import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 36, fontFamily: 'Helvetica', fontSize: 14, lineHeight: 1.35, color: '#000' },
  documentHeader: { marginBottom: 20 },
  documentTitle: { fontSize: 26, fontFamily: 'Helvetica-Bold', paddingBottom: 8, borderBottomWidth: 2, borderBottomColor: '#000', borderBottomStyle: 'solid' },
  recordContainer: { marginBottom: 18 }, recordTitle: { fontSize: 19, fontFamily: 'Helvetica-Bold', paddingBottom: 5, borderBottomWidth: 1, borderBottomColor: '#000', borderBottomStyle: 'solid', marginBottom: 12 },
  block: { marginBottom: 10 }, compactBlock: { marginBottom: 7 },
  sectionTitle: { fontSize: 16, fontFamily: 'Helvetica-Bold', paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: '#000', borderBottomStyle: 'solid', marginBottom: 8 },
  fieldLabel: { fontSize: 13, fontFamily: 'Helvetica-Bold', paddingBottom: 2, borderBottomWidth: 0.5, borderBottomColor: '#999', borderBottomStyle: 'solid', marginBottom: 3 },
  subLabel: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 3 },
  fieldValue: { fontSize: 14 }, listItem: { fontSize: 14, paddingLeft: 10, marginBottom: 2 }, noDataText: { fontSize: 14, marginTop: 30 }
});
const isEmptyDeep = v => v == null || v === '' || (Array.isArray(v) ? !v.some(x => !isEmptyDeep(x)) : typeof v === 'object' ? Object.values(v).every(isEmptyDeep) : false);
const fmt = v => typeof v === 'boolean' ? (v ? 'Yes' : 'No') : String(v ?? '');
const humanize = key => String(key).replace(/_/g, ' ').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2').replace(/^./, c => c.toUpperCase()).replace(/N S A I Ds/g, 'NSAIDs').replace(/P I C C/g, 'PICC');
const formatDate = value => { if (!value) return ''; try { const d = new Date(value.$date || value); return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }); } catch { return fmt(value); } };
const parseLabel = text => { const m = String(text || '').match(/^([A-Za-z0-9][A-Za-z0-9\s/&().#'"%<>~+=-]{1,120}?):\s+([\s\S]+)$/); return m ? { label: m[1].trim(), value: m[2].trim(), labeled: true } : { value: String(text || ''), labeled: false }; };
const splitByComma = text => { const out=[]; let cur='', depth=0; for(let i=0;i<String(text||'').length;i++){const ch=text[i]; if(ch==='(')depth++; if(ch===')')depth=Math.max(0,depth-1); if(ch===','&&depth===0){const before=cur.trim(), after=text.slice(i+1), trim=after.trimStart(), next=(trim.match(/^([A-Za-z]+)/)||[])[1]?.toLowerCase(); if((/\d$/.test(before)&&/^\d{3}\b/.test(trim))||after.length===trim.length||['and','or','then'].includes(next)){cur+=ch;}else{if(before)out.push(before);cur='';}}else cur+=ch;} if(cur.trim())out.push(cur.trim()); return out.length?out:[text]; };
const splitSentences = text => { if(!text)return[]; const parts=[];let cur='';const abbr=/(?:^|\s)(?:Mr|Mrs|Ms|Dr|St|Jr|Sr|Prof|Rev|Gen|Col|Sgt|vs|etc|approx|no|No|i\.e|e\.g)$/i; for(let i=0;i<text.length;i++){const ch=text[i];cur+=ch;if((ch!=='.'&&ch!==';')||!/\s/.test(text[i+1]||''))continue;const c=cur.slice(0,-1).trim();const marker=ch==='.'&&/(?:^|\s)\d+$/.test(c);if(marker||abbr.test(c))continue;parts.push(c.replace(/^\d+\.\s*/,''));cur='';}const tail=cur.trim().replace(/[.;]+$/,'');if(tail)parts.push(tail.replace(/^\d+\.\s*/,''));return parts; };
const narrativeBlocks = (label, value, key, splitUnlabeled=true) => { const blocks=[]; let plain=[]; const flush=()=>{if(plain.length){blocks.push({key:key+'-p-'+blocks.length,fieldLabel:blocks.length?'' : label,rows:plain});plain=[];}}; splitSentences(fmt(value)).forEach(sentence=>{const p=parseLabel(sentence), src=p.labeled?p.value:sentence, comma=splitByComma(src), rows=(p.labeled&&comma.length>=2)||(!p.labeled&&splitUnlabeled&&comma.length>=3)?comma:[src]; if(p.labeled){flush();blocks.push({key:key+'-l-'+blocks.length,fieldLabel:blocks.length?'':label,subLabel:p.label,rows});}else plain.push(...rows);});flush();return blocks; };
const scalarBlock = (label,value,key) => isEmptyDeep(value)?[]:[{key,fieldLabel:label,rows:[fmt(value)]}];
const arrayBlock = (label,value,key,splitCommas=false) => {const rows=Array.isArray(value)?value.filter(v=>!isEmptyDeep(v)).flatMap(v=>{const text=fmt(v),parts=splitCommas?splitByComma(text):[text];return parts.length>=2?parts:[text];}):[];return rows.length?[{key,fieldLabel:label,rows}]:[];};
const isAtomicNumber = value => /^-?[\d,]*\.?\d+(?:\s*\/\s*\d+(?:\.\d+)?|\s+\S.*)?$/.test(String(value || '').trim());
const objectBlocks = (label,value,key) => {const blocks=[]; const visit=(v,path,names)=>{if(isEmptyDeep(v))return;if(Array.isArray(v)){const items=v.filter(x=>!isEmptyDeep(x));if(items.every(x=>typeof x!=='object'))blocks.push({key:path,fieldLabel:blocks.length?'':label,subLabel:names.join(' - '),rows:items.map(fmt)});else items.forEach((x,i)=>visit(x,path+'-'+i,[...names,String(i+1)]));return;}if(typeof v==='object')Object.entries(v).forEach(([k,x])=>visit(x,path+'-'+k,[...names,humanize(k)]));else blocks.push({key:path,fieldLabel:blocks.length?'':label,subLabel:names.join(' - '),rows:typeof v==='string'&&!isAtomicNumber(v)?splitSentences(v):[fmt(v)]});};visit(value,key,[]);return blocks;};
const recommendationBlocks = items => {const groups=[];(items||[]).forEach(item=>{if(!item?.recommendation)return;const k=String(item.date||'');const g=groups.find(x=>x.k===k);if(g)g.rows.push(item.recommendation);else groups.push({k,date:item.date,rows:[item.recommendation]});});return groups.map((g,i)=>({key:'rec-'+i,fieldLabel:i?'':'Recommendations',subLabel:g.date?formatDate(g.date):'',rows:g.rows,compact:true}));};
const renderSection=(title,blocks,key)=>{const usable=(blocks||[]).filter(b=>b&&(b.fieldLabel||b.subLabel||b.rows?.length));if(!usable.length)return null;return <React.Fragment key={key}>{usable.map((b,i)=><View key={b.key||key+'-'+i} style={[styles.block,b.compact&&styles.compactBlock]} wrap={false}>{i===0&&<Text style={styles.sectionTitle}>{title}</Text>}{b.fieldLabel&&b.fieldLabel.trim().toLowerCase()!==title.trim().toLowerCase()&&<Text style={styles.fieldLabel}>{b.fieldLabel}</Text>}{b.subLabel&&<Text style={styles.subLabel}>{b.subLabel}</Text>}{(b.rows||[]).map((r,j)=><Text key={j} style={b.rows.length>1?styles.listItem:styles.fieldValue}>{b.rows.length>1?`${j+1}. ${r}`:r}</Text>)}</View>)}</React.Fragment>;};
const unwrap=data=>(Array.isArray(data)?data:[data]).flatMap(r=>r?.renal_protection_plan?(Array.isArray(r.renal_protection_plan)?r.renal_protection_plan:[r.renal_protection_plan]):r?.documentData?(Array.isArray(r.documentData)?r.documentData:r.documentData?.renal_protection_plan?(Array.isArray(r.documentData.renal_protection_plan)?r.documentData.renal_protection_plan:[r.documentData.renal_protection_plan]):[r.documentData]):[r]).filter(r=>r&&typeof r==='object');
export default function RenalProtectionPlanDocumentPDFTemplate({document:data}){const records=React.useMemo(()=>unwrap(data),[data]);return <Document><Page size="LETTER" style={styles.page}><View style={styles.documentHeader} wrap={false}><Text style={styles.documentTitle}>Renal Protection Plan</Text></View>{!records.length&&<Text style={styles.noDataText}>No data available</Text>}{records.map((r,i)=>{const general=[...scalarBlock('Date',formatDate(r.date),'date'),...narrativeBlocks('Type',r.type,'type'),...narrativeBlocks('Provider',r.provider,'provider',false),...narrativeBlocks('Facility',r.facility,'facility'),...narrativeBlocks('Status',r.status,'status')];return <View key={i} style={styles.recordContainer} break={i>0}><View wrap={false}><Text style={styles.recordTitle}>{`Renal Protection Plan ${i+1}`}</Text></View>{renderSection('Record Information',general,'general')}{renderSection('Findings',narrativeBlocks('Findings',r.findings,'findings'),'findings')}{renderSection('Assessment',narrativeBlocks('Assessment',r.assessment,'assessment'),'assessment')}{renderSection('Hydration',narrativeBlocks('Hydration',r.hydration,'hydration'),'hydration')}{renderSection('Nephrotoxin Avoidance',arrayBlock('Nephrotoxin Avoidance',r.nephrotoxinAvoidance,'nephrotoxin'),'nephrotoxin')}{renderSection('Monitoring',arrayBlock('Monitoring',r.monitoring,'monitoring',true),'monitoring')}{renderSection('Results',objectBlocks('Results',r.results,'results'),'results')}{renderSection('Additional Data',objectBlocks('Additional Data',r.additionalData,'additional'),'additional')}{renderSection('Plan',narrativeBlocks('Plan',r.plan,'plan'),'plan')}{renderSection('Recommendations',recommendationBlocks(r.recommendations),'recommendations')}{renderSection('Consultations',narrativeBlocks('Consultations',r.consultations,'consultations',false),'consultations')}{renderSection('Notes',narrativeBlocks('Notes',r.notes,'notes'),'notes')}</View>;})}</Page></Document>;}
