import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, paddingBottom: 64, fontFamily: 'Helvetica', fontSize: 14, color: '#000', lineHeight: 1.4 },
  documentTitle: { fontSize: 26, fontFamily: 'Helvetica-Bold', marginBottom: 16, paddingBottom: 8, borderBottomWidth: 2, borderBottomColor: '#000' },
  recordTitle: { fontSize: 19, fontFamily: 'Helvetica-Bold', marginTop: 14, marginBottom: 10, paddingBottom: 5, borderBottomWidth: 1, borderBottomColor: '#000' },
  section: { marginBottom: 8 },
  sectionTitle: { fontSize: 16, fontFamily: 'Helvetica-Bold', marginTop: 10, marginBottom: 6, paddingBottom: 3, borderBottomWidth: 1, borderBottomColor: '#000' },
  fieldLabel: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginTop: 4, marginBottom: 3, paddingBottom: 2, borderBottomWidth: 0.5, borderBottomColor: '#999' },
  value: { fontSize: 14, paddingLeft: 8, marginBottom: 2 },
  footer: { position: 'absolute', bottom: 24, left: 40, right: 40, fontSize: 9, color: '#666', textAlign: 'center', borderTopWidth: 0.5, borderTopColor: '#ccc', paddingTop: 6 },
  noData: { fontSize: 14, textAlign: 'center', marginTop: 40, color: '#666' },
});

const SECTION_TITLES = { 'record-info': 'Record Information', 'classification-evidence': 'Classification & Evidence', 'population-frequency': 'Population Frequency', 'functional-evidence': 'Functional Evidence', 'clinical-significance': 'Clinical Significance', 'therapeutic-implications': 'Therapeutic Implications', 'review-validation': 'Review & Validation', 'laboratory-details': 'Laboratory Details', 'reclassification-history': 'Reclassification History' };
const FIELD_LABELS = { geneSymbol: 'Gene Symbol', hgvsNomenclature: 'HGVS Nomenclature', genomicCoordinates: 'Genomic Coordinates', variantType: 'Variant Type', variantClassification: 'Variant Classification', acmgCriteriaApplied: 'ACMG Criteria Applied', evidenceStrength: 'Evidence Strength', alleleFrequency: 'Allele Frequency', clinvarSignificance: 'ClinVar Significance', functionalImpactPrediction: 'Functional Impact Prediction', segregationAnalysis: 'Segregation Analysis', functionalStudiesEvidence: 'Functional Studies Evidence', spliceImpactAssessment: 'Splice Impact Assessment', proteinDomainImpact: 'Protein Domain Impact', phenotypeAssociation: 'Phenotype Association', inheritancePattern: 'Inheritance Pattern', deNovoOccurrence: 'De Novo Occurrence', therapeuticImplications: 'Therapeutic Implications', reviewerConsensus: 'Reviewer Consensus', clinicalValidationStatus: 'Clinical Validation Status', laboratoryMethodology: 'Laboratory Methodology', reclassificationHistory: 'Reclassification History' };
const SECTION_FIELDS = { 'record-info': ['geneSymbol', 'hgvsNomenclature', 'genomicCoordinates', 'variantType'], 'classification-evidence': ['variantClassification', 'acmgCriteriaApplied', 'evidenceStrength'], 'population-frequency': ['alleleFrequency', 'clinvarSignificance'], 'functional-evidence': ['functionalImpactPrediction', 'segregationAnalysis', 'functionalStudiesEvidence', 'spliceImpactAssessment', 'proteinDomainImpact'], 'clinical-significance': ['phenotypeAssociation', 'inheritancePattern', 'deNovoOccurrence'], 'therapeutic-implications': ['therapeuticImplications'], 'review-validation': ['reviewerConsensus', 'clinicalValidationStatus'], 'laboratory-details': ['laboratoryMethodology'], 'reclassification-history': ['reclassificationHistory'] };
const SECTION_ORDER = Object.keys(SECTION_FIELDS);
const ARRAY_FIELDS = new Set(['acmgCriteriaApplied', 'reclassificationHistory']);
const BOOLEAN_FIELDS = new Set(['deNovoOccurrence']);
const hasValue = value => value !== null && value !== undefined && (Array.isArray(value) ? value.some(item => String(item ?? '').trim()) : typeof value === 'string' ? Boolean(value.trim()) : true);
const splitClauses = value => String(value || '').split(/;\s+|(?<!\d)\.(?:\s+)/).map(item => item.trim()).filter(Boolean);
const valuesFor = (field, value) => BOOLEAN_FIELDS.has(field) ? [value ? 'Yes' : 'No'] : ARRAY_FIELDS.has(field) ? (Array.isArray(value) ? value : [value]).map(item => String(item)).filter(Boolean) : typeof value === 'number' ? [String(value)] : splitClauses(value);
const unwrapRecords = source => (Array.isArray(source) ? source : source ? [source] : []).flatMap(record => { if (Array.isArray(record?.wrapRecordsIntoSingleDocument)) return record.wrapRecordsIntoSingleDocument; if (Array.isArray(record?.records || record?._records)) return record.records || record._records; if (record?.variant_interpretation_guidelines) return Array.isArray(record.variant_interpretation_guidelines) ? record.variant_interpretation_guidelines : [record.variant_interpretation_guidelines]; if (record?.documentData) return Array.isArray(record.documentData) ? record.documentData : record.documentData?.variant_interpretation_guidelines ? (Array.isArray(record.documentData.variant_interpretation_guidelines) ? record.documentData.variant_interpretation_guidelines : [record.documentData.variant_interpretation_guidelines]) : [record.documentData]; return [record]; }).filter(record => record && typeof record === 'object');
const renderField = (record, field, title, firstField) => { if (!hasValue(record[field])) return []; const values = valuesFor(field, record[field]); const blocks = []; for (let i = 0; i < values.length; i += 6) blocks.push(values.slice(i, i + 6)); return blocks.map((items, blockIndex) => <View key={`${field}-${blockIndex}`} wrap={false}>{firstField && blockIndex === 0 && <Text style={styles.sectionTitle}>{title}</Text>}{blockIndex === 0 && FIELD_LABELS[field].toLowerCase() !== title.toLowerCase() && <Text style={styles.fieldLabel}>{FIELD_LABELS[field]}</Text>}{items.map((item, index) => <Text key={index} style={styles.value}>{index + 1}. {item}</Text>)}</View>); };

const VariantInterpretationGuidelinesDocumentPDFTemplate = ({ document: documentProp, data, templateData }) => {
  const records = unwrapRecords(documentProp ?? data ?? templateData);
  return <Document><Page size="LETTER" style={styles.page}><Text style={styles.documentTitle}>Variant Interpretation Guidelines</Text>{records.length ? records.map((record, index) => <React.Fragment key={index}><View wrap={false} break={index > 0}><Text style={styles.recordTitle}>Variant Interpretation {index + 1}</Text></View>{SECTION_ORDER.map(sectionId => { const present = SECTION_FIELDS[sectionId].filter(field => hasValue(record[field])); if (!present.length) return null; return <View key={sectionId} style={styles.section}>{present.flatMap((field, fieldIndex) => renderField(record, field, SECTION_TITLES[sectionId], fieldIndex === 0))}</View>; })}</React.Fragment>) : <Text style={styles.noData}>No variant interpretation guidelines available.</Text>}<Text style={styles.footer} fixed>This document contains Protected Health Information (PHI). Handle in accordance with HIPAA.</Text></Page></Document>;
};

export default VariantInterpretationGuidelinesDocumentPDFTemplate;
