/**
 * Medical Collections Service
 * 
 * Single source of truth for all medical document collection names.
 * This service defines all 190 medical collection types used throughout the system.
 * 
 * Used by:
 * - documentAnalysisService.js (for AI categorization)
 * - medicalDataService.js (for data storage)
 * 
 * IMPORTANT: Keep these collections synchronized with medicalDataService.js collectionMap
 */

class MedicalCollectionsService {
  constructor() {
    // All 190 unique medical collection names
    // These map directly to MongoDB collection names
    this.allCollections = [
      // Core Medical Records
      "abnormal_results",
      "admission_assessments",
      "goals_of_care_discussions",
      "allergies",
      "appointments",
      "consultation_notes",
      "diagnoses",
      "discharge_summaries",
      "follow_ups",
      "imaging_reports",
      "imaging_orders",
      "medical_images",
      "lab_results",
      "lab_orders",
      "medical_alerts",
      "medical_certificates",
      "medical_procedures",
      "medications",
      "medication_recommendations",
      "medication_safety",
      "medication_safety_alerts",
      "prescriptions",
      "referrals",
      "vaccination_records",
      "vital_signs",
      
      // Hospital & Emergency
      "emergency_discharge_summaries",
      "emergency_reports",
      "hospital_admission_notes",
      "hospital_discharge_summaries",
      "hospital_transfer_notes",
      "hospital_course",
      "icu_flow_sheets",
      "hourly_vital_signs",
      "arterial_blood_gases",
      "continuous_infusions",
      "neurological_assessment",
      "glasgow_coma_scale",
      "cam_icu",
      "procedures_interventions",
      "nursing_notes",
      "transfer_summaries",
      "treatment_courses",
      "admission_recommendations",

      // Care Coordination
      "addiction_medicine_consultations",
      "case_management",
      "proposed_art_switch",
      "hiv_history",
      "hepatitis_c_management",
      "hepatitis_c_history",
      "food_insecurity",
      "appetite_stimulants",
      "immune_reconstitution_planning",
      "primary_prophylaxis",
      "secondary_prophylaxis",
      "cmv_monitoring_plan",

      // Surgical & Operative
      "anesthesia_records",
      "operative_reports",
      "operative_report_details",
      "patient_positioning",
      "prep_and_drape",
      "pneumoperitoneum",
      "port_placement",
      "critical_view_of_safety",
      "intraoperative_cholangiography",
      "surgical_steps",
      "pathology_gross_description",
      "closure_technique",
      "sponge_instrument_counts",
      "operative_time",
      "post_operative_reports",
      "pre_operative_assessments",
      "surgical_consent_forms",
      
      // Cardiology
      "cardiac_catheterization_reports",
      "cardiac_rehabilitation_reports",
      "cardiology_admission_notes",
      "cardiology_consultations",
      "cardiology_followup_reports",
      "ecg_reports",
      "echo_reports",
      "stress_test_reports",
      
      // Neurology
      "diagnostic_studies",
      "eeg_reports",
      "emg_reports",
      "functional_mri_studies",
      "interval_history",
      "neurology_consultations",
      "neurology_progress_notes",
      "neuropsychological_assessments",
      "neurosurgery_consultations",
      "tractography_studies",
      
      // Psychiatry & Mental Health
      "mental_health_assessments",
      "psychiatric_discharge_summaries",
      "psychiatric_evaluations",
      "psychiatric_progress_notes",
      "psychosocial_assessments",
      "therapy_session_notes",
      
      // Pediatrics
      "apgar_scores",
      "developmental_assessments",
      "newborn_screening_results",
      "pediatric_growth_charts",
      "pediatric_vaccination_records",
      "pediatric_visits",
      "well_child_examinations",
      
      // Obstetrics & Gynecology
      "amniocentesis_reports",
      "gynecology_consultations",
      "labor_delivery_records",
      "maternal_fetal_reports",
      "obstetric_ultrasound_reports",
      "postpartum_notes",
      "prenatal_testing_reports",
      "prenatal_visits",
      "ultrasound_ob_reports",
      
      // Oncology
      "biologic_therapy_records",
      "brain_tumor_characteristics",
      "brain_tumor_molecular_markers",
      "chemotherapy_records",
      "oncology_consultations",
      "oncology_followup_reports",
      "oncology_treatment_plans",
      "radiation_therapy_records",
      "tumor_board_notes",
      "tumor_marker_panels",
      
      // Endocrinology
      "diabetes_management_notes",
      "chronic_disease_management",
      "endocrinology_consultations",
      "hormone_panels",
      "hormone_therapy_records",
      "thyroid_evaluations",
      
      // Gastroenterology
      "colonoscopy_reports",
      "endoscopy_reports",
      "gastroenterology_consultations",
      "ibd_consultation_details",
      "mayo_score",
      "symptom_progression_timeline",
      "infliximab_drug_monitoring",
      "fecal_calprotectin",
      "rescue_therapy_options",
      "barriers_psychosocial_issues",
      "inflammatory_bowel_reports",
      "liver_function_assessments",
      
      // Pulmonology
      "asthma_management_notes",
      "asthma_assessments",
      "copd_assessments",
      "pulmonary_function_tests",
      "pulmonary_rehabilitation_notes",
      "pulmonology_consultations",
      "sleep_study_reports",
      "allergy_assessments",

      // Allergy & Immunology (Specialized Collections)
      "allergies_assessments",
      "allergy_skin_testing",
      "specific_ige_tests",
      "component_allergen_testing",
      "immune_function_tests",
      "challenge_tests",

      // Nephrology
      "dialysis_records",
      "dialysis_run_sheets",
      "pre_dialysis_assessment",
      "dialysis_prescription",
      "dialyzer",
      "dialysate_composition",
      "intradialytic_monitoring",
      "medications_administered",
      "post_dialysis_assessment",
      "kidney_function_reports",
      "nephrology_consultations",
      "nephrology_consultation_details",
      "kidney_disease_progression_timeline",
      "estimated_time_to_dialysis",
      "education_initiated",
      "access_planning",
      "depression_screening",
      "advance_directive_discussion",
      "prognosis_discussion",
      "transplant_evaluations",
      
      // Rheumatology
      "arthritis_assessments",
      "autoimmune_evaluations",
      "autoimmune_panels",
      "rheumatology_consultations",
      
      // Hematology
      "blood_disorder_reports",
      "bone_marrow_reports",
      "coagulation_studies",
      "hematology_consultations",
      
      // Orthopedics
      "orthopedic_consultations",
      "orthopedic_followup_notes",
      "orthopedic_operative_reports",
      
      // Ophthalmology
      "glaucoma_assessments",
      "ophthalmology_examinations",
      "retinal_examinations",
      "visual_acuity_reports",
      
      // ENT (Ear, Nose, Throat)
      "audiometry_reports",
      "ent_consultations",
      "laryngoscopy_reports",
      
      // Dermatology
      "dermatology_consultations",
      "dermatology_procedure_notes",
      "podiatry_examinations",
      "skin_biopsy_reports",
      "wound_care_assessments",
      
      // Urology
      "cystoscopy_reports",
      "urodynamic_studies",
      "urology_consultations",
      
      // Geriatrics
      "cognitive_evaluations",
      "fall_risk_assessments",
      "functional_assessments",
      "geriatric_assessments",
      "gi_risk_assessment",
      "polypharmacy_reviews",

      // Pathology
      "autopsy_reports",
      "biopsy_reports",
      "cytology_reports",
      "pathology_reports",
      
      // Radiology & Imaging
      "bone_scan_reports",
      "dexa_scan_reports",
      "interventional_radiology_notes",
      "mammography_reports",
      "mri_reports",
      "pet_scan_reports",
      "radiology_reports",
      
      // Laboratory & Specialized Tests
      "antibiogram_reports",
      "blood_glucose_logs",
      "flow_cytometry_reports",
      "genetic_testing_reports",
      "microbiology_culture_reports",
      "toxicology_reports",
      
      // Dental
      "dental_examination_reports",
      "oral_surgery_reports",
      "orthodontic_treatment_plans",
      "periodontal_charts",
      
      // Physical Therapy & Rehabilitation
      "cognitive_rehabilitation_reports",
      "occupational_therapy_reports",
      "physical_therapy_evaluations",
      "physical_therapy_notes",
      "rehabilitation_progress_notes",
      "speech_therapy_assessments",
      
      // Nursing & Clinical Notes
      "intake_output_records",
      "medication_administration_records",
      "scheduled_medications",
      "prn_medications",
      "iv_infusions",
      "blood_glucose_monitoring",
      "omissions_refusals",
      "nurse_signatures",
      "pharmacy_review",
      "monitoring_reports",
      "nicu_progress_notes",
      "nursing_assessments",
      "pain_assessment_forms",
      "progress_notes",
      "shift_handoff_notes",
      "soap_notes",
      "therapy_progress_notes",
      "vital_signs_logs",
      "wound_care_documentation",
      "wound_care_notes",
      
      // Emergency & Critical Care
      "code_blue_summaries",
      "ems_run_reports",
      "poison_control_reports",
      "rapid_response_summaries",
      "trauma_flow_sheets",
      
      // Administrative & Legal
      "administrative_data",
      "disability_evaluations",
      "dnr_orders",
      "fitness_for_duty_evaluations",
      "insurance_forms",
      "medical_power_of_attorney",
      "medical_reconciliation_forms",
      "prior_authorization_forms",
      "school_health_forms",
      "travel_health_certificates",
      "workers_comp_evaluations",
      "document_metadata",
      "workplace_accommodations",
      "employment_counseling",
      "insurance_authorizations",

      // Patient Education & Social
      "care_coordination_notes",
      "home_health_notes",
      "hospice_notes",
      "pain_management_notes",
      "patient_education_records",
      "social_work_notes",
      "social_history",
      "mental_health_resources",
      "stress_management_referrals",
      "exercise_recommendations",
      "communication_preferences",
      "data_management_instructions",

      // Telemedicine & Second Opinions
      "case_summaries",
      "second_opinion_reports",
      "telemedicine_encounters",
      
      // Research & Clinical Trials
      "clinical_trial_documents",
      "research_consent_forms",
      
      // Additional Medical Documentation (for AI extraction)
      // "hospital_course", // REMOVED: Duplicate - already defined in Hospital/ICU section (line 53)
      "specialty_fields",
      "medical_history", // Comprehensive medical history collection (includes PMH, surgical, family, social)
      "past_medical_history",
      "surgical_history",
      "family_history",
      // "social_history", // REMOVED: Duplicate - already defined in Patient Support section (line 371)
      "chief_complaints",
      "history_present_illness",
      "review_of_systems",
      "physical_examinations",
      "assessment_plans",
      "risk_factors",
      "follow_up_appointments",
      "follow_up_enhanced",
      "disease_severity",

      // Emergency Medicine Fields
      "emergency_information",
      "triage_data",
      "ed_course",
      "consultation_timeline",
      "preoperative_preparation",
      "pre_operative_preparation",
      "blood_products_ordered",
      "ed_disposition",
      "injury_details",
      "procedural_sedation",
      "work_restrictions",

      // Diabetes/Endocrinology Fields
      "diabetes_management",
      "insulin_pump_settings",
      "cgm_data",
      "insulin_regimen",
      "diabetes_education",
      "diabetes_educator",
      "hypoglycemia_management",
      "endocrine_lab_results",
      "preconception_counseling",
      "diabetes_quality_metrics",
      "pump_download_analysis",
      "foot_exam",
      "diabetes_supplies",
      "fertility_tracking",
      "pump_advanced_settings",
      "insulin_timing_instructions",
      "hypoglycemia_protocol",
      "basal_rate_adjustments",
      "bolus_adjustments",

      // IBD/Gastroenterology Fields
      "ibd_assessment",
      "disease_activity_scores",
      "endoscopy_findings",
      "ibd_biomarkers",
      "biologic_therapy",
      "extraintestinal_manifestations",
      "ibd_surgical_planning",
      "flare_management",

      // Geriatrics Fields
      "cancer_surveillance",
      "functional_status",
      "geriatric_cognitive_assessment",
      "falls_prevention_program_assessment",
      "quality_assurance",
      "lymph_node_cytomorphology",
      "cytogenetics",
      "staging_summary",
      "geriatric_nutritional_assessment",
      "mood_psychological_assessment",
      "social_functional_assessment",
      "frailty_assessment",
      "geriatric_care_planning",
      "caregiver_assessment",

      // Oncology Fields
      "cancer_diagnosis",
      "cancer_staging",
      "myeloma_specific_data",
      "chemotherapy_regimen",
      "radiation_therapy",
      "transplant_assessment",
      "performance_status",
      "tumor_markers",
      "clinical_trials",
      "response_assessment",
      "toxicity_assessment",
      "palliative_care_needs",
      "treatment_summary",
      "surgical_oncology",
      "radiation_oncology",
      "endocrine_therapy",
      "bone_health",
      "survivorship_care_plan",
      "cancer_related_side_effects",
      "oncologic_emergencies",
      "psychosocial_oncology",
      "genetic_oncology",
      "prognostic_factors",
      "integrative_oncology",
      "prophylactic_medications",
      "pre_chemotherapy_workup",
      "renal_protection_plan",
      "pain_management_plan",
      "supportive_care",
      "oncology_team",

      // Obstetrics Fields
      "obstetric_history",
      "current_pregnancy",
      "reproductive_history",
      "prenatal_screening",
      "nt_scan_result",
      "cell_free_dna_result",
      "first_trimester_screen_result",
      "anatomy_scan_result",
      "cervical_length_measurement",
      "fetal_echo_results",
      "perinatal_mental_health_referral",
      "fetal_ultrasound",
      "gestational_diabetes",
      "fetal_surveillance",
      "pregnancy_complications",
      "delivery_planning",
      "maternal_labs",
      "maternal_weight_monitoring",
      "fetal_assessment",
      "contraction_monitoring",
      "pregnancy_symptoms",
      "prenatal_education",
      "birth_plan",
      "postpartum_planning",
      "pregnancy_risk_assessment",
      "pregnancy_course",
      "risk_counseling",
      "ketone_monitoring_instructions",
      "glucometer_download_schedule",
      "carbohydrate_counting_education",
      "amniotic_fluid_index_current",
      "breastfeeding_recommendation",
      "partner_involvement",
      "diabetes_management_plan",
      "single_embryo_transfer_details",
      "single_embryo_transfer",
      "preeclampsia_monitoring",
      "infection_risk_monitoring",
      "partner_involvement_diabetes_management",
      "excessive_glucose_monitoring",
      "macrosomia_threshold",
      "postpartum_diabetes_risk",
      "gdm_recurrence_risk",
      "cervical_assessment",

      // Nephrology Fields
      "ckd_assessment",
      "proteinuria_assessment",
      "dialysis_planning",
      "current_dialysis",
      "mineral_bone_disease",
      "renal_anemia",
      "fluid_electrolyte_management",
      "renal_nutrition",
      "medication_renal_dosing",
      "glomerular_disease",
      "acute_kidney_injury",
      "polycystic_kidney_disease",
      "diabetic_nephropathy",
      "hypertensive_nephropathy",

      // Neurology Fields
      "movement_disorder_assessment",
      "parkinsonian_features",
      "gait_analysis",
      "motor_complications",
      "non_motor_symptoms",
      "neurological_exam",
      "parkinson_medications",
      "deep_brain_stimulation",
      "epilepsy_assessment",
      "headache_assessment",
      "multiple_sclerosis_assessment",
      "stroke_assessment",
      "dementia_assessment",
      "peripheral_neuropathy",
      "neuromuscular_disorder",

      // Surgery Fields
      "surgical_team",
      "operative_details",
      "surgical_approach",
      "intraoperative_findings",
      "operative_technique",
      "intraoperative_imaging",
      "specimens",
      "estimated_blood_loss",
      "complications",
      "postoperative_orders",
      "postoperative_condition",
      "discharge_planning",

      // Orthopedics Fields
      "mechanism_of_injury",
      "orthopedic_imaging",
      "orthopedic_assessment",
      "orthopedic_procedures",
      "ligament_reconstruction",
      "meniscus_repair",
      "articular_cartilage",
      "tourniquet_data",
      "postop_testing",
      "rehabilitation_protocol",
      "return_to_sport",
      "dvt_prophylaxis",
      "neurovascular_exam",
      "athlete_specific_data",

      // Pediatrics Fields
      "birth_history",
      "growth_parameters",
      "developmental_milestones",
      "pediatric_screening",
      "school_performance",
      "anticipatory_guidance",
      "behavioral_assessment",
      "adhd_assessment",
      "parental_concerns",
      "well_child_summary",
      "early_childhood_development",

      // Clinical Scores and Functional Assessments
      "clinical_scores",
      "consultation_details",
      "medication_reconciliation",
      "supplementation_plans",
      "trend_analysis",
      "home_monitoring",
      "care_coordination",
      "prognosis",
      "prognosis_records",

      // Additional Missing Fields (Only fields NOT already defined above)
      "allergy_immunology_assessment",
      "anesthesiology_assessment",
      "asthma_action_plan",
      "autoantibody_profile",
      "biopsychosocial_formulation",
      "cardiology_assessment",
      "colorectal_surgery_assessment",
      "connective_tissue_disease_assessment",
      "department",
      "dermatology_assessment",
      "diagnostic_impression",
      "document_type",
      "emergency_assessment",
      "endocrinology_assessment",
      "ent_assessment",
      "environmental_exposures",
      "facility",
      "family_meeting_notes",
      "gout_assessment",
      "headers",
      "homicide_risk_assessment",
      "neuro_imaging",  // Renamed from 'imaging' - Advanced functional neuroimaging (fMRI, DTI, tractography)
      "immunization_record",
      "immunization_status",
      "infectious_disease_assessment",
      "inflammatory_markers",
      "lupus_assessment",
      "fetal_echo",
      "umbilical_artery_doppler",
      "insulin_adjustment_protocol",
      "postpartum_glucose_monitoring",
      "amniotic_fluid_assessment",
      "continuous_glucose_monitor",
      "weekly_virtual_check_ins",
      "south_asian_nutritionist",
      "indian_diet_exchange_lists",
      "cultural_considerations",
      "thyroid_management",
      "total_weight_gain",
      "pre_pregnancy_weight",
      "diabetes_educator_training",
      "exercise_program",
      "early_maternity_leave",
      "download_glucometer",
      "estimated_delivery_date",
      "first_trimester_bleeding",
      "support_group_referral",
      "continuous_glucose_monitor_discussion",
      "glucose_monitoring_goals",
      "insulin_storage_instructions",
      "cesarean_threshold",
      "glucose_testing_weeks",
      "point_of_care_ultrasound_heart_rate",
      "lab_schedule",
      "growth_ultrasound_schedule",
      "inter_pregnancy_weight_management",
      "glucose_monitoring_frequency",
      "sleep_disturbances",
      "work_accommodations",
      "patient_emotional_response",
      "comprehensive_cardiomyopathy_panel",
      "detailed_family_pedigree",
      "acmg_guidelines_reference",
      "inheritance_pattern_details",
      "children_specific_risk",
      "cascade_testing_protocol",
      "potential_testing_outcomes",
      "psychosocial_support_services",
      "reason_for_referral",
      "medical_geneticist",
      "extended_family_history",
      "genetics_psychosocial_assessment",
      "immediate_recommendations",
      "variant_interpretation_guidelines",
      "prior_authorization_status",
      "blood_sample_collection_status",
      "fmla_documentation_note",
      "mental_status_exams",
      "myositis_assessment",
      "neurosurgery_assessment",
      "nuclear_medicine_assessment",
      "nutritional_assessment",
      "past_ocular_history",
      "ophthalmology_exam",
      "glaucoma_management",
      "post_op_testing",
      "pain_management",
      "plastic_surgery_assessment",
      "pmr_assessment",
      "preventive_medicine_assessments",
      "patient_provider",
      "provider_info",
      "psychiatric_assessment_scales",
      "psychiatric_history",
      "psychiatric_review",
      "psychiatric_treatment_plan",
      "psychotropic_medications",
      "pulmonary_imaging",
      "pulmonary_rehabilitation",
      "radiology_findings",
      "respiratory_devices",
      "respiratory_infections",
      "respiratory_medications",
      "rheumatoid_arthritis_assessment",
      "rheumatologic_assessment",
      "rheumatologic_monitoring",
      "rheumatologic_treatment",
      "scleroderma_assessment",
      "sjogrens_syndrome_assessment",
      "source",
      "spondyloarthritis_assessment",
      "substance_use_assessment",
      "suicide_risk_assessment",
      "thoracic_surgery_assessment",
      "treatment_goals",
      "urology_assessment",
      "vasculitis_assessment",
      "vital_signs_table",
      "fluid_intake",
      "fluid_output",
      "pressure_injury",
      "blood_products",
      "ventilator_settings",

      // Family Medicine & Preventive Care Fields
      "lifestyle_counseling",
      "smoking_cessation_program",
      "health_maintenance",
      "patient_instructions",
      "referrals_placed",
      "preventive_care",
      "family_medicine_assessment",
      "family_medicine_visits",

      // Gastroenterology Specific Fields
      "symptom_progression",
      "monitoring_plans",
      "nutritional_support",
      // "social_work", // REMOVED: Duplicate - social_work_notes is the active collection (line 370)
      "psychosocial_factors",
      "psc_management",
      "infusion_therapy",
      "admission_decisions",
      "care_team",
      "advance_care_planning",
      "medication_changes_new",
      "medication_changes_dose",
      "medication_changes_discontinued",

      // Geriatric Assessment collections
      "social_support",
      "geriatric_medications",
      "polypharmacy",
      "advance_directives",
      "nutritional_status",
      "home_safety",

      // Additional geriatric intervention collections
      "assistive_devices",
      "palliative_care",
      "compression_therapy",
      "medication_deprescribing",
      "cardiac_monitoring",
      "vital_signs_monitoring",
      "dietary_interventions",
      "respite_care",
      "day_programs",
      "caregiver_support_groups",
      "neuropsych_testing",
      "dementia_education",
      "safety_planning",
      "fall_prevention_education",
      "hydration_management",
      "weight_monitoring",
      "anticoagulation_management",
      "neurological_findings",
      "adult_day_program_info",

      // Additional vital signs and assessment collections
      "weight_measurements",
      "blood_pressure_readings",
      "neurological_examination",
      "family_meeting_decisions",
      "care_team_info",
      "height_measurements",
      "nutritional_supplementation",
      "caregiver_support",

      // Hematology collections
      "hematology_assessment",

      // Nephrology/CKD Management collections (NEW - January 2025)
      "follow_up_plan",
      "immediate_interventions",
      "ckd_management",
      "cardiovascular_risk_reduction",

      // AI-Generated Clinical Insights (NEW - October 2025)
      "clinical_decision_support",
      "intelligent_recommendations",
      "trending_analysis",
      "patient_specific_care_plan",
      "medication_optimization",
      "doctors_medication_recommendations",
      "doctors_medications_recommendations",
      "doctors_medications_recommendations_optimizations",
      "follow_up_intelligence",
      "patient_education_context",
      "guideline_compliance",

      // Specialty Medical Collections (December 2025 - Batch Addition)
      // Vascular Surgery
      "vascular_surgery_assessment",
      "vascular_bypass_surgery",
      "venous_insufficiency_assessment",
      "aortic_aneurysm_surveillance",
      "peripheral_artery_disease",
      "varicose_vein_treatment",
      // Transplant Surgery by Organ
      "liver_transplant_evaluation",
      "liver_transplant_follow_up",
      "heart_transplant_evaluation",
      "heart_transplant_follow_up",
      "lung_transplant_evaluation",
      "lung_transplant_follow_up",
      "kidney_transplant_follow_up",
      "pancreas_transplant_evaluation",
      "pancreas_transplant_follow_up",
      "bone_marrow_transplant_evaluation",
      "bone_marrow_transplant_follow_up",
      "stem_cell_transplant_assessment",
      // Podiatry/Foot Surgery
      "podiatry_consultations",
      "diabetic_foot_assessment",
      "bunion_surgery_evaluation",
      "foot_reconstruction",
      "heel_pain_assessment",
      "ingrown_toenail_treatment",
      "plantar_fasciitis_management",
      "foot_orthotics_assessment",
      // Oral/Maxillofacial Surgery
      "tmj_assessment",
      "facial_trauma_assessment",
      "jaw_reconstruction",
      "orthognathic_surgery_evaluation",
      "dental_implant_surgery",
      "oral_pathology_biopsy",
      // Fertility/IVF
      "ivf_cycle_monitoring",
      "egg_retrieval_procedure",
      "embryo_transfer_procedure",
      "sperm_analysis",
      "ovarian_stimulation_protocol",
      "fertility_medication_management",
      "intrauterine_insemination",
      "donor_egg_cycle",
      "surrogacy_evaluation",
      "fertility_preservation",
      // STI Testing/Sexual Health
      "sti_screening_panel",
      "hiv_pep_prophylaxis",
      "hiv_prep_management",
      "sexual_health_counseling",
      "partner_notification",
      "syphilis_treatment_follow_up",
      // Pharmacogenomics
      "pharmacogenomic_testing",
      "cyp450_panel_results",
      "drug_gene_interaction_report",
      "medication_dosing_recommendation",
      // TPN/Enteral Nutrition
      "tpn_management",
      "enteral_feeding_assessment",
      "nutrition_support_consultation",
      "tube_feeding_order",
      "parenteral_nutrition_monitoring",
      "nutrition_lab_monitoring",
      // Respiratory Therapy
      "respiratory_therapy_assessment",
      "oxygen_titration_protocol",
      "ventilator_weaning_protocol",
      "airway_clearance_therapy",
      "bronchial_hygiene_therapy",
      "cpap_bipap_management",
      // Chiropractic
      "chiropractic_consultation",
      "spinal_manipulation_record",
      "chiropractic_x_ray_review",
      "chiropractic_treatment_plan",
      // Optometry
      "optometry_examination",
      "contact_lens_fitting",
      "low_vision_evaluation",
      "vision_therapy_assessment",
      // Clinical Pharmacy MTM
      "medication_therapy_management",
      "comprehensive_medication_review",
      "medication_action_plan",
      "pharmacist_consultation",
      // Hyperbaric Medicine
      "hyperbaric_oxygen_therapy",
      "wound_healing_hyperbaric",
      "decompression_sickness_treatment",
      // Burn Unit
      "burn_assessment",
      "burn_wound_care",
      "skin_grafting_evaluation",
      "burn_rehabilitation",
      "burn_fluid_resuscitation",

      // Schema Expansion Phase 2-4 (October 2025 - Tasks 08-18)
      "nuclear_medicine_studies",
      "cardiac_device_interrogations",
      "social_determinants_of_health",
      "medication_access_programs",
      "clinical_risk_scores",
      "quality_metrics",
      "sports_medicine_evaluations",
      "occupational_medicine_evaluations",

      "care_gaps",
      "outcomes_prediction",

      // December 2025 - 80 New Collections (Emergency, Infectious Disease, Anesthesiology, Pain Management, etc.)
      "treatment_plans",
      "social_work",
      "colorectal_colonoscopies",
      "colorectal_surgery_consultations",
      "plastic_surgery_consultations",
      "bone_marrow_studies",
      "blood_smears",
      // "medical_history", // REMOVED: Duplicate - already defined in Additional Medical Documentation section (line 380)
      "lifestyle_assessments",
      "risk_calculators",
      "preventive_biomarkers",
      "screening_compliance",
      "optimization_stats",
      "ed_triage_assessment",
      "trauma_assessment",
      "trauma_scoring",
      "emergency_airway_management",
      "resuscitation_records",
      "emergency_procedures",
      "emergency_disposition",
      "emergency_observation_unit",
      "antibiotic_stewardship",
      "infection_control_records",
      "sepsis_management",
      "opportunistic_infections",
      "antimicrobial_susceptibility",
      "isolation_precautions",
      "infection_surveillance",
      "travel_medicine_assessment",
      "tropical_disease_assessment",
      "preoperative_evaluation",
      "anesthesia_consent",
      "intraoperative_monitoring",
      "postoperative_pain_management",
      "regional_anesthesia_records",
      "airway_management_records",
      "sedation_records",
      "anesthesia_complications",
      "chronic_pain_assessment",
      "opioid_risk_assessment",
      "interventional_pain_procedures",
      "pain_medication_agreements",
      "pain_functional_assessment",
      "multimodal_pain_therapy",
      "occupational_health_assessment",
      "workers_compensation_evaluation",
      "workplace_injury_report",
      "occupational_exposure_records",
      "return_to_work_plan",
      "job_hazard_analysis",
      "ergonomic_assessment",
      "pre_employment_physical",
      "cognitive_screening",
      "elder_abuse_screening",
      "goals_of_care_discussion",
      "cpap_management",
      "sleep_disorder_assessment",
      "insomnia_assessment",
      "narcolepsy_assessment",
      "sleep_apnea_management",
      "sleep_hygiene_education",
      "daytime_sleepiness_assessment",
      "sports_physical_examination",
      "concussion_assessment",
      "return_to_play_protocol",
      "athletic_injury_assessment",
      "exercise_prescription",
      "performance_assessment",
      "sports_nutrition_plan",
      "overtraining_assessment",
      "cancer_screening_records",
      "cardiovascular_risk_screening",
      "lifestyle_risk_assessment",
      "health_coaching_notes",
      "wellness_visit_documentation",
      "immunization_schedule",
      "travel_vaccination_records",
      "annual_physical_examination",
      "pressure_ulcer_risk",
      "venous_thromboembolism_risk",
      "readmission_risk_assessment",
      "mortality_risk_assessment",
      "malnutrition_risk_assessment",
      "bleeding_risk_assessment",
      "patient_care_goals",
      "patient_visits",
      "rehabilitation_goals",
      "behavioral_health_goals",
      "chronic_disease_goals",
      "consultation_requests",
      "procedure_requests",
      "therapy_requests",
      "home_health_orders",
      "durable_medical_equipment_orders"
    ];
    
    // Validate no duplicates
    const uniqueCollections = new Set(this.allCollections);
    if (uniqueCollections.size !== this.allCollections.length) {
      console.warn('⚠️ Warning: Duplicate collections detected in medicalCollectionsService');
    }
    
    console.log(`✅ MedicalCollectionsService initialized with ${this.allCollections.length} collections`);
  }
  
  /**
   * Get all medical collection names
   * @returns {string[]} Array of all collection names
   */
  getAllCollections() {
    return this.allCollections;
  }
  
  /**
   * Check if a collection name is valid
   * @param {string} collectionName
   * @returns {boolean}
   */
  isValidCollection(collectionName) {
    return this.allCollections.includes(collectionName);
  }

  /**
   * Check if a collection is a medical collection (used by SecureDataAccess)
   * @param {string} collectionName
   * @returns {boolean}
   */
  isMedicalCollection(collectionName) {
    return this.allCollections.includes(collectionName);
  }

  /**
   * Get collection count
   * @returns {number}
   */
  getCollectionCount() {
    return this.allCollections.length;
  }
}

// Create singleton instance
const medicalCollectionsService = new MedicalCollectionsService();

// Export singleton
module.exports = medicalCollectionsService;