/**
 * Optimized wrapper for generated medical functions
 * Uses patient.medicalData to skip empty collections for 85-90% speed improvement
 */

const { medicalCategoryFunctions: generatedMedicalFunctions } = require('./generatedMedicalFunctions');
const medicalDataService = require('./medicalDataService');

// Collection mapping for each function
const functionCollectionMap = {
  getAbnormalResults: 'abnormal_results',
  getAccessPlanning: 'access_planning',
  getAcmgGuidelinesReference: 'acmg_guidelines_reference',
  getAcuteKidneyInjury: 'acute_kidney_injury',
  getAddictionMedicineConsultations: 'addiction_medicine_consultations',
  getAdhdAssessment: 'adhd_assessment',
  getAdministrativeData: 'administrative_data',
  getAdmissionAssessments: 'admission_assessments',
  getAdmissionDecisions: 'admission_decisions',
  getAdmissionRecommendations: 'admission_recommendations',
  getAdultDayProgramInfo: 'adult_day_program_info',
  getAdvanceCarePlanning: 'advance_care_planning',
  getAdvanceDirectiveDiscussion: 'advance_directive_discussion',
  getAdvanceDirectives: 'advance_directives',
  getGeriatricCarePlanning: 'geriatric_care_planning',
  getGoalsOfCareDiscussions: 'goals_of_care_discussions',
  getAirwayManagementRecords: 'airway_management_records',
  getAllergies: 'allergies',
  getAllergiesAssessments: 'allergies_assessments',
  getAllergyAssessments: 'allergy_assessments',
  getAllergyImmunologyAssessment: 'allergy_immunology_assessment',
  getAllergySkinTesting: 'allergy_skin_testing',
  getAmniocentesisReports: 'amniocentesis_reports',
  getAmnioticFluidAssessment: 'amniotic_fluid_assessment',
  getAmnioticFluidIndexCurrent: 'amniotic_fluid_index_current',
  getAnatomyScanResult: 'anatomy_scan_result',
  getAnesthesiaComplications: 'anesthesia_complications',
  getAnesthesiaConsent: 'anesthesia_consent',
  getAnesthesiaRecords: 'anesthesia_records',
  getAnesthesiologyAssessment: 'anesthesiology_assessment',
  getAnnualPhysicalExamination: 'annual_physical_examination',
  getAntibiogramReports: 'antibiogram_reports',
  getAntibioticStewardship: 'antibiotic_stewardship',
  getAnticipatoryGuidance: 'anticipatory_guidance',
  getAnticoagulationManagement: 'anticoagulation_management',
  getAntimicrobialSusceptibility: 'antimicrobial_susceptibility',
  getApgarScores: 'apgar_scores',
  getAppetiteStimulants: 'appetite_stimulants',
  getAppointments: 'appointments',
  getArterialBloodGases: 'arterial_blood_gases',
  getArthritisAssessments: 'arthritis_assessments',
  getArticularCartilage: 'articular_cartilage',
  getAssessmentPlans: 'assessment_plans',
  getAssistiveDevices: 'assistive_devices',
  getAsthmaActionPlan: 'asthma_action_plan',
  getAsthmaAssessments: 'asthma_assessments',
  getAsthmaManagementNotes: 'asthma_management_notes',
  getAthleteSpecificData: 'athlete_specific_data',
  getAthleticInjuryAssessment: 'athletic_injury_assessment',
  getAudiometryReports: 'audiometry_reports',
  getAutoantibodyProfile: 'autoantibody_profile',
  getAutoimmuneEvaluations: 'autoimmune_evaluations',
  getAutoimmunePanels: 'autoimmune_panels',
  getAutopsyReports: 'autopsy_reports',
  getBarriersPsychosocialIssues: 'barriers_psychosocial_issues',
  getBasalRateAdjustments: 'basal_rate_adjustments',
  getBehavioralAssessment: 'behavioral_assessment',
  getBehavioralHealthGoals: 'behavioral_health_goals',
  getBiologicTherapy: 'biologic_therapy',
  getBiologicTherapyRecords: 'biologic_therapy_records',
  getBiopsyReports: 'biopsy_reports',
  getBiopsychosocialFormulation: 'biopsychosocial_formulation',
  getBirthHistory: 'birth_history',
  getBirthPlan: 'birth_plan',
  getBleedingRiskAssessment: 'bleeding_risk_assessment',
  getBloodDisorderReports: 'blood_disorder_reports',
  getBloodGlucoseLogs: 'blood_glucose_logs',
  getBloodGlucoseMonitoring: 'blood_glucose_monitoring',
  getBloodPressureReadings: 'blood_pressure_readings',
  getBloodProducts: 'blood_products',
  getBloodProductsOrdered: 'blood_products_ordered',
  getBloodSampleCollectionStatus: 'blood_sample_collection_status',
  getBloodSmears: 'blood_smears',
  getBolusAdjustments: 'bolus_adjustments',
  getBoneHealth: 'bone_health',
  getBoneMarrowReports: 'bone_marrow_reports',
  getBoneMarrowStudies: 'bone_marrow_studies',
  getBoneScanReports: 'bone_scan_reports',
  getBrainTumorCharacteristics: 'brain_tumor_characteristics',
  getBrainTumorMolecularMarkers: 'brain_tumor_molecular_markers',
  getBreastfeedingRecommendation: 'breastfeeding_recommendation',
  getCamIcu: 'cam_icu',
  getCancerDiagnosis: 'cancer_diagnosis',
  getCancerRelatedSideEffects: 'cancer_related_side_effects',
  getCancerScreeningRecords: 'cancer_screening_records',
  getCancerStaging: 'cancer_staging',
  getCancerSurveillance: 'cancer_surveillance',
  getCarbohydrateCountingEducation: 'carbohydrate_counting_education',
  getCardiacCatheterizationReports: 'cardiac_catheterization_reports',
  getCardiacDeviceInterrogations: 'cardiac_device_interrogations',
  getCardiacMonitoring: 'cardiac_monitoring',
  getCardiacRehabilitationReports: 'cardiac_rehabilitation_reports',
  getCardiologyAdmissionNotes: 'cardiology_admission_notes',
  getCardiologyAssessment: 'cardiology_assessment',
  getCardiologyConsultations: 'cardiology_consultations',
  getCardiologyFollowupReports: 'cardiology_followup_reports',
  getCardiovascularRiskReduction: 'cardiovascular_risk_reduction',
  getCardiovascularRiskScreening: 'cardiovascular_risk_screening',
  getCareCoordination: 'care_coordination',
  getCareCoordinationNotes: 'care_coordination_notes',
  getCareGaps: 'care_gaps',
  getCareTeam: 'care_team',
  getCareTeamInfo: 'care_team_info',
  getCaregiverAssessment: 'caregiver_assessment',
  getCaregiverSupport: 'caregiver_support',
  getCaregiverSupportGroups: 'caregiver_support_groups',
  getCascadeTestingProtocol: 'cascade_testing_protocol',
  getCaseManagement: 'case_management',
  getCaseSummaries: 'case_summaries',
  getCellFreeDnaResult: 'cell_free_dna_result',
  getCervicalAssessment: 'cervical_assessment',
  getCervicalLengthMeasurement: 'cervical_length_measurement',
  getCesareanThreshold: 'cesarean_threshold',
  getCgmData: 'cgm_data',
  getChallengeTests: 'challenge_tests',
  getChemotherapyRecords: 'chemotherapy_records',
  getChemotherapyRegimen: 'chemotherapy_regimen',
  getChiefComplaints: 'chief_complaints',
  getChildrenSpecificRisk: 'children_specific_risk',
  getChronicDiseaseGoals: 'chronic_disease_goals',
  getChronicDiseaseManagement: 'chronic_disease_management',
  getChronicPainAssessment: 'chronic_pain_assessment',
  getCkdAssessment: 'ckd_assessment',
  getCkdManagement: 'ckd_management',
  getClinicalDecisionSupport: 'clinical_decision_support',
  getClinicalRiskScores: 'clinical_risk_scores',
  getClinicalScores: 'clinical_scores',
  getClinicalTrialDocuments: 'clinical_trial_documents',
  getClinicalTrials: 'clinical_trials',
  getClosureTechnique: 'closure_technique',
  getCmvMonitoringPlan: 'cmv_monitoring_plan',
  getCoagulationStudies: 'coagulation_studies',
  getCodeBlueSummaries: 'code_blue_summaries',
  getCognitiveEvaluations: 'cognitive_evaluations',
  getCognitiveRehabilitationReports: 'cognitive_rehabilitation_reports',
  getCognitiveScreening: 'cognitive_screening',
  getColonoscopyReports: 'colonoscopy_reports',
  getColorectalColonoscopies: 'colorectal_colonoscopies',
  getColorectalSurgeryAssessment: 'colorectal_surgery_assessment',
  getColorectalSurgeryConsultations: 'colorectal_surgery_consultations',
  getCommunicationPreferences: 'communication_preferences',
  getComplications: 'complications',
  getComponentAllergenTesting: 'component_allergen_testing',
  getComprehensiveCardiomyopathyPanel: 'comprehensive_cardiomyopathy_panel',
  getCompressionTherapy: 'compression_therapy',
  getConcussionAssessment: 'concussion_assessment',
  getConnectiveTissueDiseaseAssessment: 'connective_tissue_disease_assessment',
  getConsultationDetails: 'consultation_details',
  getConsultationNotes: 'consultation_notes',
  getConsultationRequests: 'consultation_requests',
  getConsultationTimeline: 'consultation_timeline',
  getContinuousGlucoseMonitor: 'continuous_glucose_monitor',
  getContinuousGlucoseMonitorDiscussion: 'continuous_glucose_monitor_discussion',
  getContinuousInfusions: 'continuous_infusions',
  getContractionMonitoring: 'contraction_monitoring',
  getCopdAssessments: 'copd_assessments',
  getCpapManagement: 'cpap_management',
  getCriticalViewOfSafety: 'critical_view_of_safety',
  getCulturalConsiderations: 'cultural_considerations',
  getCurrentDialysis: 'current_dialysis',
  getCurrentPregnancy: 'current_pregnancy',
  getCystoscopyReports: 'cystoscopy_reports',
  getCytogenetics: 'cytogenetics',
  getCytologyReports: 'cytology_reports',
  getDataManagementInstructions: 'data_management_instructions',
  getDayPrograms: 'day_programs',
  getDaytimeSleepinessAssessment: 'daytime_sleepiness_assessment',
  getDeepBrainStimulation: 'deep_brain_stimulation',
  getDeliveryPlanning: 'delivery_planning',
  getDementiaAssessment: 'dementia_assessment',
  getDementiaEducation: 'dementia_education',
  getDentalExaminationReports: 'dental_examination_reports',
  getDepartment: 'department',
  getDepressionScreening: 'depression_screening',
  getDermatologyAssessment: 'dermatology_assessment',
  getDermatologyConsultations: 'dermatology_consultations',
  getDermatologyProcedureNotes: 'dermatology_procedure_notes',
  getDetailedFamilyPedigree: 'detailed_family_pedigree',
  getDevelopmentalAssessments: 'developmental_assessments',
  getDevelopmentalMilestones: 'developmental_milestones',
  getDexaScanReports: 'dexa_scan_reports',
  getDiabetesEducation: 'diabetes_education',
  getDiabetesEducator: 'diabetes_educator',
  getDiabetesEducatorTraining: 'diabetes_educator_training',
  getDiabetesManagement: 'diabetes_management',
  getDiabetesManagementNotes: 'diabetes_management_notes',
  getDiabetesManagementPlan: 'diabetes_management_plan',
  getDiabetesQualityMetrics: 'diabetes_quality_metrics',
  getDiabetesSupplies: 'diabetes_supplies',
  getDiabeticNephropathy: 'diabetic_nephropathy',
  getDiagnoses: 'diagnoses',
  getDiagnosticImpression: 'diagnostic_impression',
  getDiagnosticStudies: 'diagnostic_studies',
  getDialysateComposition: 'dialysate_composition',
  getDialysisPlanning: 'dialysis_planning',
  getDialysisPrescription: 'dialysis_prescription',
  getDialysisRecords: 'dialysis_records',
  getDialysisRunSheets: 'dialysis_run_sheets',
  getDialyzer: 'dialyzer',
  getDietaryInterventions: 'dietary_interventions',
  getDisabilityEvaluations: 'disability_evaluations',
  getDischargePlanning: 'discharge_planning',
  getDischargeSummaries: 'discharge_summaries',
  getDiseaseActivityScores: 'disease_activity_scores',
  getDiseaseSeverity: 'disease_severity',
  getDnrOrders: 'dnr_orders',
  getDoctorsMedicationRecommendations: 'doctors_medication_recommendations',
  getDoctorsMedicationsRecommendations: 'doctors_medications_recommendations',
  getDoctorsMedicationsRecommendationsOptimizations: 'doctors_medications_recommendations_optimizations',
  getDocumentMetadata: 'document_metadata',
  getDocumentType: 'document_type',
  getDownloadGlucometer: 'download_glucometer',
  getDurableMedicalEquipmentOrders: 'durable_medical_equipment_orders',
  getDvtProphylaxis: 'dvt_prophylaxis',
  getEarlyChildhoodDevelopment: 'early_childhood_development',
  getEarlyMaternityLeave: 'early_maternity_leave',
  getEcgReports: 'ecg_reports',
  getEchoReports: 'echo_reports',
  getEdCourse: 'ed_course',
  getEdDisposition: 'ed_disposition',
  getEdTriageAssessment: 'ed_triage_assessment',
  getEducationInitiated: 'education_initiated',
  getEegReports: 'eeg_reports',
  getElderAbuseScreening: 'elder_abuse_screening',
  getEmergencyAirwayManagement: 'emergency_airway_management',
  getEmergencyAssessment: 'emergency_assessment',
  getEmergencyDischargeSummaries: 'emergency_discharge_summaries',
  getEmergencyDisposition: 'emergency_disposition',
  getEmergencyInformation: 'emergency_information',
  getEmergencyObservationUnit: 'emergency_observation_unit',
  getEmergencyProcedures: 'emergency_procedures',
  getEmergencyReports: 'emergency_reports',
  getEmgReports: 'emg_reports',
  getEmploymentCounseling: 'employment_counseling',
  getEmsRunReports: 'ems_run_reports',
  getEndocrineLabResults: 'endocrine_lab_results',
  getEndocrineTherapy: 'endocrine_therapy',
  getEndocrinologyAssessment: 'endocrinology_assessment',
  getEndocrinologyConsultations: 'endocrinology_consultations',
  getEndoscopyFindings: 'endoscopy_findings',
  getEndoscopyReports: 'endoscopy_reports',
  getEntAssessment: 'ent_assessment',
  getEntConsultations: 'ent_consultations',
  getEnvironmentalExposures: 'environmental_exposures',
  getEpilepsyAssessment: 'epilepsy_assessment',
  getErgonomicAssessment: 'ergonomic_assessment',
  getEstimatedBloodLoss: 'estimated_blood_loss',
  getEstimatedDeliveryDate: 'estimated_delivery_date',
  getEstimatedTimeToDialysis: 'estimated_time_to_dialysis',
  getExcessiveGlucoseMonitoring: 'excessive_glucose_monitoring',
  getExercisePrescription: 'exercise_prescription',
  getExerciseProgram: 'exercise_program',
  getExerciseRecommendations: 'exercise_recommendations',
  getExtendedFamilyHistory: 'extended_family_history',
  getExtraintestinalManifestations: 'extraintestinal_manifestations',
  getFacility: 'facility',
  getFallPreventionEducation: 'fall_prevention_education',
  getFallRiskAssessments: 'fall_risk_assessments',
  getFallsPreventionProgramAssessment: 'falls_prevention_program_assessment',
  getFamilyHistory: 'family_history',
  getFamilyMedicineAssessment: 'family_medicine_assessment',
  getFamilyMedicineVisits: 'family_medicine_visits',
  getFamilyMeetingDecisions: 'family_meeting_decisions',
  getFamilyMeetingNotes: 'family_meeting_notes',
  getFecalCalprotectin: 'fecal_calprotectin',
  getFertilityTracking: 'fertility_tracking',
  getFetalAssessment: 'fetal_assessment',
  getFetalEcho: 'fetal_echo',
  getFetalEchoResults: 'fetal_echo_results',
  getFetalSurveillance: 'fetal_surveillance',
  getFetalUltrasound: 'fetal_ultrasound',
  getFirstTrimesterBleeding: 'first_trimester_bleeding',
  getFirstTrimesterScreenResult: 'first_trimester_screen_result',
  getFitnessForDutyEvaluations: 'fitness_for_duty_evaluations',
  getFlareManagement: 'flare_management',
  getFlowCytometryReports: 'flow_cytometry_reports',
  getFluidElectrolyteManagement: 'fluid_electrolyte_management',
  getFluidIntake: 'fluid_intake',
  getFluidOutput: 'fluid_output',
  getFmlaDocumentationNote: 'fmla_documentation_note',
  getFollowUpAppointments: 'follow_up_appointments',
  getFollowUpEnhanced: 'follow_up_enhanced',
  getFollowUpIntelligence: 'follow_up_intelligence',
  getFollowUpPlan: 'follow_up_plan',
  getFollowUps: 'follow_ups',
  getFoodInsecurity: 'food_insecurity',
  getFootExam: 'foot_exam',
  getFrailtyAssessment: 'frailty_assessment',
  getFunctionalAssessments: 'functional_assessments',
  getFunctionalMriStudies: 'functional_mri_studies',
  getFunctionalStatus: 'functional_status',
  getGaitAnalysis: 'gait_analysis',
  getGastroenterologyConsultations: 'gastroenterology_consultations',
  getGdmRecurrenceRisk: 'gdm_recurrence_risk',
  getGeneticOncology: 'genetic_oncology',
  getGeneticTestingReports: 'genetic_testing_reports',
  getGeneticsPsychosocialAssessment: 'genetics_psychosocial_assessment',
  getGeriatricAssessments: 'geriatric_assessments',
  getGeriatricCognitiveAssessment: 'geriatric_cognitive_assessment',
  getGeriatricMedications: 'geriatric_medications',
  getGeriatricNutritionalAssessment: 'geriatric_nutritional_assessment',
  getGestationalDiabetes: 'gestational_diabetes',
  getGiRiskAssessment: 'gi_risk_assessment',
  getGlasgowComaScale: 'glasgow_coma_scale',
  getGlaucomaAssessments: 'glaucoma_assessments',
  getGlaucomaManagement: 'glaucoma_management',
  getGlomerularDisease: 'glomerular_disease',
  getGlucometerDownloadSchedule: 'glucometer_download_schedule',
  getGlucoseMonitoringFrequency: 'glucose_monitoring_frequency',
  getGlucoseMonitoringGoals: 'glucose_monitoring_goals',
  getGlucoseTestingWeeks: 'glucose_testing_weeks',
  getGoalsOfCareDiscussion: 'goals_of_care_discussion',
  getGoutAssessment: 'gout_assessment',
  getGrowthParameters: 'growth_parameters',
  getGrowthUltrasoundSchedule: 'growth_ultrasound_schedule',
  getGuidelineCompliance: 'guideline_compliance',
  getGynecologyConsultations: 'gynecology_consultations',
  getHeadacheAssessment: 'headache_assessment',
  getHeaders: 'headers',
  getHealthCoachingNotes: 'health_coaching_notes',
  getHealthMaintenance: 'health_maintenance',
  getHeightMeasurements: 'height_measurements',
  getHematologyAssessment: 'hematology_assessment',
  getHematologyConsultations: 'hematology_consultations',
  getHepatitisCHistory: 'hepatitis_c_history',
  getHepatitisCManagement: 'hepatitis_c_management',
  getHistoryPresentIllness: 'history_present_illness',
  getHivHistory: 'hiv_history',
  getHomeHealthNotes: 'home_health_notes',
  getHomeHealthOrders: 'home_health_orders',
  getHomeMonitoring: 'home_monitoring',
  getHomeSafety: 'home_safety',
  getHomicideRiskAssessment: 'homicide_risk_assessment',
  getHormonePanels: 'hormone_panels',
  getHormoneTherapyRecords: 'hormone_therapy_records',
  getHospiceNotes: 'hospice_notes',
  getHospitalAdmissionNotes: 'hospital_admission_notes',
  getHospitalCourse: 'hospital_course',
  getHospitalDischargeSummaries: 'hospital_discharge_summaries',
  getHospitalTransferNotes: 'hospital_transfer_notes',
  getHourlyVitalSigns: 'hourly_vital_signs',
  getHydrationManagement: 'hydration_management',
  getHypertensiveNephropathy: 'hypertensive_nephropathy',
  getHypoglycemiaManagement: 'hypoglycemia_management',
  getHypoglycemiaProtocol: 'hypoglycemia_protocol',
  getIbdAssessment: 'ibd_assessment',
  getIbdBiomarkers: 'ibd_biomarkers',
  getIbdConsultationDetails: 'ibd_consultation_details',
  getIbdSurgicalPlanning: 'ibd_surgical_planning',
  getIcuFlowSheets: 'icu_flow_sheets',
  getImagingOrders: 'imaging_orders',
  getImagingReports: 'imaging_reports',
  getMedicalImages: 'medical_images',
  getImmediateInterventions: 'immediate_interventions',
  getImmediateRecommendations: 'immediate_recommendations',
  getImmuneFunctionTests: 'immune_function_tests',
  getImmuneReconstitutionPlanning: 'immune_reconstitution_planning',
  getImmunizationRecord: 'immunization_record',
  getImmunizationSchedule: 'immunization_schedule',
  getImmunizationStatus: 'immunization_status',
  getIndianDietExchangeLists: 'indian_diet_exchange_lists',
  getInfectionControlRecords: 'infection_control_records',
  getInfectionRiskMonitoring: 'infection_risk_monitoring',
  getInfectionSurveillance: 'infection_surveillance',
  getInfectiousDiseaseAssessment: 'infectious_disease_assessment',
  getInflammatoryBowelReports: 'inflammatory_bowel_reports',
  getInflammatoryMarkers: 'inflammatory_markers',
  getInfliximabDrugMonitoring: 'infliximab_drug_monitoring',
  getInfusionTherapy: 'infusion_therapy',
  getInheritancePatternDetails: 'inheritance_pattern_details',
  getInjuryDetails: 'injury_details',
  getInsomniaAssessment: 'insomnia_assessment',
  getInsulinAdjustmentProtocol: 'insulin_adjustment_protocol',
  getInsulinPumpSettings: 'insulin_pump_settings',
  getInsulinRegimen: 'insulin_regimen',
  getInsulinStorageInstructions: 'insulin_storage_instructions',
  getInsulinTimingInstructions: 'insulin_timing_instructions',
  getInsuranceAuthorizations: 'insurance_authorizations',
  getInsuranceForms: 'insurance_forms',
  getIntakeOutputRecords: 'intake_output_records',
  getIntegrativeOncology: 'integrative_oncology',
  getIntelligentRecommendations: 'intelligent_recommendations',
  getInterPregnancyWeightManagement: 'inter_pregnancy_weight_management',
  getIntervalHistory: 'interval_history',
  getInterventionalPainProcedures: 'interventional_pain_procedures',
  getInterventionalRadiologyNotes: 'interventional_radiology_notes',
  getIntradialyticMonitoring: 'intradialytic_monitoring',
  getIntraoperativeCholangiography: 'intraoperative_cholangiography',
  getIntraoperativeFindings: 'intraoperative_findings',
  getIntraoperativeImaging: 'intraoperative_imaging',
  getIntraoperativeMonitoring: 'intraoperative_monitoring',
  getIsolationPrecautions: 'isolation_precautions',
  getIvInfusions: 'iv_infusions',
  getJobHazardAnalysis: 'job_hazard_analysis',
  getKetoneMonitoringInstructions: 'ketone_monitoring_instructions',
  getKidneyDiseaseProgressionTimeline: 'kidney_disease_progression_timeline',
  getKidneyFunctionReports: 'kidney_function_reports',
  getLabOrders: 'lab_orders',
  getLabResults: 'lab_results',
  getLabSchedule: 'lab_schedule',
  getLaborDeliveryRecords: 'labor_delivery_records',
  getLaryngoscopyReports: 'laryngoscopy_reports',
  getLifestyleAssessments: 'lifestyle_assessments',
  getLifestyleCounseling: 'lifestyle_counseling',
  getLifestyleRiskAssessment: 'lifestyle_risk_assessment',
  getLigamentReconstruction: 'ligament_reconstruction',
  getLiverFunctionAssessments: 'liver_function_assessments',
  getLupusAssessment: 'lupus_assessment',
  getLymphNodeCytomorphology: 'lymph_node_cytomorphology',
  getMacrosomiaThreshold: 'macrosomia_threshold',
  getMalnutritionRiskAssessment: 'malnutrition_risk_assessment',
  getMammographyReports: 'mammography_reports',
  getMaternalFetalReports: 'maternal_fetal_reports',
  getMaternalLabs: 'maternal_labs',
  getMaternalWeightMonitoring: 'maternal_weight_monitoring',
  getMayoScore: 'mayo_score',
  getMechanismOfInjury: 'mechanism_of_injury',
  getMedicalAlerts: 'medical_alerts',
  getMedicalCertificates: 'medical_certificates',
  getMedicalGeneticist: 'medical_geneticist',
  getMedicalHistory: 'medical_history',
  getPastMedicalHistory: 'past_medical_history',
  getMedicalPowerOfAttorney: 'medical_power_of_attorney',
  getMedicalProcedures: 'medical_procedures',
  getMedicalReconciliationForms: 'medical_reconciliation_forms',
  getMedicationAccessPrograms: 'medication_access_programs',
  getMedicationAdministrationRecords: 'medication_administration_records',
  getMedicationChangesDiscontinued: 'medication_changes_discontinued',
  getMedicationChangesDose: 'medication_changes_dose',
  getMedicationChangesNew: 'medication_changes_new',
  getMedicationDeprescribing: 'medication_deprescribing',
  getMedicationOptimization: 'medication_optimization',
  getBurnFluidResuscitation: 'burn_fluid_resuscitation',
  getBurnRehabilitation: 'burn_rehabilitation',
  getSkinGraftingEvaluation: 'skin_grafting_evaluation',
  getBurnWoundCare: 'burn_wound_care',
  getBurnAssessment: 'burn_assessment',
  getDecompressionSicknessTreatment: 'decompression_sickness_treatment',
  getWoundHealingHyperbaric: 'wound_healing_hyperbaric',
  getHyperbaricOxygenTherapy: 'hyperbaric_oxygen_therapy',
  getPharmacistConsultation: 'pharmacist_consultation',
  getMedicationActionPlan: 'medication_action_plan',
  getComprehensiveMedicationReview: 'comprehensive_medication_review',
  getMedicationTherapyManagement: 'medication_therapy_management',
  getVisionTherapyAssessment: 'vision_therapy_assessment',
  getLowVisionEvaluation: 'low_vision_evaluation',
  getContactLensFitting: 'contact_lens_fitting',
  getOptometryExamination: 'optometry_examination',
  getChiropracticTreatmentPlan: 'chiropractic_treatment_plan',
  getChiropracticXRayReview: 'chiropractic_x_ray_review',
  getSpinalManipulationRecord: 'spinal_manipulation_record',
  getChiropracticConsultation: 'chiropractic_consultation',
  getCpapBipapManagement: 'cpap_bipap_management',
  getBronchialHygieneTherapy: 'bronchial_hygiene_therapy',
  getAirwayClearanceTherapy: 'airway_clearance_therapy',
  getVentilatorWeaningProtocol: 'ventilator_weaning_protocol',
  getOxygenTitrationProtocol: 'oxygen_titration_protocol',
  getRespiratoryTherapyAssessment: 'respiratory_therapy_assessment',
  getNutritionLabMonitoring: 'nutrition_lab_monitoring',
  getParenteralNutritionMonitoring: 'parenteral_nutrition_monitoring',
  getTubeFeedingOrder: 'tube_feeding_order',
  getNutritionSupportConsultation: 'nutrition_support_consultation',
  getEnteralFeedingAssessment: 'enteral_feeding_assessment',
  getTpnManagement: 'tpn_management',
  getMedicationDosingRecommendation: 'medication_dosing_recommendation',
  getDrugGeneInteractionReport: 'drug_gene_interaction_report',
  getCyp450PanelResults: 'cyp450_panel_results',
  getPharmacogenomicTesting: 'pharmacogenomic_testing',
  getSyphilisTreatmentFollowUp: 'syphilis_treatment_follow_up',
  getPartnerNotification: 'partner_notification',
  getSexualHealthCounseling: 'sexual_health_counseling',
  getHivPrepManagement: 'hiv_prep_management',
  getHivPepProphylaxis: 'hiv_pep_prophylaxis',
  getStiScreeningPanel: 'sti_screening_panel',
  getFertilityPreservation: 'fertility_preservation',
  getSurrogacyEvaluation: 'surrogacy_evaluation',
  getDonorEggCycle: 'donor_egg_cycle',
  getIntrauterineInsemination: 'intrauterine_insemination',
  getFertilityMedicationManagement: 'fertility_medication_management',
  getOvarianStimulationProtocol: 'ovarian_stimulation_protocol',
  getSpermAnalysis: 'sperm_analysis',
  getEmbryoTransferProcedure: 'embryo_transfer_procedure',
  getEggRetrievalProcedure: 'egg_retrieval_procedure',
  getIvfCycleMonitoring: 'ivf_cycle_monitoring',
  getOralPathologyBiopsy: 'oral_pathology_biopsy',
  getDentalImplantSurgery: 'dental_implant_surgery',
  getOrthognathicSurgeryEvaluation: 'orthognathic_surgery_evaluation',
  getJawReconstruction: 'jaw_reconstruction',
  getFacialTraumaAssessment: 'facial_trauma_assessment',
  getTmjAssessment: 'tmj_assessment',
  getFootOrthoticsAssessment: 'foot_orthotics_assessment',
  getPlantarFasciitisManagement: 'plantar_fasciitis_management',
  getIngrownToenailTreatment: 'ingrown_toenail_treatment',
  getHeelPainAssessment: 'heel_pain_assessment',
  getFootReconstruction: 'foot_reconstruction',
  getBunionSurgeryEvaluation: 'bunion_surgery_evaluation',
  getDiabeticFootAssessment: 'diabetic_foot_assessment',
  getPodiatryConsultations: 'podiatry_consultations',
  getStemCellTransplantAssessment: 'stem_cell_transplant_assessment',
  getBoneMarrowTransplantFollowUp: 'bone_marrow_transplant_follow_up',
  getBoneMarrowTransplantEvaluation: 'bone_marrow_transplant_evaluation',
  getPancreasTransplantFollowUp: 'pancreas_transplant_follow_up',
  getPancreasTransplantEvaluation: 'pancreas_transplant_evaluation',
  getKidneyTransplantFollowUp: 'kidney_transplant_follow_up',
  getLungTransplantFollowUp: 'lung_transplant_follow_up',
  getLungTransplantEvaluation: 'lung_transplant_evaluation',
  getHeartTransplantFollowUp: 'heart_transplant_follow_up',
  getHeartTransplantEvaluation: 'heart_transplant_evaluation',
  getLiverTransplantFollowUp: 'liver_transplant_follow_up',
  getVaricoseVeinTreatment: 'varicose_vein_treatment',
  getPeripheralArteryDisease: 'peripheral_artery_disease',
  getAorticAneurysmSurveillance: 'aortic_aneurysm_surveillance',
  getVenousInsufficiencyAssessment: 'venous_insufficiency_assessment',
  getVascularBypassSurgery: 'vascular_bypass_surgery',
  getLiverTransplantEvaluation: 'liver_transplant_evaluation',
  getVascularSurgeryAssessment: 'vascular_surgery_assessment',
  getMedicationRecommendations: 'medication_recommendations',
  getMedicationReconciliation: 'medication_reconciliation',
  getMedicationRenalDosing: 'medication_renal_dosing',
  getMedicationSafety: 'medication_safety',
  getMedicationSafetyAlerts: 'medication_safety_alerts',
  getMedications: 'medications',
  getMedicationsAdministered: 'medications_administered',
  getMeniscusRepair: 'meniscus_repair',
  getMentalHealthAssessments: 'mental_health_assessments',
  getMentalHealthResources: 'mental_health_resources',
  getMentalStatusExams: 'mental_status_exams',
  getMicrobiologyCultureReports: 'microbiology_culture_reports',
  getMineralBoneDisease: 'mineral_bone_disease',
  getMonitoringPlans: 'monitoring_plans',
  getMonitoringReports: 'monitoring_reports',
  getMoodPsychologicalAssessment: 'mood_psychological_assessment',
  getMortalityRiskAssessment: 'mortality_risk_assessment',
  getMotorComplications: 'motor_complications',
  getMovementDisorderAssessment: 'movement_disorder_assessment',
  getMriReports: 'mri_reports',
  getMultimodalPainTherapy: 'multimodal_pain_therapy',
  getMultipleSclerosisAssessment: 'multiple_sclerosis_assessment',
  getMyelomaSpecificData: 'myeloma_specific_data',
  getMyositisAssessment: 'myositis_assessment',
  getNarcolepsyAssessment: 'narcolepsy_assessment',
  getNephrologyConsultationDetails: 'nephrology_consultation_details',
  getNephrologyConsultations: 'nephrology_consultations',
  getNeuroImaging: 'neuro_imaging',
  getNeurologicalAssessment: 'neurological_assessment',
  getNeurologicalExam: 'neurological_exam',
  getNeurologicalExamination: 'neurological_examination',
  getNeurologicalFindings: 'neurological_findings',
  getNeurologyConsultations: 'neurology_consultations',
  getNeurologyProgressNotes: 'neurology_progress_notes',
  getNeuromuscularDisorder: 'neuromuscular_disorder',
  getNeuropsychTesting: 'neuropsych_testing',
  getNeuropsychologicalAssessments: 'neuropsychological_assessments',
  getNeurosurgeryAssessment: 'neurosurgery_assessment',
  getNeurosurgeryConsultations: 'neurosurgery_consultations',
  getNeurovascularExam: 'neurovascular_exam',
  getNewbornScreeningResults: 'newborn_screening_results',
  getNicuProgressNotes: 'nicu_progress_notes',
  getNonMotorSymptoms: 'non_motor_symptoms',
  getNtScanResult: 'nt_scan_result',
  getNuclearMedicineAssessment: 'nuclear_medicine_assessment',
  getNuclearMedicineStudies: 'nuclear_medicine_studies',
  getNurseSignatures: 'nurse_signatures',
  getNursingAssessments: 'nursing_assessments',
  getNursingNotes: 'nursing_notes',
  getNutritionalAssessment: 'nutritional_assessment',
  getNutritionalStatus: 'nutritional_status',
  getNutritionalSupplementation: 'nutritional_supplementation',
  getNutritionalSupport: 'nutritional_support',
  getObstetricHistory: 'obstetric_history',
  getObstetricUltrasoundReports: 'obstetric_ultrasound_reports',
  getOccupationalExposureRecords: 'occupational_exposure_records',
  getOccupationalHealthAssessment: 'occupational_health_assessment',
  getOccupationalMedicineEvaluations: 'occupational_medicine_evaluations',
  getOccupationalTherapyReports: 'occupational_therapy_reports',
  getOmissionsRefusals: 'omissions_refusals',
  getOncologicEmergencies: 'oncologic_emergencies',
  getOncologyConsultations: 'oncology_consultations',
  getOncologyFollowupReports: 'oncology_followup_reports',
  getOncologyTeam: 'oncology_team',
  getOncologyTreatmentPlans: 'oncology_treatment_plans',
  getOperativeDetails: 'operative_details',
  getOperativeReportDetails: 'operative_report_details',
  getOperativeReports: 'operative_reports',
  getOperativeTechnique: 'operative_technique',
  getOperativeTime: 'operative_time',
  getOphthalmologyExam: 'ophthalmology_exam',
  getOphthalmologyExaminations: 'ophthalmology_examinations',
  getOpioidRiskAssessment: 'opioid_risk_assessment',
  getOpportunisticInfections: 'opportunistic_infections',
  getOptimizationStats: 'optimization_stats',
  getOralSurgeryReports: 'oral_surgery_reports',
  getOrthodonticTreatmentPlans: 'orthodontic_treatment_plans',
  getOrthopedicAssessment: 'orthopedic_assessment',
  getOrthopedicConsultations: 'orthopedic_consultations',
  getOrthopedicFollowupNotes: 'orthopedic_followup_notes',
  getOrthopedicImaging: 'orthopedic_imaging',
  getOrthopedicOperativeReports: 'orthopedic_operative_reports',
  getOrthopedicProcedures: 'orthopedic_procedures',
  getOutcomesPrediction: 'outcomes_prediction',
  getOvertrainingAssessment: 'overtraining_assessment',
  getPainAssessmentForms: 'pain_assessment_forms',
  getPainFunctionalAssessment: 'pain_functional_assessment',
  getPainManagement: 'pain_management',
  getPainManagementNotes: 'pain_management_notes',
  getPainManagementPlan: 'pain_management_plan',
  getPainMedicationAgreements: 'pain_medication_agreements',
  getPalliativeCare: 'palliative_care',
  getPalliativeCareNeeds: 'palliative_care_needs',
  getParentalConcerns: 'parental_concerns',
  getParkinsonMedications: 'parkinson_medications',
  getParkinsonianFeatures: 'parkinsonian_features',
  getPartnerInvolvement: 'partner_involvement',
  getPartnerInvolvementDiabetesManagement: 'partner_involvement_diabetes_management',
  getPastOcularHistory: 'past_ocular_history',
  getPathologyGrossDescription: 'pathology_gross_description',
  getPathologyReports: 'pathology_reports',
  getPatientCareGoals: 'patient_care_goals',
  getPatientEducationContext: 'patient_education_context',
  getPatientEducationRecords: 'patient_education_records',
  getPatientEmotionalResponse: 'patient_emotional_response',
  getPatientInstructions: 'patient_instructions',
  getPatientPositioning: 'patient_positioning',
  getPatientProvider: 'patient_provider',
  getPatientSpecificCarePlan: 'patient_specific_care_plan',
  getPatientVisits: 'patient_visits',
  createPatientVisit: 'patient_visits',
  updatePatientVisit: 'patient_visits',
  deletePatientVisit: 'patient_visits',
  getPediatricGrowthCharts: 'pediatric_growth_charts',
  getPediatricScreening: 'pediatric_screening',
  getPediatricVaccinationRecords: 'pediatric_vaccination_records',
  getPediatricVisits: 'pediatric_visits',
  getPerformanceAssessment: 'performance_assessment',
  getPerformanceStatus: 'performance_status',
  getPerinatalMentalHealthReferral: 'perinatal_mental_health_referral',
  getPeriodontalCharts: 'periodontal_charts',
  getPeripheralNeuropathy: 'peripheral_neuropathy',
  getPetScanReports: 'pet_scan_reports',
  getPharmacyReview: 'pharmacy_review',
  getPhysicalExaminations: 'physical_examinations',
  getPhysicalTherapyEvaluations: 'physical_therapy_evaluations',
  getPhysicalTherapyNotes: 'physical_therapy_notes',
  getPlasticSurgeryAssessment: 'plastic_surgery_assessment',
  getPlasticSurgeryConsultations: 'plastic_surgery_consultations',
  getPmrAssessment: 'pmr_assessment',
  getPneumoperitoneum: 'pneumoperitoneum',
  getPodiatryExaminations: 'podiatry_examinations',
  getPointOfCareUltrasoundHeartRate: 'point_of_care_ultrasound_heart_rate',
  getPoisonControlReports: 'poison_control_reports',
  getPolycysticKidneyDisease: 'polycystic_kidney_disease',
  getPolypharmacy: 'polypharmacy',
  getPolypharmacyReviews: 'polypharmacy_reviews',
  getPortPlacement: 'port_placement',
  getPostDialysisAssessment: 'post_dialysis_assessment',
  getPostOpTesting: 'post_op_testing',
  getPostOperativeReports: 'post_operative_reports',
  getPostopTesting: 'postop_testing',
  getPostoperativeCondition: 'postoperative_condition',
  getPostoperativeOrders: 'postoperative_orders',
  getPostoperativePainManagement: 'postoperative_pain_management',
  getPostpartumDiabetesRisk: 'postpartum_diabetes_risk',
  getPostpartumGlucoseMonitoring: 'postpartum_glucose_monitoring',
  getPostpartumNotes: 'postpartum_notes',
  getPostpartumPlanning: 'postpartum_planning',
  getPotentialTestingOutcomes: 'potential_testing_outcomes',
  getPreChemotherapyWorkup: 'pre_chemotherapy_workup',
  getPreDialysisAssessment: 'pre_dialysis_assessment',
  getPreEmploymentPhysical: 'pre_employment_physical',
  getPreOperativeAssessments: 'pre_operative_assessments',
  getPreOperativePreparation: 'pre_operative_preparation',
  getPrePregnancyWeight: 'pre_pregnancy_weight',
  getPreconceptionCounseling: 'preconception_counseling',
  getPreeclampsiaMonitoring: 'preeclampsia_monitoring',
  getPregnancyComplications: 'pregnancy_complications',
  getPregnancyCourse: 'pregnancy_course',
  getPregnancyRiskAssessment: 'pregnancy_risk_assessment',
  getPregnancySymptoms: 'pregnancy_symptoms',
  getPrenatalEducation: 'prenatal_education',
  getPrenatalScreening: 'prenatal_screening',
  getPrenatalTestingReports: 'prenatal_testing_reports',
  getPrenatalVisits: 'prenatal_visits',
  getPreoperativeEvaluation: 'preoperative_evaluation',
  getPreoperativePreparation: 'preoperative_preparation',
  getPrepAndDrape: 'prep_and_drape',
  getPrescriptions: 'prescriptions',
  getPressureInjury: 'pressure_injury',
  getPressureUlcerRisk: 'pressure_ulcer_risk',
  getPreventiveBiomarkers: 'preventive_biomarkers',
  getPreventiveCare: 'preventive_care',
  getPreventiveMedicineAssessments: 'preventive_medicine_assessments',
  getPrimaryProphylaxis: 'primary_prophylaxis',
  getPriorAuthorizationForms: 'prior_authorization_forms',
  getPriorAuthorizationStatus: 'prior_authorization_status',
  getPrnMedications: 'prn_medications',
  getProceduralSedation: 'procedural_sedation',
  getProcedureRequests: 'procedure_requests',
  getProceduresInterventions: 'procedures_interventions',
  getPrognosis: 'prognosis',
  getPrognosisDiscussion: 'prognosis_discussion',
  getPrognosisRecords: 'prognosis_records',
  getPrognosticFactors: 'prognostic_factors',
  getProgressNotes: 'progress_notes',
  getProphylacticMedications: 'prophylactic_medications',
  getProposedArtSwitch: 'proposed_art_switch',
  getProteinuriaAssessment: 'proteinuria_assessment',
  getProviderInfo: 'provider_info',
  getPscManagement: 'psc_management',
  getPsychiatricAssessmentScales: 'psychiatric_assessment_scales',
  getPsychiatricDischargeSummaries: 'psychiatric_discharge_summaries',
  getPsychiatricEvaluations: 'psychiatric_evaluations',
  getPsychiatricHistory: 'psychiatric_history',
  getPsychiatricProgressNotes: 'psychiatric_progress_notes',
  getPsychiatricReview: 'psychiatric_review',
  getPsychiatricTreatmentPlan: 'psychiatric_treatment_plan',
  getPsychosocialAssessments: 'psychosocial_assessments',
  getPsychosocialFactors: 'psychosocial_factors',
  getPsychosocialOncology: 'psychosocial_oncology',
  getPsychosocialSupportServices: 'psychosocial_support_services',
  getPsychotropicMedications: 'psychotropic_medications',
  getPulmonaryFunctionTests: 'pulmonary_function_tests',
  getPulmonaryImaging: 'pulmonary_imaging',
  getPulmonaryRehabilitation: 'pulmonary_rehabilitation',
  getPulmonaryRehabilitationNotes: 'pulmonary_rehabilitation_notes',
  getPulmonologyConsultations: 'pulmonology_consultations',
  getPumpAdvancedSettings: 'pump_advanced_settings',
  getPumpDownloadAnalysis: 'pump_download_analysis',
  getQualityAssurance: 'quality_assurance',
  getQualityMetrics: 'quality_metrics',
  getRadiationOncology: 'radiation_oncology',
  getRadiationTherapy: 'radiation_therapy',
  getRadiationTherapyRecords: 'radiation_therapy_records',
  getRadiologyFindings: 'radiology_findings',
  getRadiologyReports: 'radiology_reports',
  getRapidResponseSummaries: 'rapid_response_summaries',
  getReadmissionRiskAssessment: 'readmission_risk_assessment',
  getReasonForReferral: 'reason_for_referral',
  getReferrals: 'referrals',
  getReferralsPlaced: 'referrals_placed',
  getRegionalAnesthesiaRecords: 'regional_anesthesia_records',
  getRehabilitationGoals: 'rehabilitation_goals',
  getRehabilitationProgressNotes: 'rehabilitation_progress_notes',
  getRehabilitationProtocol: 'rehabilitation_protocol',
  getRenalAnemia: 'renal_anemia',
  getRenalNutrition: 'renal_nutrition',
  getRenalProtectionPlan: 'renal_protection_plan',
  getReproductiveHistory: 'reproductive_history',
  getRescueTherapyOptions: 'rescue_therapy_options',
  getResearchConsentForms: 'research_consent_forms',
  getRespiratoryDevices: 'respiratory_devices',
  getRespiratoryInfections: 'respiratory_infections',
  getRespiratoryMedications: 'respiratory_medications',
  getRespiteCare: 'respite_care',
  getResponseAssessment: 'response_assessment',
  getResuscitationRecords: 'resuscitation_records',
  getRetinalExaminations: 'retinal_examinations',
  getReturnToPlayProtocol: 'return_to_play_protocol',
  getReturnToSport: 'return_to_sport',
  getReturnToWorkPlan: 'return_to_work_plan',
  getReviewOfSystems: 'review_of_systems',
  getRheumatoidArthritisAssessment: 'rheumatoid_arthritis_assessment',
  getRheumatologicAssessment: 'rheumatologic_assessment',
  getRheumatologicMonitoring: 'rheumatologic_monitoring',
  getRheumatologicTreatment: 'rheumatologic_treatment',
  getRheumatologyConsultations: 'rheumatology_consultations',
  getRiskCalculators: 'risk_calculators',
  getRiskCounseling: 'risk_counseling',
  getRiskFactors: 'risk_factors',
  getSafetyPlanning: 'safety_planning',
  getScheduledMedications: 'scheduled_medications',
  getSchoolHealthForms: 'school_health_forms',
  getSchoolPerformance: 'school_performance',
  getSclerodermaAssessment: 'scleroderma_assessment',
  getScreeningCompliance: 'screening_compliance',
  getSecondOpinionReports: 'second_opinion_reports',
  getSecondaryProphylaxis: 'secondary_prophylaxis',
  getSedationRecords: 'sedation_records',
  getSepsisManagement: 'sepsis_management',
  getShiftHandoffNotes: 'shift_handoff_notes',
  getSingleEmbryoTransfer: 'single_embryo_transfer',
  getSingleEmbryoTransferDetails: 'single_embryo_transfer_details',
  getSjogrensSyndromeAssessment: 'sjogrens_syndrome_assessment',
  getSkinBiopsyReports: 'skin_biopsy_reports',
  getSleepApneaManagement: 'sleep_apnea_management',
  getSleepDisorderAssessment: 'sleep_disorder_assessment',
  getSleepDisturbances: 'sleep_disturbances',
  getSleepHygieneEducation: 'sleep_hygiene_education',
  getSleepStudyReports: 'sleep_study_reports',
  getSmokingCessationProgram: 'smoking_cessation_program',
  getSoapNotes: 'soap_notes',
  getSocialDeterminantsOfHealth: 'social_determinants_of_health',
  getSocialFunctionalAssessment: 'social_functional_assessment',
  getSocialHistory: 'social_history',
  getSocialSupport: 'social_support',
  getSocialWork: 'social_work',
  getSocialWorkNotes: 'social_work_notes',
  getSource: 'source',
  getSouthAsianNutritionist: 'south_asian_nutritionist',
  getSpecialtyFields: 'specialty_fields',
  getSpecificIgeTests: 'specific_ige_tests',
  getSpecimens: 'specimens',
  getSpeechTherapyAssessments: 'speech_therapy_assessments',
  getSpondyloarthritisAssessment: 'spondyloarthritis_assessment',
  getSpongeInstrumentCounts: 'sponge_instrument_counts',
  getSportsMedicineEvaluations: 'sports_medicine_evaluations',
  getSportsNutritionPlan: 'sports_nutrition_plan',
  getSportsPhysicalExamination: 'sports_physical_examination',
  getStagingSummary: 'staging_summary',
  getStressManagementReferrals: 'stress_management_referrals',
  getStressTestReports: 'stress_test_reports',
  getStrokeAssessment: 'stroke_assessment',
  getSubstanceUseAssessment: 'substance_use_assessment',
  getSuicideRiskAssessment: 'suicide_risk_assessment',
  getSupplementationPlans: 'supplementation_plans',
  getSupportGroupReferral: 'support_group_referral',
  getSupportiveCare: 'supportive_care',
  getSurgicalApproach: 'surgical_approach',
  getSurgicalConsentForms: 'surgical_consent_forms',
  getSurgicalHistory: 'surgical_history',
  getSurgicalOncology: 'surgical_oncology',
  getSurgicalSteps: 'surgical_steps',
  getSurgicalTeam: 'surgical_team',
  getSurvivorshipCarePlan: 'survivorship_care_plan',
  getSymptomProgression: 'symptom_progression',
  getSymptomProgressionTimeline: 'symptom_progression_timeline',
  getTelemedicineEncounters: 'telemedicine_encounters',
  getTherapyProgressNotes: 'therapy_progress_notes',
  getTherapyRequests: 'therapy_requests',
  getTherapySessionNotes: 'therapy_session_notes',
  getThoracicSurgeryAssessment: 'thoracic_surgery_assessment',
  getThyroidEvaluations: 'thyroid_evaluations',
  getThyroidManagement: 'thyroid_management',
  getTotalWeightGain: 'total_weight_gain',
  getTourniquetData: 'tourniquet_data',
  getToxicityAssessment: 'toxicity_assessment',
  getToxicologyReports: 'toxicology_reports',
  getTractographyStudies: 'tractography_studies',
  getTransferSummaries: 'transfer_summaries',
  getTransplantAssessment: 'transplant_assessment',
  getTransplantEvaluations: 'transplant_evaluations',
  getTraumaAssessment: 'trauma_assessment',
  getTraumaFlowSheets: 'trauma_flow_sheets',
  getTraumaScoring: 'trauma_scoring',
  getTravelHealthCertificates: 'travel_health_certificates',
  getTravelMedicineAssessment: 'travel_medicine_assessment',
  getTravelVaccinationRecords: 'travel_vaccination_records',
  getTreatmentCourses: 'treatment_courses',
  getTreatmentGoals: 'treatment_goals',
  getTreatmentPlans: 'treatment_plans',
  getTreatmentSummary: 'treatment_summary',
  getTrendAnalysis: 'trend_analysis',
  getTrendingAnalysis: 'trending_analysis',
  getTriageData: 'triage_data',
  getTropicalDiseaseAssessment: 'tropical_disease_assessment',
  getTumorBoardNotes: 'tumor_board_notes',
  getTumorMarkerPanels: 'tumor_marker_panels',
  getTumorMarkers: 'tumor_markers',
  getUltrasoundObReports: 'ultrasound_ob_reports',
  getUmbilicalArteryDoppler: 'umbilical_artery_doppler',
  getUrodynamicStudies: 'urodynamic_studies',
  getUrologyAssessment: 'urology_assessment',
  getUrologyConsultations: 'urology_consultations',
  getVaccinationRecords: 'vaccination_records',
  getVariantInterpretationGuidelines: 'variant_interpretation_guidelines',
  getVasculitisAssessment: 'vasculitis_assessment',
  getVenousThromboembolismRisk: 'venous_thromboembolism_risk',
  getVentilatorSettings: 'ventilator_settings',
  getVisualAcuityReports: 'visual_acuity_reports',
  getVitalSigns: 'vital_signs',
  getVitalSignsLogs: 'vital_signs_logs',
  getVitalSignsMonitoring: 'vital_signs_monitoring',
  getVitalSignsTable: 'vital_signs_table',
  getWeeklyVirtualCheckIns: 'weekly_virtual_check_ins',
  getWeightMeasurements: 'weight_measurements',
  getWeightMonitoring: 'weight_monitoring',
  getWellChildExaminations: 'well_child_examinations',
  getWellChildSummary: 'well_child_summary',
  getWellnessVisitDocumentation: 'wellness_visit_documentation',
  getWorkAccommodations: 'work_accommodations',
  getWorkRestrictions: 'work_restrictions',
  getWorkersCompEvaluations: 'workers_comp_evaluations',
  getWorkersCompensationEvaluation: 'workers_compensation_evaluation',
  getWorkplaceAccommodations: 'workplace_accommodations',
  getWorkplaceInjuryReport: 'workplace_injury_report',
  getWoundCareAssessments: 'wound_care_assessments',
  getWoundCareDocumentation: 'wound_care_documentation',
  getWoundCareNotes: 'wound_care_notes',
};

// WRAP_ALL_RECORDS_COLLECTIONS - All collections in functionCollectionMap use document view
// This Set is derived from functionCollectionMap values for consistency
const WRAP_ALL_RECORDS_COLLECTIONS = new Set(Object.values(functionCollectionMap));

// Helper function to wrap records into a single document (imported logic from second-pass)
async function wrapRecordsIntoSingleDocument(records, collectionName, patientId, context) {
  // Create a wrapper document that contains all records
  const collectionLabel = collectionName.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  return {
    _id: `wrapped_${collectionName}_${patientId}`,
    _documentTitle: `${collectionLabel} Summary`,
    _collectionName: collectionName,
    _recordCount: records.length,
    _records: records,
    // Flatten first record's fields to top level for template compatibility
    ...(records.length === 1 ? records[0] : {}),
    // For multiple records, provide as array
    records: records
  };
}

// Build optimized functions with collection pre-checking
const optimizedFunctions = {};
for (const [funcName, originalFuncDef] of Object.entries(generatedMedicalFunctions)) {
  // originalFuncDef is an object: { description, parameters, handler }
  // We need to call originalFuncDef.handler, not originalFuncDef directly
  const originalHandler = typeof originalFuncDef === 'function' ? originalFuncDef : originalFuncDef?.handler;

  if (funcName.startsWith('get')) {
    // Wrap getter functions with optimization AND artifactPanel wrapping
    const collectionName = functionCollectionMap[funcName];
    if (collectionName && originalHandler) {
      // Create wrapper that preserves (args, context) signature AND adds artifactPanel
      optimizedFunctions[funcName] = {
        description: originalFuncDef.description,
        parameters: originalFuncDef.parameters,
        handler: async function(args, context) {
          // Skip if patient.medicalData indicates no data in this collection
          const patient = context.patient;
          if (patient?.medicalData && !patient.medicalData[collectionName]) {
            // No data in this collection for this patient - return empty with artifactPanel
            return {
              success: true,
              data: [],
              count: 0,
              message: `No ${collectionName.replace(/_/g, ' ')} found for this patient`,
              displayType: 'openArtifactPanel',
              artifactPanel: {
                patientId: args.patientId,
                category: collectionName,
                type: 'documents',
                data: []
              }
            };
          }

          // Has data or uncertain - call the original handler
          const result = await originalHandler(args, context);

          // If result is already wrapped with artifactPanel, return as-is
          if (result && result.displayType === 'openArtifactPanel') {
            return result;
          }

          // Wrap the result with artifactPanel structure
          const dataArray = Array.isArray(result) ? result : (result?.data || result?.records || [result]);

          // Check if this collection should wrap all records into single document
          if (WRAP_ALL_RECORDS_COLLECTIONS.has(collectionName)) {
            console.log(`📦 [${funcName}] Wrapping ${dataArray.length} ${collectionName} records into single document`);
            const wrappedDocument = await wrapRecordsIntoSingleDocument(dataArray, collectionName, args.patientId, context);

            return {
              success: true,
              data: [wrappedDocument],
              displayType: 'openArtifactPanel',
              artifactPanel: {
                patientId: args.patientId,
                category: collectionName,
                type: 'documents',
                data: [wrappedDocument]
              }
            };
          } else {
            // Return raw array with artifactPanel
            return {
              success: true,
              data: dataArray,
              displayType: 'openArtifactPanel',
              artifactPanel: {
                patientId: args.patientId,
                category: collectionName,
                type: 'grid',
                data: dataArray
              }
            };
          }
        }
      };
    } else if (originalHandler) {
      // No collection mapping - keep original function definition structure
      optimizedFunctions[funcName] = originalFuncDef;
    } else {
      // Keep the whole definition (may be needed for description/parameters)
      optimizedFunctions[funcName] = originalFuncDef;
    }
  } else {
    // Keep non-get functions as-is (they have {description, parameters, handler} structure)
    optimizedFunctions[funcName] = originalFuncDef;
  }
}

// Second pass: Create functions for collections in functionCollectionMap that don't exist in generatedMedicalFunctions
// Note: Only logs on module initialization, not on every request
const newFunctionsCreated = [];
for (const [funcName, collectionName] of Object.entries(functionCollectionMap)) {
  if (funcName.startsWith('get') && !optimizedFunctions[funcName]) {
    // This function exists in functionCollectionMap but not in generatedMedicalFunctions
    // Create it with a default description
    newFunctionsCreated.push(funcName);

    optimizedFunctions[funcName] = {
      description: `Retrieve ${collectionName.replace(/_/g, ' ')} records for a patient. Returns data with artifact panel for document viewing.`,
      parameters: {
        patientId: { type: "string", required: true, description: "Patient ID" },
        dateFrom: { type: "string", description: "Start date (YYYY-MM-DD)" },
        dateTo: { type: "string", description: "End date (YYYY-MM-DD)" },
        limit: { type: "number", description: "Maximum number of records" },
        sortBy: { type: "string", enum: ["date", "provider", "urgency"], description: "Sort field" },
        sortOrder: { type: "string", enum: ["asc", "desc"], description: "Sort order" }
      },
      handler: async (args, context) => {
        const secureContext = {
          serviceId: 'agent-service-v4',
          operation: funcName,
          practiceId: context.practiceId
        };

        // Cache optimization removed Feb 2026 - always query DB directly
        // (SKIP_OPTIMIZATION_CHECK array removed)

        // Always query DB directly - no cache optimization
        console.log(`📊 Querying ${collectionName} directly (no cache)`);

          // Execute the query
          const { ObjectId } = require('mongodb');
          const SecureDataAccess = require('./secureDataAccess');

          console.log(`🔍 [${funcName}] Received patientId: ${args.patientId} (type: ${typeof args.patientId})`);

          let patientId = args.patientId;
          if (typeof patientId === 'string' && patientId.match(/^[0-9a-fA-F]{24}$/)) {
            patientId = new ObjectId(patientId);
            console.log(`✅ [${funcName}] Converted to ObjectId: new ObjectId('${args.patientId}')`);
          }

          const filter = { patientId };
          if (args.dateFrom || args.dateTo) {
            filter.date = {};
            if (args.dateFrom) filter.date.$gte = new Date(args.dateFrom);
            if (args.dateTo) filter.date.$lte = new Date(args.dateTo);
          }

          console.log(`🔎 [${funcName}] Querying '${collectionName}' with filter:`, JSON.stringify(filter));

          const options = {};
          if (args.limit) options.limit = args.limit;
          if (args.sortBy) {
            options.sort = { [args.sortBy]: args.sortOrder === 'desc' ? -1 : 1 };
          }

          const dataArray = await SecureDataAccess.query(collectionName, filter, options, secureContext);

          console.log(`📊 [${funcName}] Query returned ${dataArray.length} records`);

          // If no records found, return empty result without opening artifact panel
          if (!dataArray || dataArray.length === 0) {
            console.log(`📭 [${funcName}] No records found - returning empty result without artifact panel`);
            return {
              success: true,
              data: [],
              count: 0,
              message: `No ${collectionName.replace(/_/g, ' ')} found for this patient`
            };
          }

          // Check if this collection should wrap all records
          console.log(`🔍 [${funcName}] DEBUG: collectionName='${collectionName}', WRAP_ALL_RECORDS_COLLECTIONS.has('${collectionName}')=${WRAP_ALL_RECORDS_COLLECTIONS.has(collectionName)}`);
          if (WRAP_ALL_RECORDS_COLLECTIONS.has(collectionName)) {
            console.log(`🔒 SECURITY: Policy conversion active for optimized-medical-functions`);
            const wrappedDocument = await wrapRecordsIntoSingleDocument(dataArray, collectionName, args.patientId, context);
            console.log(`📦 [${funcName}] Wrapped ${dataArray.length} ${collectionName} records into single document`);

            const result = {
              success: true,
              data: [wrappedDocument],
              displayType: 'openArtifactPanel',
              artifactPanel: {
                patientId: args.patientId,
                category: collectionName,
                type: 'documents',
                data: [wrappedDocument]
              }
            };

            console.log(`🔍 [${funcName}] RESPONSE STRUCTURE:`, {
              displayType: result.displayType,
              hasArtifactPanel: !!result.artifactPanel,
              artifactPanelType: result.artifactPanel?.type,
              dataCount: result.data?.length
            });

            return result;
          } else {
            // Raw array result, wrap it
            return {
              success: true,
              data: dataArray,
              displayType: 'openArtifactPanel',
              artifactPanel: {
                patientId: args.patientId,
                category: collectionName,
                type: 'grid',
                data: dataArray
              }
            };
          }
      }
    };
  }
}

// Log summary of auto-created functions (only once on module load)
if (newFunctionsCreated.length > 0 && process.env.QUIET_LOGS !== 'true') {
  console.log(`📝 Auto-created ${newFunctionsCreated.length} optimized functions for new collections:`, newFunctionsCreated.join(', '));
}

// Add utility function for bulk optimization checks
optimizedFunctions.getOptimizationStats = {
  description: "Get optimization statistics for a patient",
  parameters: {
    patientId: { type: "string", required: true }
  },
  handler: async (args, context) => {
    const secureContext = {
      serviceId: 'agent-service-v4',
      operation: 'getOptimizationStats',
      practiceId: context.practiceId
    };

    const collectionsWithData = await medicalDataService.getCollectionsWithData(
      args.patientId,
      secureContext
    );

    const totalCollections = Object.keys(functionCollectionMap).length;
    const percentage = collectionsWithData.length > 0
      ? Math.round((collectionsWithData.length / totalCollections) * 100)
      : 0;

    return {
      collectionsWithData: collectionsWithData.length,
      totalCollections,
      percentageWithData: percentage,
      estimatedSpeedImprovement: `${100 - percentage}%`,
      collections: collectionsWithData
    };
  }
};

module.exports = optimizedFunctions;