/**
 * Route Loader Service
 * Centralized route loading for Express application
 */

class RouteLoaderService {
    constructor() {
        this.routes = [];
        this.loadedRoutes = [];
        this.failedRoutes = [];
        this.app = null;
    }

    /**
     * Initialize the service with Express app
     */
    initialize(app) {
        if (!app) {
            throw new Error('Express app instance required for RouteLoaderService');
        }
        this.app = app;
        console.log('✅ RouteLoaderService initialized');
        return this;
    }

    /**
     * Define all routes to be loaded
     * CLEAN ARCHITECTURE: Only load routes actually used by frontend
     */
    defineRoutes() {
        this.routes = [
            // ===== AUTHENTICATION ROUTES (REQUIRED) =====
            { path: '/api/auth', file: './routes/auth' },
            { path: '/api/practice-auth', file: './routes/practiceAuth' },
            { path: '/api/passwordless-auth', file: './routes/passwordlessAuth' },
            { path: '/api/auth-ai', file: './routes/authAI' },
            { path: '/api/mfa', file: './routes/mfa' },

            // ===== PRACTICE MANAGEMENT (REQUIRED) =====
            { path: '/api/practices', file: './routes/practices' },
            { path: '/api/practice', file: './routes/practice' },

            // ===== USER SETTINGS (REQUIRED) =====
            { path: '/api/user', file: './routes/userSettings' },

            // ===== AI AGENT - PRIMARY MEDICAL INTERFACE (REQUIRED) =====
            // All medical operations go through Claude functions via this endpoint
            { path: '/api/agent', file: './routes/agent' },

            // ===== BATCH DOCUMENT PROCESSING (REQUIRED) =====
            { path: '/api/batch-documents', file: './routes/batchDocuments' },
            { path: '/api/batch', file: './routes/batchProcessor' },

            // ===== ADDRESS AUTOCOMPLETE (REMOVED - NOT USED) =====
            // Components exist but are not mounted in App.jsx routes
            // { path: '/api/streets', file: './routes/streets' },
            // { path: '/api/postal-codes', file: './routes/postalCodes' },
            // { path: '/api/addresses', file: './routes/addresses' },

            // ===== COMMUNICATION (REQUIRED) =====
            { path: '/api/communication', file: './routes/communication' },
            { path: '/api/sms', file: './routes/sms' },

            // ===== TRANSLATIONS (REQUIRED) =====
            { path: '/api/translations', file: './routes/translations' },

            // ===== SECURITY & MONITORING (REQUIRED) =====
            { path: '/api/security', file: './routes/security' },
            { path: '/api/security-monitoring', file: './routes/securityMonitoring' },

            // ===== CHAT SESSIONS (LEFT SIDEBAR - REQUIRED) =====
            { path: '/api/chat', file: './routes/chat' },

            // ===== SIDEBAR FEATURES (RIGHT SIDEBAR - REQUIRED) =====
            { path: '/api/notifications', file: './routes/notifications' },
            { path: '/api/appointments', file: './routes/appointments' },
            { path: '/api/staff-chat', file: './routes/staffChat' },

            // ===== MEDICAL IMAGE ANALYSIS =====
            { path: '/api/medical-images', file: './routes/medicalImages' },

            // ===== VISIT RECORDING =====
            { path: '/api/visits', file: './routes/visitRecording' },

            // ===== TEXT-TO-SPEECH (Voice Mode) =====
            { path: '/api/tts', file: './routes/textToSpeech' },

            // ===== AUTOCOMPLETE =====
            { path: '/api/autocomplete', file: './routes/autocomplete' },

            // ===== PATIENT SEARCH =====
            { path: '/api/patients', file: './routes/patientSearch' },

            // ===== BLUE BUTTON / MEDICARE IMPORT =====
            { path: '/api/patient-import/medicare', file: './routes/patientMedicareImport' },

            // ===== EXTERNAL APIs (FDA, Drug Information, etc.) =====
            { path: '/api/external', file: './routes/external' },

            // ===== COMPLIANCE (SECURITY API - OPTIONAL) =====
            // TEMPORARILY DISABLED: Missing complianceAnalyticsService dependency
            // TODO: Create complianceAnalyticsService or refactor to use complianceReportingService
            // { path: '/api/compliance', file: './routes/compliance' },

            // ===== TEMPLATE EDITING (Per-Collection Isolation) =====
            { path: '/api/edit/medications', file: './routes/edit/medications' },
            { path: '/api/edit/abnormal_results', file: './routes/edit/abnormal_results' },
            { path: '/api/edit/allergies', file: './routes/edit/allergies' },
            { path: '/api/edit/diagnoses', file: './routes/edit/diagnoses' },
            { path: '/api/edit/lab_results', file: './routes/edit/lab_results' },
            { path: '/api/edit/medical_procedures', file: './routes/edit/medical_procedures' },
            { path: '/api/edit/imaging_reports', file: './routes/edit/imaging_reports' },
            { path: '/api/edit/hospital_course', file: './routes/edit/hospital_course' },
            { path: '/api/edit/follow_up_appointments', file: './routes/edit/follow_up_appointments' },
            { path: '/api/edit/treatment_courses', file: './routes/edit/treatment_courses' },
            { path: '/api/edit/echo_reports', file: './routes/edit/echo_reports' },
            { path: '/api/edit/patient_education_records', file: './routes/edit/patient_education_records' },
            { path: '/api/edit/social_history', file: './routes/edit/social_history' },
            { path: '/api/edit/history_present_illness', file: './routes/edit/history_present_illness' },
            { path: '/api/edit/cardiology_assessment', file: './routes/edit/cardiology_assessment' },
            { path: '/api/edit/pulmonary_imaging', file: './routes/edit/pulmonary_imaging' },
            { path: '/api/edit/respiratory_medications', file: './routes/edit/respiratory_medications' },
            { path: '/api/edit/respiratory_therapy_assessment', file: './routes/edit/respiratory_therapy_assessment' },
            { path: '/api/edit/discharge_summaries', file: './routes/edit/discharge_summaries' },
            { path: '/api/edit/administrative_data', file: './routes/edit/administrative_data' },
            { path: '/api/edit/emergency_information', file: './routes/edit/emergency_information' },
            { path: '/api/edit/patient_provider', file: './routes/edit/patient_provider' },
            { path: '/api/edit/medication_recommendations', file: './routes/edit/medication_recommendations' },
            { path: '/api/edit/referrals', file: './routes/edit/referrals' },
            { path: '/api/edit/addiction_medicine_consultations', file: './routes/edit/addiction_medicine_consultations' },
            { path: '/api/edit/case_management', file: './routes/edit/case_management' },
            { path: '/api/edit/hepatitis_c_history', file: './routes/edit/hepatitis_c_history' },
            { path: '/api/edit/ecg_reports', file: './routes/edit/ecg_reports' },
            { path: '/api/edit/therapy_session_notes', file: './routes/edit/therapy_session_notes' },
            { path: '/api/edit/liver_function_assessments', file: './routes/edit/liver_function_assessments' },
            { path: '/api/edit/depression_screening', file: './routes/edit/depression_screening' },
            { path: '/api/edit/therapy_progress_notes', file: './routes/edit/therapy_progress_notes' },
            { path: '/api/edit/insurance_authorizations', file: './routes/edit/insurance_authorizations' },
            { path: '/api/edit/stress_management_referrals', file: './routes/edit/stress_management_referrals' },
            { path: '/api/edit/past_medical_history', file: './routes/edit/past_medical_history' },
            { path: '/api/edit/family_history', file: './routes/edit/family_history' },
            { path: '/api/edit/chief_complaints', file: './routes/edit/chief_complaints' },
            { path: '/api/edit/review_of_systems', file: './routes/edit/review_of_systems' },
            { path: '/api/edit/physical_examinations', file: './routes/edit/physical_examinations' },
            { path: '/api/edit/assessment_plans', file: './routes/edit/assessment_plans' },
            { path: '/api/edit/consultation_details', file: './routes/edit/consultation_details' },
            { path: '/api/edit/prognosis', file: './routes/edit/prognosis' },
            { path: '/api/edit/mental_status_exams', file: './routes/edit/mental_status_exams' },
            { path: '/api/edit/pain_management', file: './routes/edit/pain_management' },
            { path: '/api/edit/psychiatric_assessment_scales', file: './routes/edit/psychiatric_assessment_scales' },
            { path: '/api/edit/substance_use_assessment', file: './routes/edit/substance_use_assessment' },
            { path: '/api/edit/monitoring_plans', file: './routes/edit/monitoring_plans' },
            { path: '/api/edit/cancer_surveillance', file: './routes/edit/cancer_surveillance' },
            { path: '/api/edit/follow_up_plan', file: './routes/edit/follow_up_plan' },
            { path: '/api/edit/social_determinants_of_health', file: './routes/edit/social_determinants_of_health' },
            { path: '/api/edit/treatment_plans', file: './routes/edit/treatment_plans' },
            { path: '/api/edit/therapy_requests', file: './routes/edit/therapy_requests' },
            { path: '/api/edit/endoscopy_reports', file: './routes/edit/endoscopy_reports' },
            { path: '/api/edit/cmv_monitoring_plan', file: './routes/edit/cmv_monitoring_plan' },
            { path: '/api/edit/coagulation_studies', file: './routes/edit/coagulation_studies' },
            { path: '/api/edit/code_blue_summaries', file: './routes/edit/code_blue_summaries' },
            { path: '/api/edit/cognitive_evaluations', file: './routes/edit/cognitive_evaluations' },
            { path: '/api/edit/cognitive_rehabilitation_reports', file: './routes/edit/cognitive_rehabilitation_reports' },
            { path: '/api/edit/cognitive_screening', file: './routes/edit/cognitive_screening' },
            { path: '/api/edit/colonoscopy_reports', file: './routes/edit/colonoscopy_reports' },
            { path: '/api/edit/colorectal_colonoscopies', file: './routes/edit/colorectal_colonoscopies' },
            { path: '/api/edit/colorectal_surgery_assessment', file: './routes/edit/colorectal_surgery_assessment' },
            { path: '/api/edit/colorectal_surgery_consultations', file: './routes/edit/colorectal_surgery_consultations' },
            { path: '/api/edit/complications', file: './routes/edit/complications' },
            { path: '/api/edit/component_allergen_testing', file: './routes/edit/component_allergen_testing' },
            { path: '/api/edit/comprehensive_cardiomyopathy_panel', file: './routes/edit/comprehensive_cardiomyopathy_panel' },
            { path: '/api/edit/comprehensive_medication_review', file: './routes/edit/comprehensive_medication_review' },
            { path: '/api/edit/compression_therapy', file: './routes/edit/compression_therapy' },
            { path: '/api/edit/concussion_assessment', file: './routes/edit/concussion_assessment' },
            { path: '/api/edit/connective_tissue_disease_assessment', file: './routes/edit/connective_tissue_disease_assessment' },
            { path: '/api/edit/consultation_notes', file: './routes/edit/consultation_notes' },
            { path: '/api/edit/consultation_requests', file: './routes/edit/consultation_requests' },
            { path: '/api/edit/consultation_timeline', file: './routes/edit/consultation_timeline' },
            { path: '/api/edit/contact_lens_fitting', file: './routes/edit/contact_lens_fitting' },
            { path: '/api/edit/continuous_infusions', file: './routes/edit/continuous_infusions' },
            { path: '/api/edit/contraction_monitoring', file: './routes/edit/contraction_monitoring' },
            { path: '/api/edit/critical_view_of_safety', file: './routes/edit/critical_view_of_safety' },
            { path: '/api/edit/cultural_considerations', file: './routes/edit/cultural_considerations' },
            { path: '/api/edit/current_dialysis', file: './routes/edit/current_dialysis' },
            { path: '/api/edit/current_pregnancy', file: './routes/edit/current_pregnancy' },
            { path: '/api/edit/copd_assessments', file: './routes/edit/copd_assessments' },
            { path: '/api/edit/cpap_bipap_management', file: './routes/edit/cpap_bipap_management' },
            { path: '/api/edit/cpap_management', file: './routes/edit/cpap_management' },
            { path: '/api/edit/cystoscopy_reports', file: './routes/edit/cystoscopy_reports' },
            { path: '/api/edit/cytology_reports', file: './routes/edit/cytology_reports' },
            { path: '/api/edit/cyp450_panel_results', file: './routes/edit/cyp450_panel_results' },
            { path: '/api/edit/day_programs', file: './routes/edit/day_programs' },
            { path: '/api/edit/daytime_sleepiness_assessment', file: './routes/edit/daytime_sleepiness_assessment' },
            { path: '/api/edit/deep_brain_stimulation', file: './routes/edit/deep_brain_stimulation' },
            { path: '/api/edit/delivery_planning', file: './routes/edit/delivery_planning' },
            { path: '/api/edit/dementia_assessment', file: './routes/edit/dementia_assessment' },
            { path: '/api/edit/dementia_education', file: './routes/edit/dementia_education' },
            { path: '/api/edit/dental_examination_reports', file: './routes/edit/dental_examination_reports' },
            { path: '/api/edit/dental_implant_surgery', file: './routes/edit/dental_implant_surgery' },
            { path: '/api/edit/detailed_family_pedigree', file: './routes/edit/detailed_family_pedigree' },
            { path: '/api/edit/dermatology_assessment', file: './routes/edit/dermatology_assessment' },
            { path: '/api/edit/dermatology_consultations', file: './routes/edit/dermatology_consultations' },
            { path: '/api/edit/dermatology_procedure_notes', file: './routes/edit/dermatology_procedure_notes' },
            { path: '/api/edit/developmental_assessments', file: './routes/edit/developmental_assessments' },
            { path: '/api/edit/early_childhood_development', file: './routes/edit/early_childhood_development' },
            { path: '/api/edit/developmental_milestones', file: './routes/edit/developmental_milestones' },
            { path: '/api/edit/dexa_scan_reports', file: './routes/edit/dexa_scan_reports' },
            { path: '/api/edit/diabetes_education', file: './routes/edit/diabetes_education' },
            { path: '/api/edit/diabetes_educator', file: './routes/edit/diabetes_educator' },
            { path: '/api/edit/diabetes_management', file: './routes/edit/diabetes_management' },
            { path: '/api/edit/diabetes_management_notes', file: './routes/edit/diabetes_management_notes' },
            { path: '/api/edit/diabetes_quality_metrics', file: './routes/edit/diabetes_quality_metrics' },
            { path: '/api/edit/diabetes_supplies', file: './routes/edit/diabetes_supplies' },
            { path: '/api/edit/diabetic_nephropathy', file: './routes/edit/diabetic_nephropathy' },
            { path: '/api/edit/diagnostic_impression', file: './routes/edit/diagnostic_impression' },
            { path: '/api/edit/diagnostic_studies', file: './routes/edit/diagnostic_studies' },
            { path: '/api/edit/dialysate_composition', file: './routes/edit/dialysate_composition' },
            { path: '/api/edit/dialysis_planning', file: './routes/edit/dialysis_planning' },
            { path: '/api/edit/dialysis_prescription', file: './routes/edit/dialysis_prescription' },
            { path: '/api/edit/dialysis_records', file: './routes/edit/dialysis_records' },
            { path: '/api/edit/dialysis_run_sheets', file: './routes/edit/dialysis_run_sheets' },
            { path: '/api/edit/dialyzer', file: './routes/edit/dialyzer' },
            { path: '/api/edit/dietary_interventions', file: './routes/edit/dietary_interventions' },
            { path: '/api/edit/disability_evaluations', file: './routes/edit/disability_evaluations' },
            { path: '/api/edit/discharge_planning', file: './routes/edit/discharge_planning' },
            { path: '/api/edit/disease_activity_scores', file: './routes/edit/disease_activity_scores' },
            { path: '/api/edit/disease_severity', file: './routes/edit/disease_severity' },
            { path: '/api/edit/dnr_orders', file: './routes/edit/dnr_orders' },
            { path: '/api/edit/doctors_medication_recommendations', file: './routes/edit/doctors_medication_recommendations' },
            { path: '/api/edit/document_metadata', file: './routes/edit/document_metadata' },
            { path: '/api/edit/donor_egg_cycle', file: './routes/edit/donor_egg_cycle' },
            { path: '/api/edit/drug_gene_interaction_report', file: './routes/edit/drug_gene_interaction_report' },
            { path: '/api/edit/durable_medical_equipment_orders', file: './routes/edit/durable_medical_equipment_orders' },
            { path: '/api/edit/dvt_prophylaxis', file: './routes/edit/dvt_prophylaxis' },
            { path: '/api/edit/ed_course', file: './routes/edit/ed_course' },
            { path: '/api/edit/ed_disposition', file: './routes/edit/ed_disposition' },
            { path: '/api/edit/ed_triage_assessment', file: './routes/edit/ed_triage_assessment' },
            { path: '/api/edit/education_initiated', file: './routes/edit/education_initiated' },
            { path: '/api/edit/eeg_reports', file: './routes/edit/eeg_reports' },
            { path: '/api/edit/elder_abuse_screening', file: './routes/edit/elder_abuse_screening' },
            { path: '/api/edit/emergency_airway_management', file: './routes/edit/emergency_airway_management' },
            { path: '/api/edit/emergency_assessment', file: './routes/edit/emergency_assessment' },
            { path: '/api/edit/emergency_discharge_summaries', file: './routes/edit/emergency_discharge_summaries' },
            { path: '/api/edit/emergency_observation_unit', file: './routes/edit/emergency_observation_unit' },
            { path: '/api/edit/emergency_reports', file: './routes/edit/emergency_reports' },
            { path: '/api/edit/emg_reports', file: './routes/edit/emg_reports' },
            { path: '/api/edit/ems_run_reports', file: './routes/edit/ems_run_reports' },
            { path: '/api/edit/endocrine_lab_results', file: './routes/edit/endocrine_lab_results' },
            { path: '/api/edit/endocrine_therapy', file: './routes/edit/endocrine_therapy' },
            { path: '/api/edit/endocrinology_assessment', file: './routes/edit/endocrinology_assessment' },
            { path: '/api/edit/endocrinology_consultations', file: './routes/edit/endocrinology_consultations' },
            { path: '/api/edit/endoscopy_findings', file: './routes/edit/endoscopy_findings' },
            { path: '/api/edit/ent_assessment', file: './routes/edit/ent_assessment' },
            { path: '/api/edit/ent_consultations', file: './routes/edit/ent_consultations' },
            { path: '/api/edit/enteral_feeding_assessment', file: './routes/edit/enteral_feeding_assessment' },
            { path: '/api/edit/environmental_exposures', file: './routes/edit/environmental_exposures' },
            { path: '/api/edit/epilepsy_assessment', file: './routes/edit/epilepsy_assessment' },
            { path: '/api/edit/ergonomic_assessment', file: './routes/edit/ergonomic_assessment' },
            { path: '/api/edit/estimated_blood_loss', file: './routes/edit/estimated_blood_loss' },
            { path: '/api/edit/estimated_delivery_date', file: './routes/edit/estimated_delivery_date' },
            { path: '/api/edit/estimated_time_to_dialysis', file: './routes/edit/estimated_time_to_dialysis' },
            { path: '/api/edit/excessive_glucose_monitoring', file: './routes/edit/excessive_glucose_monitoring' },
            { path: '/api/edit/exercise_prescription', file: './routes/edit/exercise_prescription' },
            { path: '/api/edit/exercise_program', file: './routes/edit/exercise_program' },
            { path: '/api/edit/exercise_recommendations', file: './routes/edit/exercise_recommendations' },
            { path: '/api/edit/extended_family_history', file: './routes/edit/extended_family_history' },
            { path: '/api/edit/extraintestinal_manifestations', file: './routes/edit/extraintestinal_manifestations' },
            { path: '/api/edit/facility', file: './routes/edit/facility' },
            { path: '/api/edit/fall_prevention_education', file: './routes/edit/fall_prevention_education' },
            { path: '/api/edit/fall_risk_assessments', file: './routes/edit/fall_risk_assessments' },
            { path: '/api/edit/family_medicine_assessment', file: './routes/edit/family_medicine_assessment' },
            { path: '/api/edit/family_medicine_visits', file: './routes/edit/family_medicine_visits' },
            { path: '/api/edit/family_meeting_notes', file: './routes/edit/family_meeting_notes' },
            { path: '/api/edit/fecal_calprotectin', file: './routes/edit/fecal_calprotectin' },
            { path: '/api/edit/fertility_preservation', file: './routes/edit/fertility_preservation' },
            { path: '/api/edit/fetal_assessment', file: './routes/edit/fetal_assessment' },
            { path: '/api/edit/fetal_surveillance', file: './routes/edit/fetal_surveillance' },
            { path: '/api/edit/fetal_ultrasound', file: './routes/edit/fetal_ultrasound' },
            { path: '/api/edit/first_trimester_screen_result', file: './routes/edit/first_trimester_screen_result' },
            { path: '/api/edit/flare_management', file: './routes/edit/flare_management' },
            { path: '/api/edit/flow_cytometry_reports', file: './routes/edit/flow_cytometry_reports' },
            { path: '/api/edit/fluid_electrolyte_management', file: './routes/edit/fluid_electrolyte_management' },
            { path: '/api/edit/fluid_intake', file: './routes/edit/fluid_intake' },
            { path: '/api/edit/fluid_output', file: './routes/edit/fluid_output' },
            { path: '/api/edit/ventilator_weaning_protocol', file: './routes/edit/ventilator_weaning_protocol' },
            { path: '/api/edit/follow_up_enhanced', file: './routes/edit/follow_up_enhanced' },
            { path: '/api/edit/follow_up_intelligence', file: './routes/edit/follow_up_intelligence' },
            { path: '/api/edit/follow_ups', file: './routes/edit/follow_ups' },
            { path: '/api/edit/food_insecurity', file: './routes/edit/food_insecurity' },
            { path: '/api/edit/foot_exam', file: './routes/edit/foot_exam' },
            { path: '/api/edit/wound_healing_hyperbaric', file: './routes/edit/wound_healing_hyperbaric' },
            { path: '/api/edit/hyperbaric_oxygen_therapy', file: './routes/edit/hyperbaric_oxygen_therapy' },
            { path: '/api/edit/decompression_sickness_treatment', file: './routes/edit/decompression_sickness_treatment' },
            { path: '/api/edit/diabetic_foot_assessment', file: './routes/edit/diabetic_foot_assessment' },
            { path: '/api/edit/podiatry_consultations', file: './routes/edit/podiatry_consultations' },
            { path: '/api/edit/podiatry_examinations', file: './routes/edit/podiatry_examinations' },
            { path: '/api/edit/bunion_surgery_evaluation', file: './routes/edit/bunion_surgery_evaluation' },
            { path: '/api/edit/heel_pain_assessment', file: './routes/edit/heel_pain_assessment' },
            { path: '/api/edit/ingrown_toenail_treatment', file: './routes/edit/ingrown_toenail_treatment' },
            { path: '/api/edit/plantar_fasciitis_management', file: './routes/edit/plantar_fasciitis_management' },
            { path: '/api/edit/foot_orthotics_assessment', file: './routes/edit/foot_orthotics_assessment' },
            { path: '/api/edit/breastfeeding_recommendation', file: './routes/edit/breastfeeding_recommendation' },
            { path: '/api/edit/postpartum_diabetes_risk', file: './routes/edit/postpartum_diabetes_risk' },
            { path: '/api/edit/gdm_recurrence_risk', file: './routes/edit/gdm_recurrence_risk' },
            { path: '/api/edit/postpartum_glucose_monitoring', file: './routes/edit/postpartum_glucose_monitoring' },
            { path: '/api/edit/total_weight_gain', file: './routes/edit/total_weight_gain' },
            { path: '/api/edit/pre_pregnancy_weight', file: './routes/edit/pre_pregnancy_weight' },
            { path: '/api/edit/early_maternity_leave', file: './routes/edit/early_maternity_leave' },
            { path: '/api/edit/inter_pregnancy_weight_management', file: './routes/edit/inter_pregnancy_weight_management' },
            { path: '/api/edit/toxicity_assessment', file: './routes/edit/toxicity_assessment' },
            { path: '/api/edit/oncologic_emergencies', file: './routes/edit/oncologic_emergencies' },
            { path: '/api/edit/pre_chemotherapy_workup', file: './routes/edit/pre_chemotherapy_workup' },
            { path: '/api/edit/toxicology_reports', file: './routes/edit/toxicology_reports' },
            { path: '/api/edit/fitness_for_duty_evaluations', file: './routes/edit/fitness_for_duty_evaluations' },
            { path: '/api/edit/employment_counseling', file: './routes/edit/employment_counseling' },
            { path: '/api/edit/pre_employment_physical', file: './routes/edit/pre_employment_physical' },
            { path: '/api/edit/prenatal_testing_reports', file: './routes/edit/prenatal_testing_reports' },
            { path: '/api/edit/maternal_fetal_reports', file: './routes/edit/maternal_fetal_reports' },
            { path: '/api/edit/ultrasound_ob_reports', file: './routes/edit/ultrasound_ob_reports' },
            { path: '/api/edit/macrosomia_threshold', file: './routes/edit/macrosomia_threshold' },
            { path: '/api/edit/psychiatric_discharge_summaries', file: './routes/edit/psychiatric_discharge_summaries' },
            { path: '/api/edit/psychiatric_progress_notes', file: './routes/edit/psychiatric_progress_notes' },
            { path: '/api/edit/homicide_risk_assessment', file: './routes/edit/homicide_risk_assessment' },
            { path: '/api/edit/psychiatric_review', file: './routes/edit/psychiatric_review' },
            { path: '/api/edit/behavioral_health_goals', file: './routes/edit/behavioral_health_goals' },
            { path: '/api/edit/functional_assessments', file: './routes/edit/functional_assessments' },
            { path: '/api/edit/functional_mri_studies', file: './routes/edit/functional_mri_studies' },
            { path: '/api/edit/liver_transplant_evaluation', file: './routes/edit/liver_transplant_evaluation' },
            { path: '/api/edit/lung_transplant_evaluation', file: './routes/edit/lung_transplant_evaluation' },
            { path: '/api/edit/stem_cell_transplant_assessment', file: './routes/edit/stem_cell_transplant_assessment' },
            { path: '/api/edit/bleeding_risk_assessment', file: './routes/edit/bleeding_risk_assessment' },
            { path: '/api/edit/diabetes_management_plan', file: './routes/edit/diabetes_management_plan' },
            { path: '/api/edit/pump_advanced_settings', file: './routes/edit/pump_advanced_settings' },
            { path: '/api/edit/pancreas_transplant_evaluation', file: './routes/edit/pancreas_transplant_evaluation' },
            { path: '/api/edit/liver_transplant_follow_up', file: './routes/edit/liver_transplant_follow_up' },
            { path: '/api/edit/lung_transplant_follow_up', file: './routes/edit/lung_transplant_follow_up' },
            { path: '/api/edit/adhd_assessment', file: './routes/edit/adhd_assessment' },
            { path: '/api/edit/access_planning', file: './routes/edit/access_planning' },
            { path: '/api/edit/acmg_guidelines_reference', file: './routes/edit/acmg_guidelines_reference' },
            { path: '/api/edit/acute_kidney_injury', file: './routes/edit/acute_kidney_injury' },
            { path: '/api/edit/additional_data', file: './routes/edit/additional_data' },
            { path: '/api/edit/admission_recommendations', file: './routes/edit/admission_recommendations' },
            { path: '/api/edit/advance_care_planning', file: './routes/edit/advance_care_planning' },
            { path: '/api/edit/advance_directives', file: './routes/edit/advance_directives' },
            { path: '/api/edit/airway_clearance_therapy', file: './routes/edit/airway_clearance_therapy' },
            { path: '/api/edit/airway_management_records', file: './routes/edit/airway_management_records' },
            { path: '/api/edit/allergy_assessments', file: './routes/edit/allergy_assessments' },
            { path: '/api/edit/allergy_immunology_assessment', file: './routes/edit/allergy_immunology_assessment' },
            { path: '/api/edit/allergy_skin_testing', file: './routes/edit/allergy_skin_testing' },
            { path: '/api/edit/anatomy_scan_result', file: './routes/edit/anatomy_scan_result' },
            { path: '/api/edit/anesthesia', file: './routes/edit/anesthesia' },
            { path: '/api/edit/anesthesia_complications', file: './routes/edit/anesthesia_complications' },
            { path: '/api/edit/anesthesia_consent', file: './routes/edit/anesthesia_consent' },
            { path: '/api/edit/anesthesia_records', file: './routes/edit/anesthesia_records' },
            { path: '/api/edit/anesthesiology_assessment', file: './routes/edit/anesthesiology_assessment' },
            { path: '/api/edit/antibiotic_stewardship', file: './routes/edit/antibiotic_stewardship' },
            { path: '/api/edit/antibiogram_reports', file: './routes/edit/antibiogram_reports' },
            { path: '/api/edit/anticoagulation_management', file: './routes/edit/anticoagulation_management' },
            { path: '/api/edit/appetite_stimulants', file: './routes/edit/appetite_stimulants' },
            { path: '/api/edit/apgar_scores', file: './routes/edit/apgar_scores' },
            { path: '/api/edit/arterial_blood_gases', file: './routes/edit/arterial_blood_gases' },
            { path: '/api/edit/anticipatory_guidance', file: './routes/edit/anticipatory_guidance' },
            { path: '/api/edit/antimicrobial_susceptibility', file: './routes/edit/antimicrobial_susceptibility' },
            { path: '/api/edit/articular_cartilage', file: './routes/edit/articular_cartilage' },
            { path: '/api/edit/arthritis_assessments', file: './routes/edit/arthritis_assessments' },
            { path: '/api/edit/assistive_devices', file: './routes/edit/assistive_devices' },
            { path: '/api/edit/athletic_injury_assessment', file: './routes/edit/athletic_injury_assessment' },
            { path: '/api/edit/asthma_action_plan', file: './routes/edit/asthma_action_plan' },
            { path: '/api/edit/asthma_assessments', file: './routes/edit/asthma_assessments' },
            { path: '/api/edit/asthma_management_notes', file: './routes/edit/asthma_management_notes' },
            { path: '/api/edit/athlete_specific_data', file: './routes/edit/athlete_specific_data' },
            { path: '/api/edit/audiometry_reports', file: './routes/edit/audiometry_reports' },
            { path: '/api/edit/autoantibody_profile', file: './routes/edit/autoantibody_profile' },
            { path: '/api/edit/autoimmune_evaluations', file: './routes/edit/autoimmune_evaluations' },
            { path: '/api/edit/autoimmune_panels', file: './routes/edit/autoimmune_panels' },
            { path: '/api/edit/autopsy_reports', file: './routes/edit/autopsy_reports' },
            { path: '/api/edit/barriers_psychosocial_issues', file: './routes/edit/barriers_psychosocial_issues' },
            { path: '/api/edit/basal_rate_adjustments', file: './routes/edit/basal_rate_adjustments' },
            { path: '/api/edit/behavioral_assessment', file: './routes/edit/behavioral_assessment' },
            { path: '/api/edit/biologic_therapy_records', file: './routes/edit/biologic_therapy_records' },
            { path: '/api/edit/biopsy_reports', file: './routes/edit/biopsy_reports' },
            { path: '/api/edit/biopsychosocial_formulation', file: './routes/edit/biopsychosocial_formulation' },
            { path: '/api/edit/birth_history', file: './routes/edit/birth_history' },
            { path: '/api/edit/birth_plan', file: './routes/edit/birth_plan' },
            { path: '/api/edit/blood_disorder_reports', file: './routes/edit/blood_disorder_reports' },
            { path: '/api/edit/blood_sample_collection_status', file: './routes/edit/blood_sample_collection_status' },
            { path: '/api/edit/rheumatoid_arthritis_assessment', file: './routes/edit/rheumatoid_arthritis_assessment' },
            { path: '/api/edit/advance_directive_discussion', file: './routes/edit/advance_directive_discussion' },
            { path: '/api/edit/adult_day_program_info', file: './routes/edit/adult_day_program_info' },
            { path: '/api/edit/nutritional_status', file: './routes/edit/nutritional_status' },
            { path: '/api/edit/operative_time', file: './routes/edit/operative_time' },
            { path: '/api/edit/vascular_surgery_assessment', file: './routes/edit/vascular_surgery_assessment' },
            { path: '/api/edit/job_hazard_analysis', file: './routes/edit/job_hazard_analysis' },
            { path: '/api/edit/vascular_bypass_surgery', file: './routes/edit/vascular_bypass_surgery' },
            { path: '/api/edit/venous_insufficiency_assessment', file: './routes/edit/venous_insufficiency_assessment' },
            { path: '/api/edit/aortic_aneurysm_surveillance', file: './routes/edit/aortic_aneurysm_surveillance' },
            { path: '/api/edit/trauma_flow_sheets', file: './routes/edit/trauma_flow_sheets' },
            { path: '/api/edit/trauma_assessment', file: './routes/edit/trauma_assessment' },
            { path: '/api/edit/trauma_scoring', file: './routes/edit/trauma_scoring' },
            { path: '/api/edit/emergency_procedures', file: './routes/edit/emergency_procedures' },
            { path: '/api/edit/immunization_schedule', file: './routes/edit/immunization_schedule' },
            { path: '/api/edit/travel_vaccination_records', file: './routes/edit/travel_vaccination_records' },
            { path: '/api/edit/facial_trauma_assessment', file: './routes/edit/facial_trauma_assessment' },
            { path: '/api/edit/immediate_recommendations', file: './routes/edit/immediate_recommendations' },
            { path: '/api/edit/immunization_record', file: './routes/edit/immunization_record' },
            { path: '/api/edit/iv_infusions', file: './routes/edit/iv_infusions' },
            { path: '/api/edit/venous_thromboembolism_risk', file: './routes/edit/venous_thromboembolism_risk' },
            { path: '/api/edit/performance_assessment', file: './routes/edit/performance_assessment' },
            { path: '/api/edit/document_type', file: './routes/edit/document_type' },
            { path: '/api/edit/blood_glucose_logs', file: './routes/edit/blood_glucose_logs' },
            { path: '/api/edit/blood_glucose_monitoring', file: './routes/edit/blood_glucose_monitoring' },
            { path: '/api/edit/blood_pressure_readings', file: './routes/edit/blood_pressure_readings' },
            { path: '/api/edit/blood_products_ordered', file: './routes/edit/blood_products_ordered' },
            { path: '/api/edit/blood_smears', file: './routes/edit/blood_smears' },
            { path: '/api/edit/bolus_adjustments', file: './routes/edit/bolus_adjustments' },
            { path: '/api/edit/bone_health', file: './routes/edit/bone_health' },
            { path: '/api/edit/bone_marrow_studies', file: './routes/edit/bone_marrow_studies' },
            { path: '/api/edit/bone_scan_reports', file: './routes/edit/bone_scan_reports' },
            { path: '/api/edit/brain_tumor_characteristics', file: './routes/edit/brain_tumor_characteristics' },
            { path: '/api/edit/brain_tumor_molecular_markers', file: './routes/edit/brain_tumor_molecular_markers' },
            { path: '/api/edit/bronchial_hygiene_therapy', file: './routes/edit/bronchial_hygiene_therapy' },
            { path: '/api/edit/syphilis_treatment_follow_up', file: './routes/edit/syphilis_treatment_follow_up' },
            { path: '/api/edit/varicose_vein_treatment', file: './routes/edit/varicose_vein_treatment' },
            { path: '/api/edit/heart_transplant_follow_up', file: './routes/edit/heart_transplant_follow_up' },
            { path: '/api/edit/kidney_transplant_follow_up', file: './routes/edit/kidney_transplant_follow_up' },
            { path: '/api/edit/foot_reconstruction', file: './routes/edit/foot_reconstruction' },
            { path: '/api/edit/pulmonary_rehabilitation', file: './routes/edit/pulmonary_rehabilitation' },
            { path: '/api/edit/medication_action_plan', file: './routes/edit/medication_action_plan' },
            { path: '/api/edit/polypharmacy', file: './routes/edit/polypharmacy' },
            { path: '/api/edit/cesarean_threshold', file: './routes/edit/cesarean_threshold' },
            { path: '/api/edit/diabetes_educator_training', file: './routes/edit/diabetes_educator_training' },
            { path: '/api/edit/height_measurements', file: './routes/edit/height_measurements' },
            { path: '/api/edit/point_of_care_ultrasound_heart_rate', file: './routes/edit/point_of_care_ultrasound_heart_rate' },
            { path: '/api/edit/glucose_testing_weeks', file: './routes/edit/glucose_testing_weeks' },
            { path: '/api/edit/social_functional_assessment', file: './routes/edit/social_functional_assessment' },
            { path: '/api/edit/patient_emotional_response', file: './routes/edit/patient_emotional_response' },
            { path: '/api/edit/support_group_referral', file: './routes/edit/support_group_referral' },
            { path: '/api/edit/partner_involvement', file: './routes/edit/partner_involvement' },
            { path: '/api/edit/admission_decisions', file: './routes/edit/admission_decisions' },
            { path: '/api/edit/post_op_testing', file: './routes/edit/post_op_testing' },
            { path: '/api/edit/postop_testing', file: './routes/edit/postop_testing' },
            { path: '/api/edit/bone_marrow_transplant_evaluation', file: './routes/edit/bone_marrow_transplant_evaluation' },
            { path: '/api/edit/bone_marrow_transplant_follow_up', file: './routes/edit/bone_marrow_transplant_follow_up' },
            { path: '/api/edit/pancreas_transplant_follow_up', file: './routes/edit/pancreas_transplant_follow_up' },
            { path: '/api/edit/bone_marrow_reports', file: './routes/edit/bone_marrow_reports' },
            { path: '/api/edit/cytogenetics', file: './routes/edit/cytogenetics' },
            { path: '/api/edit/blood_products', file: './routes/edit/blood_products' },
            { path: '/api/edit/pre_operative_preparation', file: './routes/edit/pre_operative_preparation' },
            { path: '/api/edit/amniotic_fluid_index_current', file: './routes/edit/amniotic_fluid_index_current' },
            { path: '/api/edit/fetal_echo_results', file: './routes/edit/fetal_echo_results' },
            { path: '/api/edit/annual_physical_examination', file: './routes/edit/annual_physical_examination' },
            { path: '/api/edit/caregiver_support_groups', file: './routes/edit/caregiver_support_groups' },
            { path: '/api/edit/family_meeting_decisions', file: './routes/edit/family_meeting_decisions' },
            { path: '/api/edit/frailty_assessment', file: './routes/edit/frailty_assessment' },
            { path: '/api/edit/geriatric_nutritional_assessment', file: './routes/edit/geriatric_nutritional_assessment' },
            { path: '/api/edit/chronic_disease_goals', file: './routes/edit/chronic_disease_goals' },
            { path: '/api/edit/continuous_glucose_monitor_discussion', file: './routes/edit/continuous_glucose_monitor_discussion' },
            { path: '/api/edit/hypoglycemia_protocol', file: './routes/edit/hypoglycemia_protocol' },
            { path: '/api/edit/hormone_therapy_records', file: './routes/edit/hormone_therapy_records' },
            { path: '/api/edit/urology_assessment', file: './routes/edit/urology_assessment' },
            { path: '/api/edit/neuropsych_testing', file: './routes/edit/neuropsych_testing' },
            { path: '/api/edit/wellness_visit_documentation', file: './routes/edit/wellness_visit_documentation' },
            { path: '/api/edit/trend_analysis', file: './routes/edit/trend_analysis' },
            { path: '/api/edit/biologic_therapy', file: './routes/edit/biologic_therapy' },
            { path: '/api/edit/continuous_glucose_monitor', file: './routes/edit/continuous_glucose_monitor' },
            { path: '/api/edit/vital_signs_monitoring', file: './routes/edit/vital_signs_monitoring' },
            { path: '/api/edit/obstetric_ultrasound_reports', file: './routes/edit/obstetric_ultrasound_reports' },
            { path: '/api/edit/doctors_medications_recommendations', file: './routes/edit/doctors_medications_recommendations' },
            { path: '/api/edit/doctors_medications_recommendations_optimizations', file: './routes/edit/doctors_medications_recommendations_optimizations' },
            { path: '/api/edit/allergies_assessments', file: './routes/edit/allergies_assessments' },
            { path: '/api/edit/occupational_exposure_records', file: './routes/edit/occupational_exposure_records' },
            { path: '/api/edit/fmla_documentation_note', file: './routes/edit/fmla_documentation_note' },
            { path: '/api/edit/workers_comp_evaluations', file: './routes/edit/workers_comp_evaluations' },
            { path: '/api/edit/emergency_disposition', file: './routes/edit/emergency_disposition' },
            { path: '/api/edit/procedure_requests', file: './routes/edit/procedure_requests' },
            { path: '/api/edit/port_placement', file: './routes/edit/port_placement' },
            { path: '/api/edit/burn_assessment', file: './routes/edit/burn_assessment' },
            { path: '/api/edit/burn_fluid_resuscitation', file: './routes/edit/burn_fluid_resuscitation' },
            { path: '/api/edit/burn_wound_care', file: './routes/edit/burn_wound_care' },
            { path: '/api/edit/burn_rehabilitation', file: './routes/edit/burn_rehabilitation' },
            { path: '/api/edit/cam_icu', file: './routes/edit/cam_icu' },
            { path: '/api/edit/ckd_assessment', file: './routes/edit/ckd_assessment' },
            { path: '/api/edit/ckd_management', file: './routes/edit/ckd_management' },
            { path: '/api/edit/cancer_diagnosis', file: './routes/edit/cancer_diagnosis' },
            { path: '/api/edit/cancer_related_side_effects', file: './routes/edit/cancer_related_side_effects' },
            { path: '/api/edit/cancer_screening_records', file: './routes/edit/cancer_screening_records' },
            { path: '/api/edit/cancer_staging', file: './routes/edit/cancer_staging' },
            { path: '/api/edit/carbohydrate_counting_education', file: './routes/edit/carbohydrate_counting_education' },
            { path: '/api/edit/cardiac_catheterization_reports', file: './routes/edit/cardiac_catheterization_reports' },
            { path: '/api/edit/cardiac_device_interrogations', file: './routes/edit/cardiac_device_interrogations' },
            { path: '/api/edit/cardiac_monitoring', file: './routes/edit/cardiac_monitoring' },
            { path: '/api/edit/cardiac_rehabilitation_reports', file: './routes/edit/cardiac_rehabilitation_reports' },
            { path: '/api/edit/cardiology_admission_notes', file: './routes/edit/cardiology_admission_notes' },
            { path: '/api/edit/cardiology_consultations', file: './routes/edit/cardiology_consultations' },
            { path: '/api/edit/cardiology_followup_reports', file: './routes/edit/cardiology_followup_reports' },
            { path: '/api/edit/cardiovascular_risk_reduction', file: './routes/edit/cardiovascular_risk_reduction' },
            { path: '/api/edit/cardiovascular_risk_screening', file: './routes/edit/cardiovascular_risk_screening' },
            { path: '/api/edit/care_coordination', file: './routes/edit/care_coordination' },
            { path: '/api/edit/care_coordination_notes', file: './routes/edit/care_coordination_notes' },
            { path: '/api/edit/care_team', file: './routes/edit/care_team' },
            { path: '/api/edit/caregiver_assessment', file: './routes/edit/caregiver_assessment' },
            { path: '/api/edit/caregiver_support', file: './routes/edit/caregiver_support' },
            { path: '/api/edit/cascade_testing_protocol', file: './routes/edit/cascade_testing_protocol' },
            { path: '/api/edit/case_summaries', file: './routes/edit/case_summaries' },
            { path: '/api/edit/cell_free_dna_result', file: './routes/edit/cell_free_dna_results' },
            { path: '/api/edit/cgm_data', file: './routes/edit/cgm_data' },
            { path: '/api/edit/challenge_tests', file: './routes/edit/challenge_tests' },
            { path: '/api/edit/chemotherapy_records', file: './routes/edit/chemotherapy_records' },
            { path: '/api/edit/chemotherapy_regimen', file: './routes/edit/chemotherapy_regimen' },
            { path: '/api/edit/children_specific_risk', file: './routes/edit/children_specific_risk' },
            { path: '/api/edit/chiropractic_consultation', file: './routes/edit/chiropractic_consultations' },
            { path: '/api/edit/chiropractic_treatment_plan', file: './routes/edit/chiropractic_treatment_plan' },
            { path: '/api/edit/chiropractic_x_ray_review', file: './routes/edit/chiropractic_x_ray_review' },
            { path: '/api/edit/chronic_disease_management', file: './routes/edit/chronic_disease_management' },
            { path: '/api/edit/chronic_pain_assessment', file: './routes/edit/chronic_pain_assessment' },
            { path: '/api/edit/clinical_decision_support', file: './routes/edit/clinical_decision_support' },
            { path: '/api/edit/clinical_risk_scores', file: './routes/edit/clinical_risk_scores' },
            { path: '/api/edit/clinical_scores', file: './routes/edit/clinical_scores' },
            { path: '/api/edit/clinical_trial_documents', file: './routes/edit/clinical_trial_documents' },
            { path: '/api/edit/clinical_trials', file: './routes/edit/clinical_trials' },
            { path: '/api/edit/closure_technique', file: './routes/edit/closure_technique' },
            { path: '/api/edit/functional_status', file: './routes/edit/functional_status' },
            { path: '/api/edit/gi_risk_assessment', file: './routes/edit/gi_risk_assessment' },
            { path: '/api/edit/gait_analysis', file: './routes/edit/gait_analysis' },
            { path: '/api/edit/gastroenterology_consultations', file: './routes/edit/gastroenterology_consultations' },
            { path: '/api/edit/genetic_oncology', file: './routes/edit/genetic_oncology' },
            { path: '/api/edit/genetic_testing_reports', file: './routes/edit/genetic_testing_reports' },
            { path: '/api/edit/genetics_psychosocial_assessment', file: './routes/edit/genetics_psychosocial_assessment' },
            { path: '/api/edit/geriatric_assessments', file: './routes/edit/geriatric_assessments' },
            { path: '/api/edit/geriatric_care_planning', file: './routes/edit/geriatric_care_planning' },
            { path: '/api/edit/geriatric_cognitive_assessment', file: './routes/edit/geriatric_cognitive_assessment' },
            { path: '/api/edit/geriatric_medications', file: './routes/edit/geriatric_medications' },
            { path: '/api/edit/gestational_diabetes', file: './routes/edit/gestational_diabetes' },
            { path: '/api/edit/glasgow_coma_scale', file: './routes/edit/glasgow_coma_scale' },
            { path: '/api/edit/glaucoma_assessments', file: './routes/edit/glaucoma_assessments' },
            { path: '/api/edit/glaucoma_management', file: './routes/edit/glaucoma_management' },
            { path: '/api/edit/glomerular_disease', file: './routes/edit/glomerular_disease' },
            { path: '/api/edit/glucose_monitoring_frequency', file: './routes/edit/glucose_monitoring_frequency' },
            { path: '/api/edit/glucose_monitoring_goals', file: './routes/edit/glucose_monitoring_goals' },
            { path: '/api/edit/goals_of_care_discussion', file: './routes/edit/goals_of_care_discussion' },
            { path: '/api/edit/goals_of_care_discussions', file: './routes/edit/goals_of_care_discussions' },
            { path: '/api/edit/growth_parameters', file: './routes/edit/growth_parameters' },
            { path: '/api/edit/gout_assessment', file: './routes/edit/gout_assessment' },
            { path: '/api/edit/guideline_compliance', file: './routes/edit/guideline_compliance' },
            { path: '/api/edit/gynecology_consultations', file: './routes/edit/gynecology_consultations' },
            { path: '/api/edit/harm_reduction_counseling', file: './routes/edit/harm_reduction_counseling' },
            { path: '/api/edit/headache_assessment', file: './routes/edit/headache_assessment' },
            { path: '/api/edit/health_maintenance', file: './routes/edit/health_maintenance' },
            { path: '/api/edit/heart_transplant_evaluation', file: './routes/edit/heart_transplant_evaluation' },
            { path: '/api/edit/hematology_assessment', file: './routes/edit/hematology_assessment' },
            { path: '/api/edit/hematology_consultations', file: './routes/edit/hematology_consultations' },
            { path: '/api/edit/hepatitis_c_management', file: './routes/edit/hepatitis_c_management' },
            { path: '/api/edit/hiv_history', file: './routes/edit/hiv_history' },
            { path: '/api/edit/home_health_notes', file: './routes/edit/home_health_notes' },
            { path: '/api/edit/home_health_orders', file: './routes/edit/home_health_orders' },
            { path: '/api/edit/home_monitoring', file: './routes/edit/home_monitoring' },
            { path: '/api/edit/home_safety', file: './routes/edit/home_safety' },
            { path: '/api/edit/hormone_panels', file: './routes/edit/hormone_panels' },
            { path: '/api/edit/hospice_notes', file: './routes/edit/hospice_notes' },
            { path: '/api/edit/mortality_risk_assessment', file: './routes/edit/mortality_risk_assessment' },
            { path: '/api/edit/pressure_ulcer_risk', file: './routes/edit/pressure_ulcer_risk' },
            { path: '/api/edit/palliative_care', file: './routes/edit/palliative_care' },
            { path: '/api/edit/hydration_management', file: './routes/edit/hydration_management' },
            { path: '/api/edit/hospital_admission_notes', file: './routes/edit/hospital_admission_notes' },
            { path: '/api/edit/hospital_transfer_notes', file: './routes/edit/hospital_transfer_notes' },
            { path: '/api/edit/admission_assessments', file: './routes/edit/admission_assessments' },
            { path: '/api/edit/second_opinion_reports', file: './routes/edit/second_opinion_reports' },
            { path: '/api/edit/readmission_risk_assessment', file: './routes/edit/readmission_risk_assessment' },
            { path: '/api/edit/myositis_assessment', file: './routes/edit/myositis_assessment' },
            { path: '/api/edit/polycystic_kidney_disease', file: './routes/edit/polycystic_kidney_disease' },
            { path: '/api/edit/travel_medicine_assessment', file: './routes/edit/travel_medicine_assessment' },
            { path: '/api/edit/travel_health_certificates', file: './routes/edit/travel_health_certificates' },
            { path: '/api/edit/health_coaching_notes', file: './routes/edit/health_coaching_notes' },
            { path: '/api/edit/ibd_biomarkers', file: './routes/edit/ibd_biomarkers' },
            { path: '/api/edit/respiratory_infections', file: './routes/edit/respiratory_infections' },
            { path: '/api/edit/transfer_summaries', file: './routes/edit/transfer_summaries' },
            { path: '/api/edit/hospital_discharge', file: './routes/edit/hospital_discharge' },
            { path: '/api/edit/hospital_discharge_summaries', file: './routes/edit/hospital_discharge_summaries' },
            { path: '/api/edit/hourly_vital_signs', file: './routes/edit/hourly_vital_signs' },
            { path: '/api/edit/hypertensive_nephropathy', file: './routes/edit/hypertensive_nephropathy' },
            { path: '/api/edit/hypoglycemia_management', file: './routes/edit/hypoglycemia_management' },
            { path: '/api/edit/ibd_assessment', file: './routes/edit/ibd_assessment' },
            { path: '/api/edit/ibd_consultation_details', file: './routes/edit/ibd_consultation_details' },
            { path: '/api/edit/ibd_surgical_planning', file: './routes/edit/ibd_surgical_planning' },
            { path: '/api/edit/icu_flow_sheets', file: './routes/edit/icu_flow_sheets' },
            { path: '/api/edit/imaging_orders', file: './routes/edit/imaging_orders' },
            { path: '/api/edit/immediate_interventions', file: './routes/edit/immediate_interventions' },
            { path: '/api/edit/immune_function_tests', file: './routes/edit/immune_function_tests' },
            { path: '/api/edit/immune_reconstitution_planning', file: './routes/edit/immune_reconstitution_planning' },
            { path: '/api/edit/infection_control_records', file: './routes/edit/infection_control_records' },
            { path: '/api/edit/infectious_disease_assessment', file: './routes/edit/infectious_disease_assessment' },
            { path: '/api/edit/infection_risk_monitoring', file: './routes/edit/infection_risk_monitoring' },
            { path: '/api/edit/infection_surveillance', file: './routes/edit/infection_surveillance' },
            { path: '/api/edit/indian_diet_exchange_lists', file: './routes/edit/indian_diet_exchange_lists' },
            { path: '/api/edit/inflammatory_bowel_reports', file: './routes/edit/inflammatory_bowel_reports' },
            { path: '/api/edit/inflammatory_markers', file: './routes/edit/inflammatory_markers' },
            { path: '/api/edit/infliximab_drug_monitoring', file: './routes/edit/infliximab_drug_monitoring' },
            { path: '/api/edit/infusion_therapy', file: './routes/edit/infusion_therapy' },
            { path: '/api/edit/inheritance_pattern_details', file: './routes/edit/inheritance_pattern_details' },
            { path: '/api/edit/injury_details', file: './routes/edit/injury_details' },
            { path: '/api/edit/insomnia_assessment', file: './routes/edit/insomnia_assessment' },
            { path: '/api/edit/insulin_adjustment_protocol', file: './routes/edit/insulin_adjustment_protocol' },
            { path: '/api/edit/insulin_pump_settings', file: './routes/edit/insulin_pump_settings' },
            { path: '/api/edit/insulin_regimen', file: './routes/edit/insulin_regimen' },
            { path: '/api/edit/insulin_storage_instructions', file: './routes/edit/insulin_storage_instructions' },
            { path: '/api/edit/insulin_timing_instructions', file: './routes/edit/insulin_timing_instructions' },
            { path: '/api/edit/insurance_forms', file: './routes/edit/insurance_forms' },
            { path: '/api/edit/intake_output_records', file: './routes/edit/intake_output_records' },
            { path: '/api/edit/intelligent_recommendations', file: './routes/edit/intelligent_recommendations' },
            { path: '/api/edit/interval_history', file: './routes/edit/interval_history' },
            { path: '/api/edit/interventional_pain_procedures', file: './routes/edit/interventional_pain_procedures' },
            { path: '/api/edit/interventional_radiology_notes', file: './routes/edit/interventional_radiology_notes' },
            { path: '/api/edit/intradialytic_monitoring', file: './routes/edit/intradialytic_monitoring' },
            { path: '/api/edit/intraoperative_cholangiography', file: './routes/edit/intraoperative_cholangiography' },
            { path: '/api/edit/intraoperative_findings', file: './routes/edit/intraoperative_findings' },
            { path: '/api/edit/intraoperative_imaging', file: './routes/edit/intraoperative_imaging' },
            { path: '/api/edit/intraoperative_monitoring', file: './routes/edit/intraoperative_monitoring' },
            { path: '/api/edit/intraoperative_records', file: './routes/edit/intraoperative_records' },
            { path: '/api/edit/isolation_precautions', file: './routes/edit/isolation_precautions' },
            { path: '/api/edit/jaw_reconstruction', file: './routes/edit/jaw_reconstruction' },
            { path: '/api/edit/ketone_monitoring_instructions', file: './routes/edit/ketone_monitoring_instructions' },
            { path: '/api/edit/kidney_disease_progression_timeline', file: './routes/edit/kidney_disease_progression_timeline' },
            { path: '/api/edit/kidney_function_reports', file: './routes/edit/kidney_function_reports' },
            { path: '/api/edit/lab_orders', file: './routes/edit/lab_orders' },
            { path: '/api/edit/labor_delivery_records', file: './routes/edit/labor_delivery_records' },
            { path: '/api/edit/laryngoscopy_reports', file: './routes/edit/laryngoscopy_reports' },
            { path: '/api/edit/lifestyle_assessments', file: './routes/edit/lifestyle_assessments' },
            { path: '/api/edit/lifestyle_counseling', file: './routes/edit/lifestyle_counseling' },
            { path: '/api/edit/lifestyle_risk_assessment', file: './routes/edit/lifestyle_risk_assessment' },
            { path: '/api/edit/ligament_reconstruction', file: './routes/edit/ligament_reconstruction' },
            { path: '/api/edit/lupus_assessment', file: './routes/edit/lupus_assessment' },
            { path: '/api/edit/lymph_node_cytomorphology', file: './routes/edit/lymph_node_cytomorphology' },
            { path: '/api/edit/low_vision_evaluation', file: './routes/edit/low_vision_evaluation' },
            { path: '/api/edit/mammography_reports', file: './routes/edit/mammography_reports' },
            { path: '/api/edit/maternal_labs', file: './routes/edit/maternal_labs' },
            { path: '/api/edit/maternal_weight_monitoring', file: './routes/edit/maternal_weight_monitoring' },
            { path: '/api/edit/mayo_score', file: './routes/edit/mayo_score' },
            { path: '/api/edit/mechanism_of_injury', file: './routes/edit/mechanism_of_injury' },
            { path: '/api/edit/medical_alerts', file: './routes/edit/medical_alerts' },
            { path: '/api/edit/medical_certificates', file: './routes/edit/medical_certificates' },
            { path: '/api/edit/medical_geneticist', file: './routes/edit/medical_geneticist' },
            { path: '/api/edit/medical_history', file: './routes/edit/medical_history' },
            { path: '/api/edit/medical_power_of_attorney', file: './routes/edit/medical_power_of_attorney' },
            { path: '/api/edit/medical_reconciliation_forms', file: './routes/edit/medical_reconciliation_forms' },
            { path: '/api/edit/medication_access_programs', file: './routes/edit/medication_access_programs' },
            { path: '/api/edit/medication_administration_records', file: './routes/edit/medication_administration_records' },
            { path: '/api/edit/medication_changes_discontinued', file: './routes/edit/medication_changes_discontinued' },
            { path: '/api/edit/medication_changes_dose', file: './routes/edit/medication_changes_dose' },
            { path: '/api/edit/medication_changes_new', file: './routes/edit/medication_changes_new' },
            { path: '/api/edit/medication_deprescribing', file: './routes/edit/medication_deprescribing' },
            { path: '/api/edit/medication_optimization', file: './routes/edit/medication_optimization' },
            { path: '/api/edit/medication_reconciliation', file: './routes/edit/medication_reconciliation' },
            { path: '/api/edit/medication_renal_dosing', file: './routes/edit/medication_renal_dosing' },
            { path: '/api/edit/medication_safety', file: './routes/edit/medication_safety' },
            { path: '/api/edit/medication_safety_alerts', file: './routes/edit/medication_safety_alerts' },
            { path: '/api/edit/medication_therapy_management', file: './routes/edit/medication_therapy_management' },
            { path: '/api/edit/medications_administered', file: './routes/edit/medications_administered' },
            { path: '/api/edit/meniscus_repair', file: './routes/edit/meniscus_repair' },
            { path: '/api/edit/mental_health_assessments', file: './routes/edit/mental_health_assessments' },
            { path: '/api/edit/mental_health_resources', file: './routes/edit/mental_health_resources' },
            { path: '/api/edit/microbiology_culture_reports', file: './routes/edit/microbiology_culture_reports' },
            { path: '/api/edit/mineral_bone_disease', file: './routes/edit/mineral_bone_disease' },
            { path: '/api/edit/mood_psychological_assessment', file: './routes/edit/mood_psychological_assessment' },
            { path: '/api/edit/motor_complications', file: './routes/edit/motor_complications' },
            { path: '/api/edit/movement_disorder_assessment', file: './routes/edit/movement_disorder_assessment' },
            { path: '/api/edit/mri_reports', file: './routes/edit/mri_reports' },
            { path: '/api/edit/multimodal_pain_therapy', file: './routes/edit/multimodal_pain_therapy' },
            { path: '/api/edit/multiple_sclerosis_assessment', file: './routes/edit/multiple_sclerosis_assessment' },
            { path: '/api/edit/myeloma_specific_data', file: './routes/edit/myeloma_specific_data' },
            { path: '/api/edit/narcolepsy_assessment', file: './routes/edit/narcolepsy_assessment' },
            { path: '/api/edit/nephrology_consultation_details', file: './routes/edit/nephrology_consultation_details' },
            { path: '/api/edit/nephrology_consultations', file: './routes/edit/nephrology_consultations' },
            { path: '/api/edit/neuro_imaging', file: './routes/edit/neuro_imaging' },
            { path: '/api/edit/neurological_assessment', file: './routes/edit/neurological_assessment' },
            { path: '/api/edit/neurological_exam', file: './routes/edit/neurological_exam' },
            { path: '/api/edit/neurological_examination', file: './routes/edit/neurological_examination' },
            { path: '/api/edit/neurological_findings', file: './routes/edit/neurological_findings' },
            { path: '/api/edit/neurology_consultations', file: './routes/edit/neurology_consultations' },
            { path: '/api/edit/neurology_progress_notes', file: './routes/edit/neurology_progress_notes' },
            { path: '/api/edit/neuromuscular_disorder', file: './routes/edit/neuromuscular_disorder' },
            { path: '/api/edit/neuropsychological_assessments', file: './routes/edit/neuropsychological_assessments' },
            { path: '/api/edit/neurosurgery_assessment', file: './routes/edit/neurosurgery_assessment' },
            { path: '/api/edit/neurosurgery_consultations', file: './routes/edit/neurosurgery_consultations' },
            { path: '/api/edit/neurovascular_exam', file: './routes/edit/neurovascular_exam' },
            { path: '/api/edit/newborn_screening_results', file: './routes/edit/newborn_screening_results' },
            { path: '/api/edit/nicu_progress_notes', file: './routes/edit/nicu_progress_notes' },
            { path: '/api/edit/non_motor_symptoms', file: './routes/edit/non_motor_symptoms' },
            { path: '/api/edit/nuclear_medicine_assessment', file: './routes/edit/nuclear_medicine_assessment' },
            { path: '/api/edit/nuclear_medicine_studies', file: './routes/edit/nuclear_medicine_studies' },
            { path: '/api/edit/nursing_assessments', file: './routes/edit/nursing_assessments' },
            { path: '/api/edit/nursing_notes', file: './routes/edit/nursing_notes' },
            { path: '/api/edit/nurse_signatures', file: './routes/edit/nurse_signatures' },
            { path: '/api/edit/nutrition_assessments', file: './routes/edit/nutrition_assessments' },
            { path: '/api/edit/nutritional_assessment', file: './routes/edit/nutritional_assessment' },
            { path: '/api/edit/nutritional_supplementation', file: './routes/edit/nutritional_supplementation' },
            { path: '/api/edit/nutritional_support', file: './routes/edit/nutritional_support' },
            { path: '/api/edit/nutrition_support_consultation', file: './routes/edit/nutrition_support_consultation' },
            { path: '/api/edit/obstetric_history', file: './routes/edit/obstetric_history' },
            { path: '/api/edit/occupational_health_assessment', file: './routes/edit/occupational_health_assessment' },
            { path: '/api/edit/occupational_medicine_evaluations', file: './routes/edit/occupational_medicine_evaluations' },
            { path: '/api/edit/occupational_therapy_reports', file: './routes/edit/occupational_therapy_reports' },
            { path: '/api/edit/oncology_consultations', file: './routes/edit/oncology_consultations' },
            { path: '/api/edit/oncology_followup_reports', file: './routes/edit/oncology_followup_reports' },
            { path: '/api/edit/oncology_team', file: './routes/edit/oncology_team' },
            { path: '/api/edit/oncology_treatment_plans', file: './routes/edit/oncology_treatment_plans' },
            { path: '/api/edit/omissions_refusals', file: './routes/edit/omissions_refusals' },
            { path: '/api/edit/operative_details', file: './routes/edit/operative_details' },
            { path: '/api/edit/operative_report_details', file: './routes/edit/operative_report_details' },
            { path: '/api/edit/operative_reports', file: './routes/edit/operative_reports' },
            { path: '/api/edit/operative_technique', file: './routes/edit/operative_technique' },
            { path: '/api/edit/ophthalmology_exam', file: './routes/edit/ophthalmology_exam' },
            { path: '/api/edit/ophthalmology_examinations', file: './routes/edit/ophthalmology_examinations' },
            { path: '/api/edit/optometry_examination', file: './routes/edit/optometry_examination' },
            { path: '/api/edit/opioid_risk_assessment', file: './routes/edit/opioid_risk_assessment' },
            { path: '/api/edit/opportunistic_infections', file: './routes/edit/opportunistic_infections' },
            { path: '/api/edit/oral_pathology_biopsy', file: './routes/edit/oral_pathology_biopsy' },
            { path: '/api/edit/oral_surgery_reports', file: './routes/edit/oral_surgery_reports' },
            { path: '/api/edit/oxygen_titration_protocol', file: './routes/edit/oxygen_titration_protocol' },
            { path: '/api/edit/orthodontic_treatment_plans', file: './routes/edit/orthodontic_treatment_plans' },
            { path: '/api/edit/orthognathic_surgery_evaluation', file: './routes/edit/orthognathic_surgery_evaluation' },
            { path: '/api/edit/orthopedic_assessment', file: './routes/edit/orthopedic_assessment' },
            { path: '/api/edit/orthopedic_consultations', file: './routes/edit/orthopedic_consultations' },
            { path: '/api/edit/orthopedic_followup_notes', file: './routes/edit/orthopedic_followup_notes' },
            { path: '/api/edit/orthopedic_imaging', file: './routes/edit/orthopedic_imaging' },
            { path: '/api/edit/overtraining_assessment', file: './routes/edit/overtraining_assessment' },
            { path: '/api/edit/orthopedic_operative_reports', file: './routes/edit/orthopedic_operative_reports' },
            { path: '/api/edit/orthopedic_procedures', file: './routes/edit/orthopedic_procedures' },
            { path: '/api/edit/outcomes_predictions', file: './routes/edit/outcomes_predictions' },
            { path: '/api/edit/outcomes_predictions_smart', file: './routes/edit/outcomes_predictions_smart' },
            { path: '/api/edit/psc_management', file: './routes/edit/psc_management' },
            { path: '/api/edit/pain_assessment_forms', file: './routes/edit/pain_assessment_forms' },
            { path: '/api/edit/pain_management_notes', file: './routes/edit/pain_management_notes' },
            { path: '/api/edit/medication_dosing_recommendation', file: './routes/edit/medication_dosing_recommendation' },
            { path: '/api/edit/pharmacogenomic_testing', file: './routes/edit/pharmacogenomic_testing' },
            { path: '/api/edit/malnutrition_risk_assessment', file: './routes/edit/malnutrition_risk_assessment' },
            { path: '/api/edit/pain_medication_agreements', file: './routes/edit/pain_medication_agreements' },
            { path: '/api/edit/pain_functional_assessment', file: './routes/edit/pain_functional_assessment' },
            { path: '/api/edit/pain_management_plan', file: './routes/edit/pain_management_plan' },
            { path: '/api/edit/palliative_care_needs', file: './routes/edit/palliative_care_needs' },
            { path: '/api/edit/parental_concerns', file: './routes/edit/parental_concerns' },
            { path: '/api/edit/parenteral_nutrition_monitoring', file: './routes/edit/parenteral_nutrition_monitoring' },
            { path: '/api/edit/nutrition_lab_monitoring', file: './routes/edit/nutrition_lab_monitoring' },
            { path: '/api/edit/parkinson_medications', file: './routes/edit/parkinson_medications' },
            { path: '/api/edit/parkinsonian_features', file: './routes/edit/parkinsonian_features' },
            { path: '/api/edit/partner_involvement_diabetes_management', file: './routes/edit/partner_involvement_diabetes_management' },
            { path: '/api/edit/past_ocular_history', file: './routes/edit/past_ocular_history' },
            { path: '/api/edit/pathology_gross_description', file: './routes/edit/pathology_gross_description' },
            { path: '/api/edit/patient_advocacy_support', file: './routes/edit/patient_advocacy_support' },
            { path: '/api/edit/patient_barriers_assessment', file: './routes/edit/patient_barriers_assessment' },
            { path: '/api/edit/patient_compliance_tracking', file: './routes/edit/patient_compliance_tracking' },
            { path: '/api/edit/patient_education_diabetes', file: './routes/edit/patient_education_diabetes' },
            { path: '/api/edit/patient_engagement_metrics', file: './routes/edit/patient_engagement_metrics' },
            { path: '/api/edit/patient_goal_setting', file: './routes/edit/patient_goal_setting' },
            { path: '/api/edit/patient_portal_security', file: './routes/edit/patient_portal_security' },
            { path: '/api/edit/patient_reported_measures', file: './routes/edit/patient_reported_measures' },
            { path: '/api/edit/patient_safety_screening', file: './routes/edit/patient_safety_screening' },
            { path: '/api/edit/pediatric_dental', file: './routes/edit/pediatric_dental' },
            { path: '/api/edit/pediatric_growth_charts', file: './routes/edit/pediatric_growth_charts' },
            { path: '/api/edit/pediatric_screening', file: './routes/edit/pediatric_screening' },
            { path: '/api/edit/pediatric_vaccination_records', file: './routes/edit/pediatric_vaccination_records' },
            { path: '/api/edit/pediatric_visits', file: './routes/edit/pediatric_visits' },
            { path: '/api/edit/performance_status', file: './routes/edit/performance_status' },
            { path: '/api/edit/periodontal_charts', file: './routes/edit/periodontal_charts' },
            { path: '/api/edit/peripheral_artery_disease', file: './routes/edit/peripheral_artery_disease' },
            { path: '/api/edit/integrative_oncology', file: './routes/edit/integrative_oncology' },
            { path: '/api/edit/peripheral_neuropathy', file: './routes/edit/peripheral_neuropathy' },
            { path: '/api/edit/pet_scan_reports', file: './routes/edit/pet_scan_reports' },
            { path: '/api/edit/pharmacist_consultation', file: './routes/edit/pharmacist_consultation' },
            { path: '/api/edit/physical_therapy_evaluations', file: './routes/edit/physical_therapy_evaluations' },
            { path: '/api/edit/physical_therapy_notes', file: './routes/edit/physical_therapy_notes' },
            { path: '/api/edit/falls_prevention_program_assessment', file: './routes/edit/falls_prevention_program_assessment' },
            { path: '/api/edit/pharmacy_review', file: './routes/edit/pharmacy_review' },
            { path: '/api/edit/plastic_surgery_assessment', file: './routes/edit/plastic_surgery_assessment' },
            { path: '/api/edit/plastic_surgery_consultations', file: './routes/edit/plastic_surgery_consultations' },
            { path: '/api/edit/poison_control_reports', file: './routes/edit/poison_control_reports' },
            { path: '/api/edit/pmr_assessment', file: './routes/edit/pmr_assessment' },
            { path: '/api/edit/pneumoperitoneum', file: './routes/edit/pneumoperitoneum' },
            { path: '/api/edit/polypharmacy_reviews', file: './routes/edit/polypharmacy_reviews' },
            { path: '/api/edit/post_dialysis_assessment', file: './routes/edit/post_dialysis_assessment' },
            { path: '/api/edit/post_operative_reports', file: './routes/edit/post_operative_reports' },
            { path: '/api/edit/postoperative_condition', file: './routes/edit/postoperative_condition' },
            { path: '/api/edit/postoperative_orders', file: './routes/edit/postoperative_orders' },
            { path: '/api/edit/postoperative_pain_management', file: './routes/edit/postoperative_pain_management' },
            { path: '/api/edit/postpartum_notes', file: './routes/edit/postpartum_notes' },
            { path: '/api/edit/postpartum_planning', file: './routes/edit/postpartum_planning' },
            { path: '/api/edit/potential_testing_outcomes', file: './routes/edit/potential_testing_outcomes' },
            { path: '/api/edit/pre_dialysis_assessment', file: './routes/edit/pre_dialysis_assessment' },
            { path: '/api/edit/pre_operative_assessments', file: './routes/edit/pre_operative_assessments' },
            { path: '/api/edit/preconception_counseling', file: './routes/edit/preconception_counseling' },
            { path: '/api/edit/pregnancy_course', file: './routes/edit/pregnancy_course' },
            { path: '/api/edit/pregnancy_risk_assessment', file: './routes/edit/pregnancy_risk_assessment' },
            { path: '/api/edit/pregnancy_symptoms', file: './routes/edit/pregnancy_symptoms' },
            { path: '/api/edit/prenatal_education', file: './routes/edit/prenatal_education' },
            { path: '/api/edit/prenatal_screening', file: './routes/edit/prenatal_screening' },
            { path: '/api/edit/prenatal_visits', file: './routes/edit/prenatal_visits' },
            { path: '/api/edit/preoperative_evaluation', file: './routes/edit/preoperative_evaluation' },
            { path: '/api/edit/preoperative_preparation', file: './routes/edit/preoperative_preparation' },
            { path: '/api/edit/prep_and_drape', file: './routes/edit/prep_and_drape' },
            { path: '/api/edit/prescriptions', file: './routes/edit/prescriptions' },
            { path: '/api/edit/pressure_injury', file: './routes/edit/pressure_injury' },
            { path: '/api/edit/preventive_biomarkers', file: './routes/edit/preventive_biomarkers' },
            { path: '/api/edit/preventive_care', file: './routes/edit/preventive_care' },
            { path: '/api/edit/preventive_medicine_assessments', file: './routes/edit/preventive_medicine_assessments' },
            { path: '/api/edit/primary_prophylaxis', file: './routes/edit/primary_prophylaxis' },
            { path: '/api/edit/prior_authorization_forms', file: './routes/edit/prior_authorization_forms' },
            { path: '/api/edit/prior_authorization_status', file: './routes/edit/prior_authorization_status' },
            { path: '/api/edit/prn_medications', file: './routes/edit/prn_medications' },
            { path: '/api/edit/procedures_interventions', file: './routes/edit/procedures_interventions' },
            { path: '/api/edit/prognosis_discussion', file: './routes/edit/prognosis_discussion' },
            { path: '/api/edit/prognosis_records', file: './routes/edit/prognosis_records' },
            { path: '/api/edit/prognostic_factors', file: './routes/edit/prognostic_factors' },
            { path: '/api/edit/progress_notes', file: './routes/edit/progress_notes' },
            { path: '/api/edit/prophylactic_medications', file: './routes/edit/prophylactic_medications' },
            { path: '/api/edit/proposed_art_switch', file: './routes/edit/proposed_art_switch' },
            { path: '/api/edit/proteinuria_assessment', file: './routes/edit/proteinuria_assessment' },
            { path: '/api/edit/provider_info', file: './routes/edit/provider_info' },
            { path: '/api/edit/psychiatric_evaluation', file: './routes/edit/psychiatric_evaluation' },
            { path: '/api/edit/psychiatric_evaluations', file: './routes/edit/psychiatric_evaluations' },
            { path: '/api/edit/psychiatric_history', file: './routes/edit/psychiatric_history' },
            { path: '/api/edit/psychiatric_treatment_plan', file: './routes/edit/psychiatric_treatment_plan' },
            { path: '/api/edit/psychosocial_assessments', file: './routes/edit/psychosocial_assessments' },
            { path: '/api/edit/psychosocial_factors', file: './routes/edit/psychosocial_factors' },
            { path: '/api/edit/psychosocial_oncology', file: './routes/edit/psychosocial_oncology' },
            { path: '/api/edit/psychosocial_support_services', file: './routes/edit/psychosocial_support_services' },
            { path: '/api/edit/psychotropic_medications', file: './routes/edit/psychotropic_medications' },
            { path: '/api/edit/pulmonary_function_tests', file: './routes/edit/pulmonary_function_tests' },
            { path: '/api/edit/pulmonary_rehabilitation_notes', file: './routes/edit/pulmonary_rehabilitation_notes' },
            { path: '/api/edit/pulmonology_consultations', file: './routes/edit/pulmonology_consultations' },
            { path: '/api/edit/pump_download_analysis', file: './routes/edit/pump_download_analysis' },
            { path: '/api/edit/quality_assurance', file: './routes/edit/quality_assurance' },
            { path: '/api/edit/quality_metrics', file: './routes/edit/quality_metrics' },
            { path: '/api/edit/radiation_oncology', file: './routes/edit/radiation_oncology' },
            { path: '/api/edit/radiation_therapy', file: './routes/edit/radiation_therapy' },
            { path: '/api/edit/radiation_therapy_records', file: './routes/edit/radiation_therapy_records' },
            { path: '/api/edit/radiology_findings', file: './routes/edit/radiology_findings' },
            { path: '/api/edit/radiology_reports', file: './routes/edit/radiology_reports' },
            { path: '/api/edit/rapid_response_summaries', file: './routes/edit/rapid_response_summaries' },
            { path: '/api/edit/reason_for_referral', file: './routes/edit/reason_for_referral' },
            { path: '/api/edit/procedural_sedation', file: './routes/edit/procedural_sedation' },
            { path: '/api/edit/recommendations', file: './routes/edit/recommendations' },
            { path: '/api/edit/referrals_placed', file: './routes/edit/referrals_placed' },
            { path: '/api/edit/regional_anesthesia', file: './routes/edit/regional_anesthesia' },
            { path: '/api/edit/rehabilitation_goals', file: './routes/edit/rehabilitation_goals' },
            { path: '/api/edit/rehabilitation_progress_notes', file: './routes/edit/rehabilitation_progress_notes' },
            { path: '/api/edit/rehabilitation_protocol', file: './routes/edit/rehabilitation_protocol' },
            { path: '/api/edit/reminders', file: './routes/edit/reminders' },
            { path: '/api/edit/renal_anemia', file: './routes/edit/renal_anemia' },
            { path: '/api/edit/renal_nutrition', file: './routes/edit/renal_nutrition' },
            { path: '/api/edit/renal_protection_plan', file: './routes/edit/renal_protection_plan' },
            { path: '/api/edit/reproductive_history', file: './routes/edit/reproductive_history' },
            { path: '/api/edit/fertility_tracking', file: './routes/edit/fertility_tracking' },
            { path: '/api/edit/single_embryo_transfer', file: './routes/edit/single_embryo_transfer' },
            { path: '/api/edit/single_embryo_transfer_details', file: './routes/edit/single_embryo_transfer_details' },
            { path: '/api/edit/ivf_cycle_monitoring', file: './routes/edit/ivf_cycle_monitoring' },
            { path: '/api/edit/egg_retrieval_procedure', file: './routes/edit/egg_retrieval_procedure' },
            { path: '/api/edit/embryo_transfer_procedure', file: './routes/edit/embryo_transfer_procedure' },
            { path: '/api/edit/sperm_analysis', file: './routes/edit/sperm_analysis' },
            { path: '/api/edit/intrauterine_insemination', file: './routes/edit/intrauterine_insemination' },
            { path: '/api/edit/surrogacy_evaluation', file: './routes/edit/surrogacy_evaluation' },
            { path: '/api/edit/ovarian_stimulation_protocol', file: './routes/edit/ovarian_stimulation_protocol' },
            { path: '/api/edit/fertility_medication_management', file: './routes/edit/fertility_medication_management' },
            { path: '/api/edit/rescue_therapy_options', file: './routes/edit/rescue_therapy_options' },
            { path: '/api/edit/research_consent_forms', file: './routes/edit/research_consent_forms' },
            { path: '/api/edit/respiratory_devices', file: './routes/edit/respiratory_devices' },
            { path: '/api/edit/respite_care', file: './routes/edit/respite_care' },
            { path: '/api/edit/response_assessment', file: './routes/edit/response_assessment' },
            { path: '/api/edit/resuscitation_records', file: './routes/edit/resuscitation_records' },
            { path: '/api/edit/retinal_examinations', file: './routes/edit/retinal_examinations' },
            { path: '/api/edit/return_to_play_protocol', file: './routes/edit/return_to_play_protocol' },
            { path: '/api/edit/return_to_sport', file: './routes/edit/return_to_sport' },
            { path: '/api/edit/return_to_work_plan', file: './routes/edit/return_to_work_plan' },
            { path: '/api/edit/rheumatologic_treatment', file: './routes/edit/rheumatologic_treatment' },
            { path: '/api/edit/rheumatologic_assessment', file: './routes/edit/rheumatologic_assessment' },
            { path: '/api/edit/rheumatologic_monitoring', file: './routes/edit/rheumatologic_monitoring' },
            { path: '/api/edit/rheumatology_consultations', file: './routes/edit/rheumatology_consultations' },
            { path: '/api/edit/risk_calculators', file: './routes/edit/risk_calculators' },
            { path: '/api/edit/risk_counseling', file: './routes/edit/risk_counseling' },
            { path: '/api/edit/risk_factors', file: './routes/edit/risk_factors' },
            { path: '/api/edit/safety_planning', file: './routes/edit/safety_planning' },
            { path: '/api/edit/school_health_forms', file: './routes/edit/school_health_forms' },
            { path: '/api/edit/school_performance', file: './routes/edit/school_performance' },
            { path: '/api/edit/scheduled_medications', file: './routes/edit/scheduled_medications' },
            { path: '/api/edit/scleroderma_assessment', file: './routes/edit/scleroderma_assessment' },
            { path: '/api/edit/screening_compliance', file: './routes/edit/screening_compliance' },
            { path: '/api/edit/secondary_prophylaxis', file: './routes/edit/secondary_prophylaxis' },
            { path: '/api/edit/sedation_records', file: './routes/edit/sedation_records' },
            { path: '/api/edit/sepsis_management', file: './routes/edit/sepsis_management' },
            { path: '/api/edit/sjogrens_syndrome_assessment', file: './routes/edit/sjogrens_syndrome_assessment' },
            { path: '/api/edit/skin_biopsy_reports', file: './routes/edit/skin_biopsy_reports' },
            { path: '/api/edit/skin_grafting_evaluation', file: './routes/edit/skin_grafting_evaluation' },
            { path: '/api/edit/sleep_apnea_management', file: './routes/edit/sleep_apnea_management' },
            { path: '/api/edit/sleep_disorder_assessment', file: './routes/edit/sleep_disorder_assessment' },
            { path: '/api/edit/sleep_disturbances', file: './routes/edit/sleep_disturbances' },
            { path: '/api/edit/sleep_hygiene_education', file: './routes/edit/sleep_hygiene_education' },
            { path: '/api/edit/sleep_study_reports', file: './routes/edit/sleep_study_reports' },
            { path: '/api/edit/smoking_cessation_program', file: './routes/edit/smoking_cessation_program' },
            { path: '/api/edit/social_support', file: './routes/edit/social_support' },
            { path: '/api/edit/social_work', file: './routes/edit/social_work' },
            { path: '/api/edit/social_work_notes', file: './routes/edit/social_work_notes' },
            { path: '/api/edit/soap_notes', file: './routes/edit/soap_notes' },
            { path: '/api/edit/south_asian_nutritionist', file: './routes/edit/south_asian_nutritionist' },
            { path: '/api/edit/specific_ige_testing', file: './routes/edit/specific_ige_testing' },
            { path: '/api/edit/specific_ige_tests', file: './routes/edit/specific_ige_tests' },
            { path: '/api/edit/specimens', file: './routes/edit/specimens' },
            { path: '/api/edit/speech_therapy_assessments', file: './routes/edit/speech_therapy_assessments' },
            { path: '/api/edit/spinal_manipulation_record', file: './routes/edit/spinal_manipulation_record' },
            { path: '/api/edit/spondyloarthritis_assessment', file: './routes/edit/spondyloarthritis_assessment' },
            { path: '/api/edit/sports_medicine_evaluations', file: './routes/edit/sports_medicine_evaluations' },
            { path: '/api/edit/sports_nutrition_plan', file: './routes/edit/sports_nutrition_plan' },
            { path: '/api/edit/sports_physical_examination', file: './routes/edit/sports_physical_examination' },
            { path: '/api/edit/staging_summary', file: './routes/edit/staging_summary' },
            { path: '/api/edit/stress_test_reports', file: './routes/edit/stress_test_reports' },
            { path: '/api/edit/stroke_assessment', file: './routes/edit/stroke_assessment' },
            { path: '/api/edit/suicide_risk_assessment', file: './routes/edit/suicide_risk_assessment' },
            { path: '/api/edit/supplementation_plans', file: './routes/edit/supplementation_plans' },
            { path: '/api/edit/supportive_care', file: './routes/edit/supportive_care' },
            { path: '/api/edit/surgical_approach', file: './routes/edit/surgical_approach' },
            { path: '/api/edit/sponge_instrument_counts', file: './routes/edit/sponge_instrument_counts' },
            { path: '/api/edit/surgical_consent_forms', file: './routes/edit/surgical_consent_forms' },
            { path: '/api/edit/surgical_history', file: './routes/edit/surgical_history' },
            { path: '/api/edit/surgical_oncology', file: './routes/edit/surgical_oncology' },
            { path: '/api/edit/surgical_steps', file: './routes/edit/surgical_steps' },
            { path: '/api/edit/surgical_team', file: './routes/edit/surgical_team' },
            { path: '/api/edit/survivorship_care_plan', file: './routes/edit/survivorship_care_plan' },
            { path: '/api/edit/symptom_progression', file: './routes/edit/symptom_progression' },
            { path: '/api/edit/symptom_progression_timeline', file: './routes/edit/symptom_progression_timeline' },
            { path: '/api/edit/table', file: './routes/edit/table' },
            { path: '/api/edit/telemedicine_encounters', file: './routes/edit/telemedicine_encounters' },
            { path: '/api/edit/thoracic_surgery_assessment', file: './routes/edit/thoracic_surgery_assessment' },
            { path: '/api/edit/thyroid_evaluations', file: './routes/edit/thyroid_evaluations' },
            { path: '/api/edit/thyroid_management', file: './routes/edit/thyroid_management' },
            { path: '/api/edit/tmj_assessment', file: './routes/edit/tmj_assessment' },
            { path: '/api/edit/tourniquet_data', file: './routes/edit/tourniquet_data' },
            { path: '/api/edit/tpn_management', file: './routes/edit/tpn_management' },
            { path: '/api/edit/toxicology_reports', file: './routes/edit/toxicology_reports' },
            { path: '/api/edit/tractography_studies', file: './routes/edit/tractography_studies' },
            { path: '/api/edit/transplant_assessment', file: './routes/edit/transplant_assessment' },
            { path: '/api/edit/transplant_evaluations', file: './routes/edit/transplant_evaluations' },
            { path: '/api/edit/treatment_goals', file: './routes/edit/treatment_goals' },
            { path: '/api/edit/treatment_summary', file: './routes/edit/treatment_summary' },
            { path: '/api/edit/trending_analysis', file: './routes/edit/trending_analysis' },
            { path: '/api/edit/triage_data', file: './routes/edit/triage_data' },
            { path: '/api/edit/tropical_disease_assessment', file: './routes/edit/tropical_disease_assessment' },
            { path: '/api/edit/tube_feeding_order', file: './routes/edit/tube_feeding_order' },
            { path: '/api/edit/tumor_board_notes', file: './routes/edit/tumor_board_notes' },
            { path: '/api/edit/tumor_marker_panels', file: './routes/edit/tumor_marker_panels' },
            { path: '/api/edit/tumor_markers', file: './routes/edit/tumor_markers' },
            { path: '/api/edit/urodynamic_studies', file: './routes/edit/urodynamic_studies' },
            { path: '/api/edit/urology_consultations', file: './routes/edit/urology_consultations' },
            { path: '/api/edit/vaccination_records', file: './routes/edit/vaccination_records' },
            { path: '/api/edit/vasculitis_assessment', file: './routes/edit/vasculitis_assessment' },
            { path: '/api/edit/variant_interpretation_guidelines', file: './routes/edit/variant_interpretation_guidelines' },
            { path: '/api/edit/ventilator_settings', file: './routes/edit/ventilator_settings' },
            { path: '/api/edit/visual_acuity_reports', file: './routes/edit/visual_acuity_reports' },
            { path: '/api/edit/vision_therapy_assessment', file: './routes/edit/vision_therapy_assessment' },
            { path: '/api/edit/vital_signs', file: './routes/edit/vital_signs' },
            { path: '/api/edit/vital_signs_table', file: './routes/edit/vital_signs_table' },
            { path: '/api/edit/vital_signs_logs', file: './routes/edit/vital_signs_logs' },
            { path: '/api/edit/weight_measurements', file: './routes/edit/weight_measurements' },
            { path: '/api/edit/weight_monitoring', file: './routes/edit/weight_monitoring' },
            { path: '/api/edit/weekly_virtual_check_ins', file: './routes/edit/weekly_virtual_check_ins' },
            { path: '/api/edit/well_child_examinations', file: './routes/edit/well_child_examinations' },
            { path: '/api/edit/well_child_summary', file: './routes/edit/well_child_summary' },
            { path: '/api/edit/work_accommodations', file: './routes/edit/work_accommodations' },
            { path: '/api/edit/workplace_accommodations', file: './routes/edit/workplace_accommodations' },
            { path: '/api/edit/work_restrictions', file: './routes/edit/work_restrictions' },
            { path: '/api/edit/workers_compensation_evaluation', file: './routes/edit/workers_compensation_evaluation' },
            { path: '/api/edit/workplace_injury_report', file: './routes/edit/workplace_injury_report' },
            { path: '/api/edit/wound_care_assessments', file: './routes/edit/wound_care_assessments' },
            { path: '/api/edit/wound_care_documentation', file: './routes/edit/wound_care_documentation' },
            { path: '/api/edit/wound_care_notes', file: './routes/edit/wound_care_notes' },

            { path: '/api/edit/care_gaps', file: './routes/edit/care_gaps' },
            { path: '/api/edit/pathology_reports', file: './routes/edit/pathology_reports' },
            { path: '/api/edit/patient_care_goals', file: './routes/edit/patient_care_goals' },
            { path: '/api/edit/patient_care_plan', file: './routes/edit/patient_care_plan' },
            { path: '/api/edit/patient_details', file: './routes/edit/patient_details' },
            { path: '/api/edit/patient_education_context', file: './routes/edit/patient_education_context' },
            { path: '/api/edit/patient_instructions', file: './routes/edit/patient_instructions' },
            { path: '/api/edit/patient_positioning', file: './routes/edit/patient_positioning' },
            { path: '/api/edit/patient_specific_care_plan', file: './routes/edit/patient_specific_care_plan' },
            { path: '/api/edit/amniocentesis_reports', file: './routes/edit/amniocentesis_reports' },
            { path: '/api/edit/amniotic_fluid_assessment', file: './routes/edit/amniotic_fluid_assessment' },
            { path: '/api/edit/cervical_assessment', file: './routes/edit/cervical_assessment' },
            { path: '/api/edit/cervical_length_measurement', file: './routes/edit/cervical_length_measurement' },
            { path: '/api/edit/perinatal_mental_health_referral', file: './routes/edit/perinatal_mental_health_referral' },
            { path: '/api/edit/fetal_echo', file: './routes/edit/fetal_echo' },
            { path: '/api/edit/first_trimester_bleeding', file: './routes/edit/first_trimester_bleeding' },
            { path: '/api/edit/growth_ultrasound_schedule', file: './routes/edit/growth_ultrasound_schedule' },
            { path: '/api/edit/nt_scan_result', file: './routes/edit/nt_scan_result' },
            { path: '/api/edit/preeclampsia_monitoring', file: './routes/edit/preeclampsia_monitoring' },
            { path: '/api/edit/pregnancy_complications', file: './routes/edit/pregnancy_complications' },
            { path: '/api/edit/umbilical_artery_doppler', file: './routes/edit/umbilical_artery_doppler' },
            { path: '/api/edit/sti_screening_panel', file: './routes/edit/sti_screening_panel' },
            { path: '/api/edit/hiv_pep_prophylaxis', file: './routes/edit/hiv_pep_prophylaxis' },
            { path: '/api/edit/hiv_prep_management', file: './routes/edit/hiv_prep_management' },
            { path: '/api/edit/sexual_health_counseling', file: './routes/edit/sexual_health_counseling' },
            { path: '/api/edit/partner_notification', file: './routes/edit/partner_notification' },
            { path: '/api/edit/shift_handoff_notes', file: './routes/edit/shift_handoff_notes' },
            // ===== INFRASTRUCTURE (OPTIONAL - CAN BE REMOVED IF NOT USED) =====
            { path: '/api/cost-tracking', file: './routes/costTracking' },
            { path: '/api/cache-monitor', file: './routes/cacheMonitor' },

            // ===== REMOVED - NOW HANDLED BY CLAUDE FUNCTIONS =====
            // All medical CRUD operations go through /api/agent/chat → Claude → Functions
            // Deleted routes: patients, documents, prescriptions, referrals,
            // imaging, medical-data, deleted-patients, users, and 724 medical collection routes
        ];
    }

    /**
     * Load a single route safely
     */
    loadRoute(routeConfig) {
        const { path, file } = routeConfig;
        try {
            // Fix path - require from parent directory since we're in services/
            const routePath = file.replace('./routes/', '../routes/');
            const router = require(routePath);
            this.app.use(path, router);
            this.loadedRoutes.push({ path, file });
            console.log(`✓ Loaded route: ${path}`);
            return true;
        } catch (error) {
            this.failedRoutes.push({ path, file, error: error.message });
            console.error(`✗ Failed to load route ${path}: ${error.message}`);
            return false;
        }
    }

    /**
     * REMOVED: loadMedicalRoutes()
     * Medical routes directory deleted - all medical operations now go through
     * Claude functions via /api/agent/chat endpoint
     */

    /**
     * Load all routes
     */
    loadAllRoutes() {
        console.log('Loading API routes...');
        this.defineRoutes();
        // REMOVED: this.loadMedicalRoutes() - medical routes deleted

        for (const route of this.routes) {
            this.loadRoute(route);
        }

        console.log(`\n✅ Route loading complete: ${this.loadedRoutes.length} loaded, ${this.failedRoutes.length} failed`);
        console.log(`📊 Architecture: Frontend → /api/agent/chat → Claude Functions → Services → SecureDataAccess`);

        if (this.failedRoutes.length > 0) {
            console.error('❌ Failed routes:', this.failedRoutes.map(r => r.path));
        }

        return {
            loaded: this.loadedRoutes.length,
            failed: this.failedRoutes.length,
            failedRoutes: this.failedRoutes
        };
    }

    /**
     * Get route loading report
     */
    getReport() {
        return {
            total: this.routes.length,
            loaded: this.loadedRoutes.length,
            failed: this.failedRoutes.length,
            loadedRoutes: this.loadedRoutes.map(r => r.path),
            failedRoutes: this.failedRoutes
        };
    }
}

// Export singleton instance
module.exports = new RouteLoaderService();