import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';
import AdvanceDirectiveDiscussionDocumentPDFTemplate from '../pdf-templates/AdvanceDirectiveDiscussionDocumentPDFTemplate';
import BlueDatePicker from '../components/BlueDatePicker';
import BlueSelect from '../components/BlueSelect';
import secureApiClient from '../../../services/secureApiClient';
import './AdvanceDirectiveDiscussionDocument.css';

const DRAFT_KEY = 'advance_directive_discussionPendingEdits';
const readDrafts = () => { try { return JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}') || {}; } catch { return {}; } };
const writeDrafts = store => { try { if (store && Object.keys(store).length) localStorage.setItem(DRAFT_KEY, JSON.stringify(store)); else localStorage.removeItem(DRAFT_KEY); } catch { /* best effort */ } };
const SECTION_TITLES = { overview: 'Discussion Overview', topics: 'Topics Covered', preferences: 'Preferences & Proxy', documentation: 'Documentation & Understanding', followup: 'Follow-up & Notes' };
const FIELD_LABELS = { discussionDate: 'Discussion Date', participants: 'Participants', provider: 'Provider', facility: 'Facility', topicsCovered: 'Topics Covered', patientPreferences: 'Patient Preferences', codeStatus: 'Code Status', healthcareProxyIdentified: 'Healthcare Proxy Identified', documentationCompleted: 'Documentation Completed', patientUnderstanding: 'Patient Understanding', familyAgreement: 'Family Agreement', followUp: 'Follow-up', notes: 'Notes' };
const SECTION_FIELDS = { overview: ['discussionDate', 'participants', 'provider', 'facility'], topics: ['topicsCovered'], preferences: ['patientPreferences', 'codeStatus', 'healthcareProxyIdentified'], documentation: ['documentationCompleted', 'patientUnderstanding', 'familyAgreement'], followup: ['followUp', 'notes'] };
const BOOLEAN_FIELDS = new Set(); const NUMBER_FIELDS = new Set(); const DATE_FIELDS = new Set(['discussionDate']); const ARRAY_FIELDS = new Set(['participants', 'topicsCovered']); const OBJECT_ARRAY_FIELDS = new Set(); const OBJECT_FIELDS = new Set();
const COMMA_ARRAY_FIELDS = new Set(); const SENTENCE_STRING_FIELDS = new Set(['patientPreferences', 'documentationCompleted', 'patientUnderstanding', 'familyAgreement', 'notes']); const COMMA_STRING_FIELDS = new Set();
const COMMA_LABELED_ONLY_FIELDS = new Set();
const SENTENCE_OBJECT_PATHS = new Set(); const COMMA_OBJECT_PATHS = new Set();
const SCORE_RATIO_PATHS = new Set();
const ENUM_OPTIONS = {};
const hasVal = value => value !== null && value !== undefined && value !== '' && (!Array.isArray(value) || value.some(hasVal)) && (typeof value !== 'object' || Array.isArray(value) || Object.values(value).some(hasVal));
const safeId = record => !record?._id ? null : typeof record._id === 'string' ? record._id : record._id.$oid || String(record._id);
const humanize = key => String(key || '').replace(/_/g, ' ').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, char => char.toUpperCase());
const rawDateValue = value => value?.$date?.$numberLong ?? value?.$date ?? value?.$numberLong ?? value;
const normalizedDateValue = value => { const raw = rawDateValue(value); return typeof raw === 'string' && /^-?\d+$/.test(raw) ? Number(raw) : raw; };
const formatDate = value => { if (!value) return ''; try { const date = new Date(normalizedDateValue(value)); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }); } catch { return String(value); } };
const toInputDate = value => { if (!value) return ''; try { const date = new Date(normalizedDateValue(value)); return Number.isNaN(date.getTime()) ? '' : date.toISOString().slice(0, 10); } catch { return ''; } };
const splitScoreRatio = value => { const match = String(value || '').match(/^(\s*)(-?\d+(?:\.\d+)?)(\s*\/\s*(\d+(?:\.\d+)?)[\s\S]*)$/); if (!match) return null; const decimals = (match[2].split('.')[1] || '').length; return { prefix: match[1], number: match[2], suffix: match[3], denominator: Number(match[4]), step: decimals ? Number(`0.${'0'.repeat(decimals - 1)}1`) : 1 }; };
const parseLabel = value => { const text = String(value || ''), match = text.match(/^([^:]{1,60}):\s+(.+)$/); return match ? { label: match[1].trim(), content: match[2].trim() } : { label: '', content: text }; };
const splitByComma = value => { const rows = []; let current = '', depth = 0; for (const char of String(value || '')) { if (char === '(') depth += 1; if (char === ')') depth = Math.max(0, depth - 1); if (char === ',' && depth === 0) { if (current.trim()) rows.push(current.trim()); current = ''; } else current += char; } if (current.trim()) rows.push(current.trim()); return rows; };
const splitBySentenceParts = value => { const text = String(value || ''), rows = []; let start = 0; for (const match of text.matchAll(/;\s+|\.(?!\d)(?:\s+|$)/g)) { const row = text.slice(start, match.index).trim(); if (row && !/^[;.,!?]+$/.test(row)) rows.push({ value: row, delimiter: match[0].trim().charAt(0) }); start = match.index + match[0].length; } const tail = text.slice(start).trim(); if (tail && !/^[;.,!?]+$/.test(tail)) rows.push({ value: tail, delimiter: '' }); return rows.length ? rows : [{ value: text.trim(), delimiter: '' }]; };
const splitBySentence = value => splitBySentenceParts(value).map(row => row.value);
const splitTextRows = (value, { sentences = false, commas = false, commasWhenLabeled = false } = {}) => { const parts = sentences ? splitBySentenceParts(value) : [{ value: String(value || '').trim(), delimiter: '' }]; return parts.flatMap((part, partIndex) => { const parsed = parseLabel(part.value), clauses = commas && (!commasWhenLabeled || parsed.label) ? splitByComma(parsed.content) : [parsed.content]; return clauses.filter(Boolean).map((clause, clauseIndex) => ({ subtitle: parsed.label, value: clause, textPart: partIndex, textClause: clauseIndex, textDelimiter: part.delimiter, textPrefix: parsed.label ? `${parsed.label}: ` : '', textStructured: true })); }); };
const rebuildTextRows = (entries, target, nextValue) => { const groups = []; entries.forEach(entry => { let group = groups.find(item => item.part === entry.textPart); if (!group) { group = { part: entry.textPart, prefix: entry.textPrefix || '', delimiter: entry.textDelimiter || '', clauses: [] }; groups.push(group); } group.clauses.push(entry === target ? String(nextValue).trim() : String(entry.value).trim()); }); return groups.sort((a, b) => a.part - b.part).map(group => `${group.prefix}${group.clauses.filter(Boolean).join(', ')}${group.delimiter}${group.delimiter ? ' ' : ''}`).join('').trim(); };
const splitString = (field, value) => splitTextRows(value, { sentences: SENTENCE_STRING_FIELDS.has(field), commas: COMMA_STRING_FIELDS.has(field), commasWhenLabeled: COMMA_LABELED_ONLY_FIELDS.has(field) });
const shouldSplitArrayItem = field => COMMA_ARRAY_FIELDS.has(field);
const cloneValue = value => value === undefined ? undefined : JSON.parse(JSON.stringify(value));
const setNested = (value, path, nextValue) => { const root = cloneValue(value) ?? (/^\d+$/.test(path[0]) ? [] : {}); let cursor = root; path.forEach((part, index) => { if (index === path.length - 1) cursor[part] = nextValue; else { if (cursor[part] === null || typeof cursor[part] !== 'object') cursor[part] = /^\d+$/.test(path[index + 1]) ? [] : {}; cursor = cursor[part]; } }); return root; };
const normalizeIndexedPath = path => path.replace(/\.\d+(?=\.|$)/g, '.*');
const pathIsDeclared = (set, path) => set.has(path) || set.has(normalizeIndexedPath(path));
const isDatePath = path => /date/i.test(String(path || '').split('.').pop());
const isNumericString = value => typeof value === 'string' && /^-?\d+(?:\.\d+)?$/.test(value.trim());
const isDateObject = value => value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === 1 && Object.hasOwn(value, '$date');
const OBJECT_ARRAY_ITEM_LABELS = {};
const flattenObject = (value, prefix = '', labelPrefix = '') => {
  if (Array.isArray(value)) return value.flatMap((child, index) => {
    const path = prefix ? `${prefix}.${index}` : String(index), label = `${labelPrefix || 'Item'} ${index + 1}`;
    return child && typeof child === 'object' && !isDateObject(child) ? flattenObject(child, path, label) : hasVal(child) ? [{ path, label, value: child }] : [];
  });
  return Object.entries(value || {}).flatMap(([key, child]) => {
    const path = prefix ? `${prefix}.${key}` : key, label = labelPrefix ? `${labelPrefix} — ${humanize(key)}` : humanize(key);
    return child && typeof child === 'object' && !isDateObject(child) ? flattenObject(child, path, label) : hasVal(child) ? [{ path, label, value: child }] : [];
  });
};
const groupRecommendations = value => {
  const groups = [];
  (Array.isArray(value) ? value : []).forEach((item, itemIndex) => {
    if (!hasVal(item)) return;
    const dateValue = item && typeof item === 'object' ? item.date : null;
    const dateKey = dateValue ? toInputDate(dateValue) : 'no-date';
    let group = groups.find(candidate => candidate.dateKey === dateKey);
    if (!group) { group = { dateKey, dateValue, items: [] }; groups.push(group); }
    group.items.push({ item, itemIndex });
  });
  return groups;
};

const AdvanceDirectiveDiscussionDocument = ({ document: documentProp, data: dataProp, templateData }) => {
  const [searchTerm, setSearchTerm] = useState(''); const [copiedSection, setCopiedSection] = useState(null); const [copiedItems, setCopiedItems] = useState({}); const [showCopied, setShowCopied] = useState(false); const [localEdits, setLocalEdits] = useState({}); const [pendingEdits, setPendingEdits] = useState({}); const [editedFields, setEditedFields] = useState({}); const [editingField, setEditingField] = useState(null); const [editValue, setEditValue] = useState(''); const [approvedSections, setApprovedSections] = useState({}); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState(null); const containerRef = useRef(null);
  const records = useMemo(() => { const source = documentProp ?? dataProp ?? templateData; if (!source) return []; let rows = Array.isArray(source) ? source : [source]; rows = rows.flatMap(row => { if (Array.isArray(row?.records)) return row.records; if (Array.isArray(row?._records)) return row._records; if (row?.advance_directive_discussion) return Array.isArray(row.advance_directive_discussion) ? row.advance_directive_discussion : [row.advance_directive_discussion]; if (row?.documentData) { const nested = row.documentData; if (Array.isArray(nested)) return nested; if (nested?.advance_directive_discussion) return Array.isArray(nested.advance_directive_discussion) ? nested.advance_directive_discussion : [nested.advance_directive_discussion]; return [nested]; } return [row]; }); return rows.filter(row => row && typeof row === 'object'); }, [documentProp, dataProp, templateData]);
  const getValue = useCallback((record, field, index) => localEdits[`${field}-${index}`] !== undefined ? localEdits[`${field}-${index}`] : record[field], [localEdits]);
  useEffect(() => { const store = readDrafts(), nextLocal = {}, nextPending = {}, nextEdited = {}; records.forEach((record, recordIndex) => { Object.entries(store[safeId(record)] || {}).forEach(([part, value]) => { const [field, ...path] = part.split('.'), key = `${field}-${recordIndex}`; nextLocal[key] = path.length ? setNested(nextLocal[key] ?? record[field], path, value) : value; nextPending[key] = true; nextEdited[`${part}-${recordIndex}`] = true; }); }); if (!Object.keys(nextPending).length) return; /* eslint-disable react-hooks/set-state-in-effect */ setLocalEdits(previous => ({ ...nextLocal, ...previous })); setPendingEdits(previous => ({ ...nextPending, ...previous })); setEditedFields(previous => ({ ...nextEdited, ...previous })); /* eslint-enable react-hooks/set-state-in-effect */ }, [records]);
  const stagePath = useCallback((record, field, part, recordIndex, section, value) => { const id = safeId(record); if (!id) return; const path = part.split('.').slice(1), key = `${field}-${recordIndex}`, nextRoot = path.length ? setNested(getValue(record, field, recordIndex), path, value) : value; setLocalEdits(previous => ({ ...previous, [key]: nextRoot })); setPendingEdits(previous => ({ ...previous, [key]: true })); setEditedFields(previous => ({ ...previous, [`${part}-${recordIndex}`]: true })); setApprovedSections(previous => { const approvalKey = `${section}-${recordIndex}`; if (!previous[approvalKey]) return previous; const next = { ...previous }; delete next[approvalKey]; return next; }); const store = readDrafts(); store[id] = { ...(store[id] || {}), [part]: value }; writeDrafts(store); setEditingField(null); setEditValue(''); }, [getValue]);
  const stageRecommendationDates = useCallback((record, recordIndex, section, itemIndexes, value) => { const id = safeId(record); if (!id) return; const key = `recommendations-${recordIndex}`, next = cloneValue(getValue(record, 'recommendations', recordIndex)) || []; itemIndexes.forEach(itemIndex => { next[itemIndex] = { ...(next[itemIndex] || {}), date: value }; }); setLocalEdits(previous => ({ ...previous, [key]: next })); setPendingEdits(previous => ({ ...previous, [key]: true })); setEditedFields(previous => { const updated = { ...previous }; itemIndexes.forEach(itemIndex => { updated[`recommendations.${itemIndex}.date-${recordIndex}`] = true; }); return updated; }); setApprovedSections(previous => { const approvalKey = `${section}-${recordIndex}`; if (!previous[approvalKey]) return previous; const updated = { ...previous }; delete updated[approvalKey]; return updated; }); const store = readDrafts(); const drafts = { ...(store[id] || {}) }; itemIndexes.forEach(itemIndex => { drafts[`recommendations.${itemIndex}.date`] = value; }); store[id] = drafts; writeDrafts(store); setEditingField(null); setEditValue(''); setSaveError(null); }, [getValue]);
  const sectionHasEdits = useCallback((section, index) => SECTION_FIELDS[section].some(field => pendingEdits[`${field}-${index}`]), [pendingEdits]);
  const approve = useCallback(async (record, section, index) => { const id = safeId(record); if (!id) return; setSaving(true); setSaveError(null); try { const store = readDrafts(), drafts = store[id] || {}, committed = []; for (const [part, value] of Object.entries(drafts)) { if (!SECTION_FIELDS[section].includes(part.split('.')[0])) continue; const response = await secureApiClient.put(`/api/edit/advance_directive_discussion/${id}/edit`, { field: part, value }); if (response?.success === false) throw new Error(response.error || 'Save failed'); committed.push(part); } await secureApiClient.put(`/api/edit/advance_directive_discussion/${id}/approve`, { sectionId: section, approved: true }); setPendingEdits(previous => { const next = { ...previous }; SECTION_FIELDS[section].forEach(field => delete next[`${field}-${index}`]); return next; }); committed.forEach(part => delete drafts[part]); if (Object.keys(drafts).length) store[id] = drafts; else delete store[id]; writeDrafts(store); setApprovedSections(previous => ({ ...previous, [`${section}-${index}`]: true })); } catch (error) { console.error(error); setSaveError('Approve failed. Please try again.'); } finally { setSaving(false); } }, []);
  const copyText = useCallback(async text => { try { await navigator.clipboard.writeText(text); return true; } catch { const area = window.document.createElement('textarea'); area.value = text; area.style.position = 'absolute'; area.style.left = '-9999px'; (containerRef.current || window.document.body).appendChild(area); area.select(); window.document.execCommand('copy'); area.remove(); return true; } }, []);
  const rowsFor = useCallback((field, value) => {
    if (DATE_FIELDS.has(field)) return [{ subtitle: '', value: formatDate(value), path: field, type: 'date', raw: value }];
    if (BOOLEAN_FIELDS.has(field)) return [{ subtitle: '', value: value ? 'Yes' : 'No', path: field, type: 'boolean', raw: value }];
    if (NUMBER_FIELDS.has(field)) return [{ subtitle: '', value: String(value), path: field, type: 'number', raw: value }];
    if (ENUM_OPTIONS[field]) return [{ subtitle: '', value: String(value), path: field, type: 'enum', raw: value, options: [...new Set([String(value), ...ENUM_OPTIONS[field]])] }];
    if (ARRAY_FIELDS.has(field)) return (Array.isArray(value) ? value : []).flatMap((item, itemIndex) => splitTextRows(item, { commas: shouldSplitArrayItem(field, item) }).map(entry => ({ ...entry, path: `${field}.${itemIndex}`, itemIndex })));
    if (field === 'recommendations' && Array.isArray(value)) return groupRecommendations(value).flatMap(group => { const entries = []; if (group.dateValue) entries.push({ subtitle: 'Date', value: formatDate(group.dateValue), path: `recommendations.${group.items[0].itemIndex}.date`, type: 'date', raw: group.dateValue }); group.items.forEach(({ item, itemIndex }) => { const objectItem = item && typeof item === 'object', textKey = objectItem ? (Object.hasOwn(item, 'recommendation') ? 'recommendation' : Object.hasOwn(item, 'text') ? 'text' : 'value') : null, raw = objectItem ? item[textKey] : item; if (hasVal(raw)) entries.push({ subtitle: '', value: String(raw), path: textKey ? `recommendations.${itemIndex}.${textKey}` : `recommendations.${itemIndex}`, type: 'text', raw }); }); return entries; });
    if (OBJECT_ARRAY_FIELDS.has(field)) return (Array.isArray(value) ? value : []).flatMap((item, itemIndex) => flattenObject(item).flatMap(leaf => { const path = `${field}.${itemIndex}.${leaf.path}`, sentence = pathIsDeclared(SENTENCE_OBJECT_PATHS, path), comma = pathIsDeclared(COMMA_OBJECT_PATHS, path), subtitle = `${OBJECT_ARRAY_ITEM_LABELS[field]} ${itemIndex + 1} — ${leaf.label}`; if (typeof leaf.value === 'string' && (sentence || comma)) return splitTextRows(leaf.value, { sentences: sentence, commas: comma }).map(entry => ({ ...entry, subtitle: entry.subtitle ? `${subtitle} — ${entry.subtitle}` : subtitle, path, type: 'text' })); return [{ subtitle, value: isDatePath(path) ? formatDate(leaf.value) : typeof leaf.value === 'boolean' ? (leaf.value ? 'Yes' : 'No') : String(leaf.value), path, type: isDatePath(path) ? 'date' : typeof leaf.value === 'number' ? 'number' : isNumericString(leaf.value) ? 'numberString' : typeof leaf.value === 'boolean' ? 'boolean' : 'text', raw: leaf.value }]; }));
    if (OBJECT_FIELDS.has(field)) return flattenObject(value).flatMap(leaf => { const path = `${field}.${leaf.path}`, sentence = pathIsDeclared(SENTENCE_OBJECT_PATHS, path), comma = pathIsDeclared(COMMA_OBJECT_PATHS, path), ratio = pathIsDeclared(SCORE_RATIO_PATHS, path) ? splitScoreRatio(leaf.value) : null; if (typeof leaf.value === 'string' && (sentence || comma)) return splitTextRows(leaf.value, { sentences: sentence, commas: comma }).map(entry => ({ ...entry, subtitle: entry.subtitle ? `${leaf.label} — ${entry.subtitle}` : leaf.label, path, type: 'text' })); return [{ subtitle: leaf.label, value: isDatePath(path) ? formatDate(leaf.value) : typeof leaf.value === 'boolean' ? (leaf.value ? 'Yes' : 'No') : String(leaf.value), path, type: ratio ? 'scoreRatio' : isDatePath(path) ? 'date' : typeof leaf.value === 'number' ? 'number' : isNumericString(leaf.value) ? 'numberString' : typeof leaf.value === 'boolean' ? 'boolean' : 'text', raw: leaf.value, ratio }]; });
    return splitString(field, value).map(entry => ({ ...entry, path: field, type: 'text' }));
  }, []);
  const sectionCopy = useCallback((record, index, section) => { const presentFields = SECTION_FIELDS[section].filter(field => hasVal(getValue(record, field, index))); if (!presentFields.length) return ''; let text = `${SECTION_TITLES[section]}\n${'='.repeat(40)}\n\n`; presentFields.forEach(field => { const value = getValue(record, field, index); text += `${FIELD_LABELS[field]}\n${'-'.repeat(40)}\n`; let prior = ''; rowsFor(field, value).forEach((entry, rowIndex) => { if (entry.subtitle && entry.subtitle !== prior) text += `${entry.subtitle}\n`; text += `${rowIndex + 1}. ${entry.value}\n`; prior = entry.subtitle || ''; }); text += '\n'; }); return text; }, [getValue, rowsFor]);
  const copyAll = useCallback(async () => { let text = `ADVANCE DIRECTIVE DISCUSSION\n${'='.repeat(40)}\n\n`; records.forEach((record, index) => { text += `Advance Directive Discussion ${index + 1}\n${'='.repeat(40)}\n\n`; Object.keys(SECTION_FIELDS).forEach(section => { text += sectionCopy(record, index, section); }); }); if (await copyText(text)) { setShowCopied(true); setTimeout(() => setShowCopied(false), 2000); } }, [copyText, records, sectionCopy]);
  const highlight = useCallback(value => { if (!searchTerm.trim()) return value; const escaped = searchTerm.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), matcher = new RegExp(`(${escaped})`, 'gi'); return String(value).split(matcher).map((part, index) => matcher.test(part) ? <mark key={index}>{part}</mark> : part); }, [searchTerm]);
  const row = ({ record, field, section, recordIndex, entry, key, save }) => {
    const editing = editingField === key, type = entry.type || 'text', dataField = entry.path, modified = editedFields[`${dataField}-${recordIndex}`], display = type === 'date' ? formatDate(entry.raw ?? entry.value) : type === 'boolean' ? ((entry.raw ?? entry.value) === true || entry.value === 'Yes' ? 'Yes' : 'No') : String(entry.value);
    const beginEditing = () => { if (editing) return; setEditingField(key); setEditValue(type === 'date' ? toInputDate(entry.raw ?? entry.value) : type === 'scoreRatio' ? entry.ratio.number : display); setSaveError(null); };
    const saveValue = event => {
      event.stopPropagation();
      if (type === 'scoreRatio') {
        const numeric = Number(editValue);
        if (!Number.isFinite(numeric) || numeric < 0 || numeric > entry.ratio.denominator) { setSaveError(`Enter a value from 0 to ${entry.ratio.denominator}`); return; }
        save(`${entry.ratio.prefix}${editValue}${entry.ratio.suffix}`);
        return;
      }
      save(type === 'boolean' ? editValue === 'Yes' : type === 'number' ? Number(editValue) : editValue);
    };
    return <div key={key} className="editable-leaf" data-edit-field={dataField}><div className={`numbered-row editable-row ${modified ? 'modified' : ''}`} onClick={beginEditing}>{editing ? <div className="edit-field-container">{type === 'date' ? <BlueDatePicker value={editValue} onSelect={next => setEditValue(next || '')} /> : type === 'boolean' ? <BlueSelect value={editValue} options={['Yes', 'No']} onChange={setEditValue} /> : type === 'enum' ? <BlueSelect value={editValue} options={entry.options} onChange={setEditValue} /> : type === 'scoreRatio' ? <div className="number-edit-row score-ratio-editor"><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String(Math.max(0, (Number(editValue) || 0) - entry.ratio.step))); }}>−</button><input type="text" inputMode="decimal" className="edit-input edit-number" value={editValue} onChange={event => setEditValue(event.target.value)} /><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String(Math.min(entry.ratio.denominator, (Number(editValue) || 0) + entry.ratio.step))); }}>+</button><span className="number-edit-unit">{entry.ratio.suffix}</span></div> : type === 'number' || type === 'numberString' ? <div className="number-edit-row"><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String((Number(editValue) || 0) - 1)); }}>−</button><input type="text" className="edit-input" value={editValue} onChange={event => setEditValue(event.target.value)} /><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String((Number(editValue) || 0) + 1)); }}>+</button></div> : <textarea className="edit-textarea" value={editValue} onChange={event => setEditValue(event.target.value)} autoFocus />}{saveError && <div className="save-error">{saveError}</div>}<div className="edit-actions"><button className="save-btn" disabled={saving} onClick={saveValue}>Save</button><button className="cancel-btn" onClick={event => { event.stopPropagation(); setEditingField(null); setEditValue(''); setSaveError(null); }}>Cancel</button></div></div> : <><div className="row-content"><span className="content-value">{highlight(display)}</span><span className="edit-indicator">&#9998;</span></div><button className={`copy-btn ${copiedItems[key] ? 'copied' : ''}`} onClick={async event => { event.stopPropagation(); if (await copyText(display)) { setCopiedItems(previous => ({ ...previous, [key]: true })); setTimeout(() => setCopiedItems(previous => ({ ...previous, [key]: false })), 2000); } }}>{copiedItems[key] ? 'Copied!' : 'Copy'}</button></>}</div>{modified && <span className="modified-badge">edited - click Pending Approve to save</span>}</div>;
  };
  const renderRecommendations = (record, recordIndex, section) => { const groups = groupRecommendations(getValue(record, 'recommendations', recordIndex)); return groups.map((group, groupIndex) => { const datePaths = group.items.filter(({ item }) => item && typeof item === 'object' && hasVal(item.date)).map(({ itemIndex }) => `recommendations.${itemIndex}.date`), dateEditKey = `recommendations-${recordIndex}-${group.dateKey}-date`, dateEditing = editingField === dateEditKey, dateModified = datePaths.some(path => editedFields[`${path}-${recordIndex}`]); return <div key={`${group.dateKey}-${groupIndex}`} className="rec-mini-card nested-mini-card recommendation-group">{group.dateValue && <div className="editable-date-subtitle" data-edit-field={datePaths[0]} data-edit-fields={datePaths.join(',')}><div className={`nested-subtitle editable-row date-subtitle ${dateModified ? 'modified' : ''}`} onClick={() => { if (!dateEditing) { setEditingField(dateEditKey); setEditValue(toInputDate(group.dateValue)); setSaveError(null); } }}>{dateEditing ? <div className="edit-field-container"><BlueDatePicker value={editValue} onSelect={next => setEditValue(next || '')} />{saveError && <div className="save-error">{saveError}</div>}<div className="edit-actions"><button className="save-btn" disabled={saving} onClick={event => { event.stopPropagation(); stageRecommendationDates(record, recordIndex, section, group.items.map(item => item.itemIndex), editValue); }}>Save</button><button className="cancel-btn" onClick={event => { event.stopPropagation(); setEditingField(null); setEditValue(''); setSaveError(null); }}>Cancel</button></div></div> : <><span className="content-value">{highlight(formatDate(group.dateValue))}</span><span className="edit-indicator">&#9998;</span></>}</div>{dateModified && <span className="modified-badge">edited - click Pending Approve to save</span>}</div>}{group.items.map(({ item, itemIndex }) => { const objectItem = item && typeof item === 'object', textKey = objectItem ? (Object.hasOwn(item, 'recommendation') ? 'recommendation' : Object.hasOwn(item, 'text') ? 'text' : 'value') : null, raw = objectItem ? item[textKey] : item; if (!hasVal(raw)) return null; const entry = { value: String(raw), raw, path: textKey ? `recommendations.${itemIndex}.${textKey}` : `recommendations.${itemIndex}`, type: 'text' }; return row({ record, field: 'recommendations', section, recordIndex, entry, key: `recommendations-${recordIndex}-${itemIndex}`, save: next => stagePath(record, 'recommendations', entry.path, recordIndex, section, next) }); })}</div>; }); };
  const renderField = (record, field, recordIndex, section) => { const value = getValue(record, field, recordIndex); if (!hasVal(value)) return null; if (field === 'recommendations' && Array.isArray(value)) return renderRecommendations(record, recordIndex, section); const entries = rowsFor(field, value), showFieldLabel = FIELD_LABELS[field].toLowerCase() !== SECTION_TITLES[section].toLowerCase(); const groups = []; entries.forEach((entry, entryIndex) => { const groupLabel = entry.subtitle || '', last = groups[groups.length - 1]; if (last && last.label === groupLabel) last.entries.push({ entry, entryIndex }); else groups.push({ label: groupLabel, entries: [{ entry, entryIndex }] }); }); return groups.map((group, groupIndex) => <div key={`${field}-${groupIndex}`} className="rec-mini-card nested-mini-card">{(showFieldLabel || group.label) && <div className="nested-subtitle">{showFieldLabel ? FIELD_LABELS[field] : ''}{showFieldLabel && group.label ? ' — ' : ''}{group.label}</div>}{group.entries.map(({ entry, entryIndex }) => row({ record, field, section, recordIndex, entry, key: `${field}-${recordIndex}-${entryIndex}`, save: next => { if (entry.textStructured) { const siblings = entries.filter(candidate => candidate.path === entry.path); stagePath(record, field, entry.path, recordIndex, section, rebuildTextRows(siblings, entry, next)); } else stagePath(record, field, entry.path, recordIndex, section, next); } }))}</div>); };
  const matches = useCallback(record => !searchTerm.trim() || JSON.stringify(record).toLowerCase().includes(searchTerm.trim().toLowerCase()), [searchTerm]);
  const pdfData = useMemo(() => records.filter(matches).map((record, index) => { const merged = { ...record }; Object.entries(localEdits).forEach(([key, value]) => { const match = key.match(/^(.+)-(\d+)$/); if (match && Number(match[2]) === index && !pendingEdits[key]) merged[match[1]] = value; }); return merged; }), [localEdits, matches, pendingEdits, records]);
  return <div ref={containerRef} className="advance-directive-discussion-document"><div className="document-header"><h2 className="document-title">Advance Directive Discussion</h2><div className="header-actions"><button className={`copy-btn ${showCopied ? 'copied' : ''}`} onClick={copyAll}>{showCopied ? 'Copied!' : 'Copy All'}</button><PDFDownloadLink document={<AdvanceDirectiveDiscussionDocumentPDFTemplate document={pdfData} />} fileName="Advance_Directive_Discussion.pdf" className="copy-btn">Export PDF</PDFDownloadLink></div></div><div className="search-container"><input className="search-input" type="text" value={searchTerm} onChange={event => setSearchTerm(event.target.value)} placeholder="Search advance directive discussion..." /></div><div className="records-container">{records.filter(matches).map((record, recordIndex) => <div className="record-card" key={safeId(record) || recordIndex}><div className="record-header"><h3 className="record-name">{record.provider || `Advance Directive Discussion Record ${recordIndex + 1}`}</h3></div>{Object.keys(SECTION_FIELDS).map(section => { const fields = SECTION_FIELDS[section]; if (!fields.some(field => hasVal(getValue(record, field, recordIndex)))) return null; const copyId = `${section}-${recordIndex}`, hasEdits = sectionHasEdits(section, recordIndex); return <section className="section" key={section}><div className="mini-cards-container"><div className="section-header"><h4 className="section-title">{SECTION_TITLES[section]}</h4><div className="header-right-actions"><button className={`copy-btn ${copiedSection === copyId ? 'copied' : ''}`} onClick={async () => { if (await copyText(sectionCopy(record, recordIndex, section))) { setCopiedSection(copyId); setTimeout(() => setCopiedSection(null), 2000); } }}>{copiedSection === copyId ? 'Copied!' : 'Copy Section'}</button>{hasEdits && <button className="approve-btn pending" disabled={saving} onClick={() => approve(record, section, recordIndex)}>Pending Approve</button>}{approvedSections[copyId] && !hasEdits && <span className="approve-btn approved">Approved</span>}</div></div>{fields.map(field => renderField(record, field, recordIndex, section))}</div></section>; })}</div>)}</div>{!records.length && <div className="empty-state">No advance directive discussions available</div>}</div>;
};

export default AdvanceDirectiveDiscussionDocument;
