import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';
import AllergySkinTestingDocumentPDFTemplate from '../pdf-templates/AllergySkinTestingDocumentPDFTemplate';
import BlueDatePicker from '../components/BlueDatePicker';
import secureApiClient from '../../../services/secureApiClient';
import './AllergySkinTestingDocument.css';

const DRAFT_KEY = 'allergy_skin_testingPendingEdits';
const readDrafts = () => { try { return JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}') || {}; } catch { return {}; } };
const writeDrafts = store => { try { if (store && Object.keys(store).length) localStorage.setItem(DRAFT_KEY, JSON.stringify(store)); else localStorage.removeItem(DRAFT_KEY); } catch { /* best effort */ } };

const SECTION_TITLES = {
  metadata: 'Test Information',
  controls: 'Controls',
  whealSize: 'Wheal Size',
  allergensTested: 'Allergens Tested',
  positiveReactions: 'Positive Reactions',
  negativeReactions: 'Negative Reactions',
  medicationsWithheld: 'Medications Withheld',
  adverseReactions: 'Adverse Reactions',
  interpretation: 'Interpretation',
  recommendations: 'Recommendations',
  notes: 'Notes',
};
const FIELD_LABELS = {
  date: 'Date', testType: 'Test Type', allergist: 'Allergist', facility: 'Facility', controls: 'Controls',
  whealSize: 'Wheal Size', allergensTested: 'Allergens Tested', positiveReactions: 'Positive Reactions',
  negativeReactions: 'Negative Reactions', medicationWithheld: 'Medications Withheld', adverseReactions: 'Adverse Reactions',
  interpretation: 'Interpretation', recommendations: 'Recommendations', notes: 'Notes',
};
const SECTION_FIELDS = {
  metadata: ['date', 'testType', 'allergist', 'facility'], controls: ['controls'], whealSize: ['whealSize'],
  allergensTested: ['allergensTested'], positiveReactions: ['positiveReactions'], negativeReactions: ['negativeReactions'],
  medicationsWithheld: ['medicationWithheld'], adverseReactions: ['adverseReactions'], interpretation: ['interpretation'],
  recommendations: ['recommendations'], notes: ['notes'],
};
const DATE_FIELDS = new Set(['date']);
const OBJECT_FIELDS = new Set(['whealSize']);
const ARRAY_FIELDS = new Set(['allergensTested', 'positiveReactions', 'negativeReactions', 'medicationWithheld']);
const SENTENCE_STRING_FIELDS = new Set(['controls', 'adverseReactions', 'interpretation', 'recommendations', 'notes']);
const COMMA_STRING_FIELDS = new Set(['controls', 'interpretation', 'notes']);

const hasVal = value => value !== null && value !== undefined && value !== '' && (!Array.isArray(value) || value.some(hasVal)) && (typeof value !== 'object' || Array.isArray(value) || Object.values(value).some(hasVal));
const safeId = record => record?._id?.$oid || record?._id || '';
const humanize = key => String(key || '').replace(/_/g, ' ').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, char => char.toUpperCase());
const isDateObject = value => value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === 1 && Object.hasOwn(value, '$date');
const rawDate = value => value?.$date?.$numberLong ?? value?.$date ?? value?.$numberLong ?? value;
const formatDate = value => { if (!value) return ''; try { const raw = rawDate(value), normalized = typeof raw === 'string' && /^-?\d+$/.test(raw) ? Number(raw) : raw, date = new Date(normalized); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }); } catch { return String(value); } };
const toInputDate = value => { if (!value) return ''; try { const raw = rawDate(value), normalized = typeof raw === 'string' && /^-?\d+$/.test(raw) ? Number(raw) : raw, date = new Date(normalized); return Number.isNaN(date.getTime()) ? '' : date.toISOString().slice(0, 10); } catch { return ''; } };
const safeDisplay = value => String(value ?? '').replace(/μ/g, 'µ');
const parseLabel = value => { const text = safeDisplay(value), match = text.match(/^([^:]{1,80}):\s+(.+)$/); return match ? { subtitle: match[1].trim(), content: match[2].trim() } : { subtitle: '', content: text }; };
const splitComma = value => { const rows = []; let current = '', depth = 0; for (const char of safeDisplay(value)) { if (char === '(') depth += 1; if (char === ')') depth = Math.max(0, depth - 1); if (char === ',' && depth === 0) { if (current.trim()) rows.push(current.trim()); current = ''; } else current += char; } if (current.trim()) rows.push(current.trim()); return rows; };
const splitSentenceParts = value => { const text = safeDisplay(value), rows = []; let start = 0; for (const match of text.matchAll(/;\s+|(?<!\b[A-Z])\.(?!\d)(?:\s+|$)/g)) { const row = text.slice(start, match.index).trim(); if (row && !/^[;.,!?]+$/.test(row)) rows.push({ value: row, delimiter: match[0].trim().charAt(0) }); start = match.index + match[0].length; } const tail = text.slice(start).trim(); if (tail && !/^[;.,!?]+$/.test(tail)) rows.push({ value: tail, delimiter: '' }); return rows.length ? rows : [{ value: text.trim(), delimiter: '' }]; };
const textRows = (value, { sentences = false, commas = false } = {}) => (sentences ? splitSentenceParts(value) : [{ value: safeDisplay(value).trim(), delimiter: '' }]).flatMap((part, partIndex) => { const parsed = parseLabel(part.value), clauses = commas ? splitComma(parsed.content) : [parsed.content]; return clauses.filter(Boolean).map((row, clauseIndex) => ({ subtitle: parsed.subtitle, value: row, textPart: partIndex, textClause: clauseIndex, textDelimiter: part.delimiter, textPrefix: parsed.subtitle ? `${parsed.subtitle}: ` : '', textStructured: sentences || commas })); });
const splitScoreRatio = value => { const match = String(value || '').match(/^(\s*)(-?\d+(?:\.\d+)?)(\s*\/\s*(\d+(?:\.\d+)?)[\s\S]*)$/); return match ? { prefix: match[1], number: match[2], suffix: match[3], denominator: Number(match[4]) } : null; };
const getPath = (record, path) => String(path).split('.').reduce((value, part) => value?.[part], record);
const setPath = (record, path, value) => { const parts = String(path).split('.'); let cursor = record; parts.slice(0, -1).forEach((part, index) => { if (!cursor[part] || typeof cursor[part] !== 'object') cursor[part] = /^\d+$/.test(parts[index + 1]) ? [] : {}; cursor = cursor[part]; }); cursor[parts.at(-1)] = value; };
const unwrap = source => { if (!source) return []; let rows = Array.isArray(source) ? source : [source]; rows = rows.flatMap(row => { if (Array.isArray(row?.records)) return row.records; if (Array.isArray(row?._records)) return row._records; if (row?.allergy_skin_testing) return Array.isArray(row.allergy_skin_testing) ? row.allergy_skin_testing : [row.allergy_skin_testing]; if (row?.documentData) { const nested = row.documentData; if (Array.isArray(nested)) return nested; if (nested?.allergy_skin_testing) return Array.isArray(nested.allergy_skin_testing) ? nested.allergy_skin_testing : [nested.allergy_skin_testing]; return [nested]; } return [row]; }); return rows.filter(row => row && typeof row === 'object'); };
const flattenObject = (value, prefix = '', labelPrefix = '') => {
  if (Array.isArray(value)) return value.flatMap((child, index) => { const path = prefix ? `${prefix}.${index}` : String(index), label = `${labelPrefix || 'Item'} ${index + 1}`; return child && typeof child === 'object' && !isDateObject(child) ? flattenObject(child, path, label) : hasVal(child) ? [{ path, subtitle: label, raw: child }] : []; });
  return Object.entries(value || {}).flatMap(([key, child]) => { const path = prefix ? `${prefix}.${key}` : key, label = labelPrefix ? `${labelPrefix} - ${humanize(key)}` : humanize(key); return child && typeof child === 'object' && !isDateObject(child) ? flattenObject(child, path, label) : hasVal(child) ? [{ path, subtitle: label, raw: child, dateLike: /date/i.test(key) }] : []; });
};
const entryType = (raw, dateLike = false) => { const ratio = splitScoreRatio(raw); if (dateLike) return { type: 'date', ratio }; if (typeof raw === 'number') return { type: 'number', ratio }; if (typeof raw === 'boolean') return { type: 'boolean', ratio }; if (ratio) return { type: 'scoreRatio', ratio }; if (typeof raw === 'string' && /^-?\d+(?:\.\d+)?$/.test(raw.trim())) return { type: 'numberString', ratio }; return { type: 'text', ratio }; };

const AllergySkinTestingDocument = ({ document: documentProp, data: dataProp, templateData }) => {
  const records = useMemo(() => unwrap(documentProp ?? dataProp ?? templateData), [documentProp, dataProp, templateData]);
  const [searchTerm, setSearchTerm] = useState('');
  const [editingField, setEditingField] = useState(null);
  const [editValue, setEditValue] = useState('');
  const [localEdits, setLocalEdits] = useState({});
  const [pendingEdits, setPendingEdits] = useState({});
  const [editedFields, setEditedFields] = useState({});
  const [approvedSections, setApprovedSections] = useState({});
  const [copiedItems, setCopiedItems] = useState({});
  const [copiedSection, setCopiedSection] = useState(null);
  const [showCopied, setShowCopied] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState(null);
  const containerRef = useRef(null);

  useEffect(() => { const store = readDrafts(), restored = {}, pending = {}, edited = {}; records.forEach((record, index) => Object.entries(store[safeId(record)] || {}).forEach(([path, value]) => { const key = `${path}-${index}`; restored[key] = value; pending[key] = true; edited[key] = true; })); if (!Object.keys(restored).length) return undefined; const timer = window.setTimeout(() => { setLocalEdits(previous => ({ ...restored, ...previous })); setPendingEdits(previous => ({ ...pending, ...previous })); setEditedFields(previous => ({ ...edited, ...previous })); }, 0); return () => window.clearTimeout(timer); }, [records]);
  const getValue = useCallback((record, path, index) => { const key = `${path}-${index}`; return Object.hasOwn(localEdits, key) ? localEdits[key] : getPath(record, path); }, [localEdits]);
  const stagePath = useCallback((record, path, index, section, value) => { const id = safeId(record); if (!id) { setSaveError('This record cannot be edited because it has no ID.'); return; } const key = `${path}-${index}`, store = readDrafts(); if (!store[id]) store[id] = {}; store[id][path] = value; writeDrafts(store); setLocalEdits(previous => ({ ...previous, [key]: value })); setPendingEdits(previous => ({ ...previous, [key]: true })); setEditedFields(previous => ({ ...previous, [key]: true })); setApprovedSections(previous => { const next = { ...previous }; delete next[`${section}-${index}`]; return next; }); setEditingField(null); setEditValue(''); setSaveError(null); }, []);
  const sectionHasEdits = useCallback((section, index) => SECTION_FIELDS[section].some(field => Object.keys(pendingEdits).some(key => key.endsWith(`-${index}`) && key.slice(0, key.lastIndexOf(`-${index}`)).split('.')[0] === field)), [pendingEdits]);
  const approve = useCallback(async (record, section, index) => { const id = safeId(record); if (!id) return; setSaving(true); setSaveError(null); try { const store = readDrafts(), drafts = store[id] || {}, committed = []; for (const [path, value] of Object.entries(drafts)) { if (!SECTION_FIELDS[section].includes(path.split('.')[0])) continue; const response = await secureApiClient.put(`/api/edit/allergy_skin_testing/${id}/edit`, { field: path, value }); if (response?.success === false) throw new Error(response.error || 'Save failed'); committed.push(path); } await secureApiClient.put(`/api/edit/allergy_skin_testing/${id}/approve`, { sectionId: section, approved: true }); setPendingEdits(previous => { const next = { ...previous }; committed.forEach(path => delete next[`${path}-${index}`]); return next; }); committed.forEach(path => delete drafts[path]); if (Object.keys(drafts).length) store[id] = drafts; else delete store[id]; writeDrafts(store); setApprovedSections(previous => ({ ...previous, [`${section}-${index}`]: true })); } catch (error) { console.error(error); setSaveError('Approve failed. Please try again.'); } finally { setSaving(false); } }, []);
  const copyText = useCallback(async text => { try { await navigator.clipboard.writeText(text); return true; } catch { const area = window.document.createElement('textarea'); area.value = text; area.style.position = 'fixed'; area.style.opacity = '0'; (containerRef.current || window.document.body).appendChild(area); area.select(); const copied = window.document.execCommand('copy'); area.remove(); return copied; } }, []);
  const entriesForField = useCallback((field, value) => {
    if (DATE_FIELDS.has(field)) return [{ value: formatDate(value), raw: value, path: field, type: 'date' }];
    if (OBJECT_FIELDS.has(field)) return flattenObject(value).map(leaf => { const typed = entryType(leaf.raw, leaf.dateLike); return { subtitle: leaf.subtitle, value: typed.type === 'date' ? formatDate(leaf.raw) : typed.type === 'boolean' ? (leaf.raw ? 'Yes' : 'No') : safeDisplay(leaf.raw), raw: leaf.raw, path: `${field}.${leaf.path}`, ...typed }; });
    if (ARRAY_FIELDS.has(field)) return value.flatMap((raw, index) => { if (!hasVal(raw)) return []; if (raw && typeof raw === 'object' && !isDateObject(raw)) return flattenObject(raw, String(index), `Item ${index + 1}`).map(leaf => { const typed = entryType(leaf.raw, leaf.dateLike); return { subtitle: leaf.subtitle, value: typed.type === 'date' ? formatDate(leaf.raw) : typed.type === 'boolean' ? (leaf.raw ? 'Yes' : 'No') : safeDisplay(leaf.raw), raw: leaf.raw, path: `${field}.${leaf.path}`, ...typed }; }); const typed = entryType(raw); return [{ subtitle: '', value: safeDisplay(raw), raw, path: `${field}.${index}`, ...typed }]; });
    return textRows(value, { sentences: SENTENCE_STRING_FIELDS.has(field), commas: COMMA_STRING_FIELDS.has(field) }).map(entry => ({ ...entry, path: field, raw: value, ...entryType(entry.value) }));
  }, []);
  const rebuildTextRows = (entries, target, nextValue) => { const groups = []; entries.forEach(entry => { let group = groups.find(item => item.part === entry.textPart); if (!group) { group = { part: entry.textPart, prefix: entry.textPrefix || '', delimiter: entry.textDelimiter || '', clauses: [] }; groups.push(group); } group.clauses.push(entry === target ? String(nextValue).trim() : String(entry.value).trim()); }); return groups.sort((a, b) => a.part - b.part).map(group => `${group.prefix}${group.clauses.filter(Boolean).join(', ')}${group.delimiter}${group.delimiter ? ' ' : ''}`).join('').trim(); };
  const rowsForSection = useCallback((record, index, section) => SECTION_FIELDS[section].flatMap(field => { const value = getValue(record, field, index); return hasVal(value) ? entriesForField(field, value).map(entry => ({ ...entry, field })) : []; }), [entriesForField, getValue]);
  const sectionCopy = useCallback((record, index, section) => { let text = `${SECTION_TITLES[section]}\n${'='.repeat(40)}\n\n`; SECTION_FIELDS[section].filter(field => hasVal(getValue(record, field, index))).forEach(field => { text += `${FIELD_LABELS[field]}\n${'-'.repeat(40)}\n`; let prior = ''; entriesForField(field, getValue(record, field, index)).forEach((entry, rowIndex) => { if (entry.subtitle && entry.subtitle !== prior) text += `${entry.subtitle}\n`; text += `${rowIndex + 1}. ${entry.value}\n`; prior = entry.subtitle || ''; }); text += '\n'; }); return text; }, [entriesForField, getValue]);
  const copyAll = useCallback(async () => { let text = `ALLERGY SKIN TESTING\n${'='.repeat(40)}\n\n`; records.forEach((record, index) => { text += `Allergy Skin Testing ${index + 1}\n${'='.repeat(40)}\n\n`; Object.keys(SECTION_FIELDS).forEach(section => { if (rowsForSection(record, index, section).length) text += sectionCopy(record, index, section); }); }); if (await copyText(text)) { setShowCopied(true); setTimeout(() => setShowCopied(false), 2000); } }, [copyText, records, rowsForSection, sectionCopy]);
  const highlight = useCallback(value => { if (!searchTerm.trim()) return value; const escaped = searchTerm.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), matcher = new RegExp(`(${escaped})`, 'gi'); return String(value).split(matcher).map((part, index) => part.toLowerCase() === searchTerm.trim().toLowerCase() ? <mark key={index}>{part}</mark> : part); }, [searchTerm]);

  const renderRow = ({ recordIndex, entry, key, save }) => {
    const editing = editingField === key, modified = editedFields[`${entry.path}-${recordIndex}`];
    const display = entry.type === 'date' ? formatDate(entry.raw) : entry.type === 'boolean' ? (entry.raw === true || entry.value === 'Yes' ? 'Yes' : 'No') : String(entry.value);
    const beginEditing = () => { if (editing) return; setEditingField(key); setEditValue(entry.type === 'date' ? toInputDate(entry.raw) : entry.type === 'boolean' ? display : entry.type === 'scoreRatio' ? entry.ratio.number : display); setSaveError(null); };
    const adjust = delta => { const current = Number(editValue) || 0, next = entry.type === 'scoreRatio' ? Math.max(0, Math.min(entry.ratio.denominator, current + delta)) : current + delta; setEditValue(String(next)); };
    const saveValue = event => { event.stopPropagation(); if (['number', 'numberString', 'scoreRatio'].includes(entry.type) && !Number.isFinite(Number(editValue))) { setSaveError('Enter a valid number.'); return; } if (entry.type === 'boolean') save(editValue === 'Yes'); else if (entry.type === 'number') save(Number(editValue)); else if (entry.type === 'scoreRatio') save(`${entry.ratio.prefix}${editValue}${entry.ratio.suffix}`); else save(editValue); };
    return <div key={key} className="editable-leaf" data-edit-field={entry.path}><div className={`numbered-row editable-row ${modified ? 'modified' : ''}`} onClick={beginEditing}>{editing ? <div className="edit-field-container">{entry.type === 'date' ? <BlueDatePicker value={editValue} onSelect={next => setEditValue(next || '')} /> : entry.type === 'boolean' ? <div className="boolean-editor"><button type="button" className={`choice-btn ${editValue === 'Yes' ? 'selected' : ''}`} onClick={event => { event.stopPropagation(); setEditValue('Yes'); }}>Yes</button><button type="button" className={`choice-btn ${editValue === 'No' ? 'selected' : ''}`} onClick={event => { event.stopPropagation(); setEditValue('No'); }}>No</button></div> : ['number', 'numberString', 'scoreRatio'].includes(entry.type) ? <div className="number-edit-row"><button type="button" className="num-step" onClick={event => { event.stopPropagation(); adjust(-1); }}>−</button><input type="text" inputMode="decimal" className="edit-input edit-number" value={editValue} onChange={event => setEditValue(event.target.value)} /><button type="button" className="num-step" onClick={event => { event.stopPropagation(); adjust(1); }}>+</button>{entry.type === 'scoreRatio' && <span className="number-edit-unit">{entry.ratio.suffix}</span>}</div> : <textarea className="edit-textarea" value={editValue} onChange={event => setEditValue(event.target.value)} autoFocus />}{saveError && <div className="save-error">{saveError}</div>}<div className="edit-actions"><button className="save-btn" disabled={saving} onClick={saveValue}>Save</button><button className="cancel-btn" onClick={event => { event.stopPropagation(); setEditingField(null); setEditValue(''); setSaveError(null); }}>Cancel</button></div></div> : <><div className="row-content editable"><span className="content-value">{highlight(display)}</span><span className="edit-indicator">&#9998;</span></div><button className={`copy-btn ${copiedItems[key] ? 'copied' : ''}`} onClick={async event => { event.stopPropagation(); if (await copyText(display)) { setCopiedItems(previous => ({ ...previous, [key]: true })); setTimeout(() => setCopiedItems(previous => ({ ...previous, [key]: false })), 2000); } }}>{copiedItems[key] ? 'Copied!' : 'Copy'}</button></>}</div>{modified && <span className="modified-badge">edited - click Pending Approve to save</span>}</div>;
  };
  const renderEntries = (record, field, recordIndex, section, entries) => { const defaultLabel = FIELD_LABELS[field] === SECTION_TITLES[section] ? '' : FIELD_LABELS[field], groups = []; entries.forEach((entry, entryIndex) => { const label = entry.subtitle || defaultLabel, last = groups.at(-1); if (last && last.label === label) last.entries.push({ entry, entryIndex }); else groups.push({ label, entries: [{ entry, entryIndex }] }); }); return groups.map((group, groupIndex) => <div key={`${field}-${groupIndex}`} className={`rec-mini-card nested-mini-card ${group.label ? '' : 'regular-row-group'}`}>{group.label && <div className="nested-subtitle">{group.label}</div>}{group.entries.map(({ entry, entryIndex }) => renderRow({ record, section, recordIndex, entry, key: `${field}-${recordIndex}-${entryIndex}`, save: next => { if (entry.textStructured) stagePath(record, entry.path, recordIndex, section, rebuildTextRows(entries, entry, next)); else stagePath(record, entry.path, recordIndex, section, next); } }))}</div>); };
  const matches = useCallback(record => !searchTerm.trim() || JSON.stringify(record).toLowerCase().includes(searchTerm.trim().toLowerCase()), [searchTerm]);
  const pdfData = useMemo(() => records.map((record, index) => { const merged = structuredClone(record); Object.entries(localEdits).forEach(([key, value]) => { const suffix = `-${index}`; if (key.endsWith(suffix) && !pendingEdits[key]) setPath(merged, key.slice(0, -suffix.length), value); }); return merged; }).filter(matches), [localEdits, matches, pendingEdits, records]);
  const visibleRecords = useMemo(() => records.map((record, recordIndex) => ({ record, recordIndex })).filter(({ record }) => matches(record)), [matches, records]);

  return <div ref={containerRef} className="allergy-skin-testing-document"><div className="document-header"><h2 className="document-title">Allergy Skin Testing</h2><div className="header-actions"><button className={`copy-btn ${showCopied ? 'copied' : ''}`} onClick={copyAll}>{showCopied ? 'Copied!' : 'Copy All'}</button><PDFDownloadLink document={<AllergySkinTestingDocumentPDFTemplate document={pdfData} />} fileName="Allergy_Skin_Testing.pdf" className="copy-btn">Export PDF</PDFDownloadLink></div></div><div className="search-container"><input className="search-input" type="text" value={searchTerm} onChange={event => setSearchTerm(event.target.value)} placeholder="Search allergy skin testing..." /></div><div className="records-list">{visibleRecords.map(({ record, recordIndex }) => <div className="record-card" key={safeId(record) || recordIndex}><div className="card-header"><h3 className="card-title">Allergy Skin Testing {recordIndex + 1}</h3></div><div className="card-content">{Object.keys(SECTION_FIELDS).map(section => { const entries = rowsForSection(record, recordIndex, section); if (!entries.length) return null; const copyId = `${section}-${recordIndex}`, hasEdits = sectionHasEdits(section, recordIndex); return <section className="section" key={section}><div className="mini-cards-container"><div className="section-header"><h4 className="section-title">{SECTION_TITLES[section]}</h4><div className="header-right-actions"><button className={`copy-btn ${copiedSection === copyId ? 'copied' : ''}`} onClick={async () => { if (await copyText(sectionCopy(record, recordIndex, section))) { setCopiedSection(copyId); setTimeout(() => setCopiedSection(null), 2000); } }}>{copiedSection === copyId ? 'Copied!' : 'Copy Section'}</button>{hasEdits && <button className="approve-btn pending" disabled={saving} onClick={() => approve(record, section, recordIndex)}>Pending Approve</button>}{approvedSections[copyId] && !hasEdits && <span className="approve-btn approved">Approved</span>}</div></div>{SECTION_FIELDS[section].flatMap(field => { const value = getValue(record, field, recordIndex); return hasVal(value) ? renderEntries(record, field, recordIndex, section, entriesForField(field, value)) : []; })}</div></section>; })}</div></div>)}</div>{!records.length && <div className="empty-state">No allergy skin testing records available</div>}</div>;
};

export default AllergySkinTestingDocument;
