import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';
import AutoantibodyProfileDocumentPDFTemplate from '../pdf-templates/AutoantibodyProfileDocumentPDFTemplate';
import BlueDatePicker from '../components/BlueDatePicker';
import BlueSelect from '../components/BlueSelect';
import secureApiClient from '../../../services/secureApiClient';
import './AutoantibodyProfileDocument.css';

const COLLECTION = 'autoantibody_profile';
const DRAFT_KEY = `${COLLECTION}PendingEdits`;
const COMMA_ARRAY_FIELDS = [];
const COMMA_SPLIT_FIELDS = ['assessment'];
const CORE_FIELDS = [['antiDsDna', 'Anti-dsDNA'], ['antiSmith', 'Anti-Smith'], ['antiSsaRo', 'Anti-SSA/Ro'], ['antiSsbLa', 'Anti-SSB/La'], ['antiRnp', 'Anti-RNP'], ['antiScl70', 'Anti-Scl-70'], ['antiCentromere', 'Anti-Centromere'], ['antiJo1', 'Anti-Jo-1'], ['antiCcp', 'Anti-CCP'], ['rheumatoidFactor', 'Rheumatoid Factor']];
const FIXED_OBJECTS = {
  ana: [['titer', 'Titer'], ['pattern', 'Pattern'], ['positive', 'Positive']],
  antiphospholipidAntibodies: [['anticardiolipin.IgG', 'Anticardiolipin IgG'], ['anticardiolipin.IgM', 'Anticardiolipin IgM'], ['beta2Glycoprotein.IgG', 'Beta-2 Glycoprotein IgG'], ['beta2Glycoprotein.IgM', 'Beta-2 Glycoprotein IgM'], ['lupusAnticoagulant', 'Lupus Anticoagulant']],
  anca: [['cAnca', 'c-ANCA'], ['pAnca', 'p-ANCA'], ['antiPr3', 'Anti-PR3'], ['antiMpo', 'Anti-MPO']],
};
const FIELD_LABELS = { date: 'Date', provider: 'Provider', facility: 'Facility', status: 'Status', ana: 'ANA Panel', ...Object.fromEntries(CORE_FIELDS), antiphospholipidAntibodies: 'Antiphospholipid Antibodies', anca: 'ANCA Panel', results: 'Results', findings: 'Findings', assessment: 'Assessment', plan: 'Plan', recommendations: 'Recommendations', notes: 'Notes' };
const SECTIONS = [
  { id: 'date', title: 'Date', fields: ['date'] },
  { id: 'recordInfo', title: 'Record Information', fields: ['provider', 'facility', 'status'] },
  { id: 'anaPanel', title: 'ANA Panel', fields: ['ana'] },
  { id: 'coreAntibodies', title: 'Core Antibodies', fields: CORE_FIELDS.map(([field]) => field) },
  { id: 'antiphospholipid', title: 'Antiphospholipid Antibodies', fields: ['antiphospholipidAntibodies'] },
  { id: 'ancaPanel', title: 'ANCA Panel', fields: ['anca'] },
  { id: 'results', title: 'Results', fields: ['results'] },
  { id: 'findings', title: 'Findings', fields: ['findings'] },
  { id: 'assessment', title: 'Assessment', fields: ['assessment'] },
  { id: 'plan', title: 'Plan', fields: ['plan'] },
  { id: 'recommendations', title: 'Recommendations', fields: ['recommendations'] },
  { id: 'notes', title: 'Notes', fields: ['notes'] },
];
const DATE_FIELDS = new Set(['date']);
const NARRATIVE_FIELDS = new Set(['findings', 'assessment', 'plan']);
const DISPLAY_FIELDS = Object.keys(FIELD_LABELS);

const readDrafts = () => { try { return JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}') || {}; } catch { return {}; } };
const writeDrafts = store => { try { if (store && Object.keys(store).length) localStorage.setItem(DRAFT_KEY, JSON.stringify(store)); else localStorage.removeItem(DRAFT_KEY); } catch { /* best effort */ } };
const hasValue = value => value !== null && value !== undefined && value !== '' && (!Array.isArray(value) || value.some(hasValue)) && (typeof value !== 'object' || Array.isArray(value) || Object.values(value).some(hasValue));
const recordIdOf = record => !record?._id ? null : typeof record._id === 'string' ? record._id : record._id.$oid || String(record._id);
const humanize = key => String(key || '').replace(/_/g, ' ').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, character => character.toUpperCase());
const getAtPath = (source, path) => path.split('.').reduce((value, part) => value?.[/^\d+$/.test(part) ? Number(part) : part], source);
const setAtPath = (source, path, value) => { const parts = path.split('.'); let node = source; parts.forEach((part, index) => { const key = /^\d+$/.test(part) ? Number(part) : part; if (index === parts.length - 1) node[key] = value; else { const array = /^\d+$/.test(parts[index + 1]); if (node[key] === undefined || node[key] === null) node[key] = array ? [] : {}; node = node[key]; } }); };
const formatDate = value => { if (!value) return ''; const raw = value.$date || value; const match = String(raw).match(/^(\d{4})-(\d{2})-(\d{2})/); if (!match) return String(raw); const date = new Date(`${match[1]}-${match[2]}-${match[3]}T00:00:00Z`); return Number.isNaN(date.getTime()) ? String(raw) : date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' }); };
const toInputDate = value => { const raw = value?.$date || value; const match = String(raw || '').match(/^(\d{4})-(\d{2})-(\d{2})/); return match ? `${match[1]}-${match[2]}-${match[3]}` : ''; };
const displayValue = (path, value) => path === 'ana.positive' ? (value ? 'Positive' : 'Negative') : typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value ?? '');
const parseLabel = text => { const match = String(text || '').match(/^([A-Z][A-Za-z0-9 /&()'"-]{1,60}?):\s+([\s\S]+)$/); return match ? { label: match[1].trim(), value: match[2].trim(), labeled: true } : { label: '', value: String(text || '').trim(), labeled: false }; };
const splitClauses = (field, text, splitCommas = COMMA_SPLIT_FIELDS.includes(field)) => { const source = String(text || ''); if (!source.trim()) return []; const clauses = []; let start = 0, depth = 0; const push = end => { let left = start, right = end; while (left < right && /\s/.test(source[left])) left += 1; while (right > left && /\s/.test(source[right - 1])) right -= 1; if (right > left) clauses.push({ text: source.slice(left, right), start: left, end: right }); }; for (let index = 0; index < source.length; index += 1) { const character = source[index]; if (character === '(') { depth += 1; continue; } if (character === ')') { depth = Math.max(0, depth - 1); continue; } if (depth) continue; const sentenceBreak = (character === '.' || character === ';') && (index + 1 === source.length || /\s/.test(source[index + 1])); const commaBreak = splitCommas && character === ','; if (!sentenceBreak && !commaBreak) continue; push(index); start = index + 1; } push(source.length); return clauses; };
const groupClauses = clauses => { const groups = []; let current = null; clauses.forEach((clause, index) => { const parsed = parseLabel(clause.text), item = { ...clause, ...parsed, index }; if (parsed.labeled) { current = { subtitle: parsed.label, items: [item] }; groups.push(current); } else if (current?.subtitle) current.items.push(item); else { if (!current || current.subtitle) { current = { subtitle: null, items: [] }; groups.push(current); } current.items.push(item); } }); return groups; };
const flattenLeaves = (value, prefix = '', labelPrefix = '') => { if (Array.isArray(value)) return value.flatMap((child, index) => { const path = prefix ? `${prefix}.${index}` : String(index), label = `${labelPrefix || 'Item'} ${index + 1}`; return child && typeof child === 'object' && !child.$date ? flattenLeaves(child, path, label) : hasValue(child) ? [{ path, label, value: child }] : []; }); return Object.entries(value || {}).flatMap(([key, child]) => { const path = prefix ? `${prefix}.${key}` : key, label = labelPrefix ? `${labelPrefix} — ${humanize(key)}` : humanize(key); return child && typeof child === 'object' && !child.$date ? flattenLeaves(child, path, label) : hasValue(child) ? [{ path, label, value: child }] : []; }); };
const groupRecommendations = value => { const groups = []; (Array.isArray(value) ? value : []).forEach((item, itemIndex) => { if (!hasValue(item)) return; const dateValue = item && typeof item === 'object' ? item.date : null, dateKey = dateValue ? toInputDate(dateValue) : 'no-date'; let group = groups.find(candidate => candidate.dateKey === dateKey); if (!group) { group = { dateKey, dateValue, items: [] }; groups.push(group); } group.items.push({ item, itemIndex }); }); return groups; };
const unwrapRecords = source => { if (!source) return []; const queue = Array.isArray(source) ? [...source] : [source], records = []; while (queue.length) { const value = queue.shift(); if (!value) continue; if (Array.isArray(value)) { queue.unshift(...value); continue; } if (value[COLLECTION] !== undefined) { queue.unshift(value[COLLECTION]); continue; } if (value.documentData !== undefined) { queue.unshift(value.documentData); continue; } if (value.data !== undefined && !DISPLAY_FIELDS.some(field => hasValue(value[field]))) { queue.unshift(value.data); continue; } if (value.records !== undefined) { queue.unshift(value.records); continue; } if (typeof value === 'object') records.push(value); } return records.filter(record => DISPLAY_FIELDS.some(field => hasValue(record[field]))); };

const AutoantibodyProfileDocument = ({ document: documentProp, data, templateData }) => {
  const records = useMemo(() => unwrapRecords(documentProp || data || templateData), [documentProp, data, templateData]);
  const [searchTerm, setSearchTerm] = useState(''); const [copied, setCopied] = useState(null); const [editingField, setEditingField] = useState(null); const [editValue, setEditValue] = useState(''); const [saveError, setSaveError] = useState(''); const [localEdits, setLocalEdits] = useState({}); const [pendingEdits, setPendingEdits] = useState({}); const [approvedSections, setApprovedSections] = useState({}); const [approving, setApproving] = useState(false);
  useEffect(() => { const store = readDrafts(), nextLocal = {}, nextPending = {}; records.forEach((record, index) => { Object.entries(store[recordIdOf(record)] || {}).forEach(([path, value]) => { nextLocal[`${path}-${index}`] = value; nextPending[`${path}-${index}`] = true; }); }); if (Object.keys(nextLocal).length) { setLocalEdits(previous => ({ ...nextLocal, ...previous })); setPendingEdits(previous => ({ ...nextPending, ...previous })); } }, [records]);
  const valueAt = useCallback((record, path, index) => localEdits[`${path}-${index}`] !== undefined ? localEdits[`${path}-${index}`] : getAtPath(record, path), [localEdits]);
  const stagePath = useCallback((record, path, index, value) => { const id = recordIdOf(record); if (!id) return; const key = `${path}-${index}`; setLocalEdits(previous => ({ ...previous, [key]: value })); setPendingEdits(previous => ({ ...previous, [key]: true })); const store = readDrafts(); store[id] = { ...(store[id] || {}), [path]: value }; writeDrafts(store); setEditingField(null); setEditValue(''); setSaveError(''); }, []);
  const mergedRecord = useCallback((record, index, includePending) => { const merged = JSON.parse(JSON.stringify(record)); Object.entries(localEdits).forEach(([key, value]) => { if (!key.endsWith(`-${index}`) || (!includePending && pendingEdits[key])) return; setAtPath(merged, key.slice(0, -String(index).length - 1), value); }); return merged; }, [localEdits, pendingEdits]);
  const pdfData = useMemo(() => records.map((record, index) => mergedRecord(record, index, false)), [records, mergedRecord]);
  const copyText = async (text, id) => { await navigator.clipboard.writeText(text); setCopied(id); setTimeout(() => setCopied(null), 2500); };
  const highlight = value => { const text = String(value ?? ''), query = searchTerm.trim(); if (!query) return text; const index = text.toLowerCase().indexOf(query.toLowerCase()); return index < 0 ? text : <>{text.slice(0, index)}<mark>{text.slice(index, index + query.length)}</mark>{text.slice(index + query.length)}</>; };
  const sectionPending = (section, index) => Object.keys(pendingEdits).some(key => pendingEdits[key] && key.endsWith(`-${index}`) && section.fields.includes(key.slice(0, -String(index).length - 1).split('.')[0]));
  const approveSection = async (record, index, section) => { const id = recordIdOf(record); if (!id) return; const keys = Object.keys(pendingEdits).filter(key => pendingEdits[key] && key.endsWith(`-${index}`) && section.fields.includes(key.slice(0, -String(index).length - 1).split('.')[0])); if (!keys.length) return; setApproving(true); try { for (const key of keys) { const path = key.slice(0, -String(index).length - 1), response = await secureApiClient.put(`/api/edit/${COLLECTION}/${id}/edit`, { field: path, value: localEdits[key] }); if (response?.success === false) throw new Error(response.error || 'save failed'); } const response = await secureApiClient.put(`/api/edit/${COLLECTION}/${id}/approve`, { sectionId: section.id, approved: true }); if (response?.success === false) throw new Error(response.error || 'approval failed'); setPendingEdits(previous => { const next = { ...previous }; keys.forEach(key => delete next[key]); return next; }); const store = readDrafts(); if (store[id]) { keys.forEach(key => delete store[id][key.slice(0, -String(index).length - 1)]); if (!Object.keys(store[id]).length) delete store[id]; writeDrafts(store); } setApprovedSections(previous => ({ ...previous, [`${section.id}-${index}`]: true })); } catch (error) { setSaveError(error.message || 'Unable to approve changes'); } finally { setApproving(false); } };
  const editControl = (widget, options) => { if (widget === 'date') return <BlueDatePicker value={editValue} onSelect={setEditValue} />; if (widget === 'boolean' || widget === 'enum') return <BlueSelect value={editValue} options={options} onChange={setEditValue} />; if (widget === 'number') return <div className="num-stepper-row"><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String((Number(editValue) || 0) - 1)); }}>&minus;</button><input type="text" inputMode="decimal" className="num-stepper-input" value={editValue} onChange={event => setEditValue(event.target.value.replace(/[^0-9.-]/g, ''))} /><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String((Number(editValue) || 0) + 1)); }}>+</button></div>; return <textarea className="edit-textarea" value={editValue} onChange={event => setEditValue(event.target.value)} autoFocus />; };
  const renderLeaf = ({ record, index, path, shown, raw, label, widget = 'text', options = [], leafKey, saveValue }) => { const editKey = leafKey || `${path}-${index}`, editing = editingField === editKey, modified = !!pendingEdits[`${path}-${index}`]; const save = event => { event?.stopPropagation(); if (!String(editValue).trim()) { setSaveError('Please enter a value'); return; } let next; if (saveValue) next = saveValue(editValue); else if (widget === 'date') next = `${editValue}T00:00:00.000Z`; else if (widget === 'number') next = Number(editValue); else if (widget === 'boolean') next = path === 'ana.positive' ? editValue === 'Positive' : editValue === 'Yes'; else next = String(editValue).trim(); stagePath(record, path, index, next); }; return <div data-edit-field={path} key={editKey}><span className="field-label sr-only">{label || path}</span><div className={`numbered-row editable-row${modified ? ' modified' : ''}`} onClick={() => { if (!editing) { setEditingField(editKey); setEditValue(widget === 'date' ? toInputDate(raw) : String(shown)); setSaveError(''); } }}>{editing ? <div className="edit-field-container" onClick={event => event.stopPropagation()}>{editControl(widget, options)}{saveError && <div className="save-error">{saveError}</div>}<div className="edit-actions"><button className="save-btn" onClick={save}>Save</button><button className="cancel-btn" onClick={event => { event.stopPropagation(); setEditingField(null); setEditValue(''); setSaveError(''); }}>Cancel</button></div></div> : <><div className="row-content"><span className="content-value">{highlight(shown)}</span><span className="edit-indicator">&#9998;</span></div><button className={`copy-btn ${copied === editKey ? 'copied' : ''}`} onClick={event => { event.stopPropagation(); copyText(String(shown), editKey); }}>{copied === editKey ? 'Copied!' : 'Copy'}</button></>}</div>{modified && <div className="modified-badge">edited - click Pending Approve to save</div>}</div>; };
  const renderScalar = (record, index, path, label, sectionTitle) => { const value = valueAt(record, path, index); if (!hasValue(value)) return null; let widget = DATE_FIELDS.has(path) ? 'date' : typeof value === 'number' ? 'number' : typeof value === 'boolean' ? 'boolean' : path === 'status' ? 'enum' : 'text'; const shown = DATE_FIELDS.has(path) ? formatDate(value) : displayValue(path, value), options = widget === 'boolean' ? (path === 'ana.positive' ? ['Positive', 'Negative'] : ['Yes', 'No']) : widget === 'enum' ? [...new Map([shown, 'Completed', 'Active', 'Pending', 'Reviewed'].map(option => [option.toLowerCase(), option])).values()] : []; return <div className={`rec-mini-card nested-mini-card${label === sectionTitle ? ' regular-row-group' : ''}`} key={path}>{label !== sectionTitle && <div className="nested-subtitle field-label">{label}</div>}{renderLeaf({ record, index, path, shown, raw: value, label, widget, options })}</div>; };
  const renderFixedObject = (record, index, field) => FIXED_OBJECTS[field].map(([subpath, label]) => { const path = `${field}.${subpath}`, value = valueAt(record, path, index); if (!hasValue(value)) return null; const widget = typeof value === 'number' ? 'number' : typeof value === 'boolean' ? 'boolean' : 'text', shown = displayValue(path, value), options = widget === 'boolean' ? (path === 'ana.positive' ? ['Positive', 'Negative'] : ['Yes', 'No']) : []; return <div className="rec-mini-card nested-mini-card" key={path}><div className="nested-subtitle field-label">{label}</div>{renderLeaf({ record, index, path, shown, raw: value, label, widget, options })}</div>; }).filter(Boolean);
  const renderResults = (record, index) => { const value = valueAt(record, 'results', index); if (!value || typeof value !== 'object') return null; return flattenLeaves(value).map(leaf => { const path = `results.${leaf.path}`, widget = typeof leaf.value === 'number' ? 'number' : typeof leaf.value === 'boolean' ? 'boolean' : /date/i.test(leaf.path.split('.').pop()) ? 'date' : 'text', shown = widget === 'date' ? formatDate(leaf.value) : displayValue(path, leaf.value), options = widget === 'boolean' ? ['Yes', 'No'] : []; return <div className="rec-mini-card nested-mini-card" key={path}><div className="nested-subtitle field-label">{leaf.label}</div>{renderLeaf({ record, index, path, shown, raw: leaf.value, label: leaf.label, widget, options })}</div>; }); };
  const renderNarrative = (record, index, field, sectionTitle) => { const source = String(valueAt(record, field, index) || ''); if (!source.trim()) return null; const groups = groupClauses(splitClauses(field, source)); return groups.map((group, groupIndex) => <div className={`rec-mini-card nested-mini-card${group.subtitle ? '' : ' regular-row-group'}`} key={`${field}-${groupIndex}`}>{group.subtitle && <div className="nested-subtitle">{group.subtitle}</div>}{group.items.map(item => renderLeaf({ record, index, path: field, leafKey: `${field}-${index}-clause-${item.index}`, shown: item.value, raw: item.value, label: group.subtitle || sectionTitle, saveValue: next => source.slice(0, item.start) + (item.labeled ? `${item.label}: ${String(next).trim()}` : String(next).trim()) + source.slice(item.end) }))}</div>); };
  const stageRecommendationDates = (record, index, paths, value) => { paths.forEach(path => stagePath(record, path, index, `${value}T00:00:00.000Z`)); setEditingField(null); };
  const renderRecommendations = (record, index) => groupRecommendations(mergedRecord(record, index, true).recommendations).map((group, groupIndex) => { const datePaths = group.items.filter(({ item }) => hasValue(item?.date)).map(({ itemIndex }) => `recommendations.${itemIndex}.date`), dateKey = `recommendations-${index}-${group.dateKey}-date`, dateEditing = editingField === dateKey, dateModified = datePaths.some(path => pendingEdits[`${path}-${index}`]); return <div className={`rec-mini-card nested-mini-card recommendation-group${group.dateValue ? '' : ' regular-row-group'}`} key={`${group.dateKey}-${groupIndex}`}>{group.dateValue && <div className="editable-date-subtitle" data-edit-field={datePaths[0]} data-edit-fields={datePaths.join(',')}><div className={`nested-subtitle editable-row date-subtitle${dateModified ? ' modified' : ''}`} onClick={() => { if (!dateEditing) { setEditingField(dateKey); setEditValue(toInputDate(group.dateValue)); } }}>{dateEditing ? <div className="edit-field-container" onClick={event => event.stopPropagation()}><BlueDatePicker value={editValue} onSelect={setEditValue} /><div className="edit-actions"><button className="save-btn" onClick={event => { event.stopPropagation(); stageRecommendationDates(record, index, datePaths, editValue); }}>Save</button><button className="cancel-btn" onClick={event => { event.stopPropagation(); setEditingField(null); }}>Cancel</button></div></div> : <><span className="content-value">{formatDate(group.dateValue)}</span><span className="edit-indicator">&#9998;</span></>}</div></div>}{group.items.flatMap(({ item, itemIndex }) => { const source = String(item?.recommendation ?? item?.text ?? item?.value ?? ''); if (!source.trim()) return []; const key = Object.hasOwn(item, 'recommendation') ? 'recommendation' : Object.hasOwn(item, 'text') ? 'text' : 'value', path = `recommendations.${itemIndex}.${key}`; return splitClauses(path, source, true).map((clause, clauseIndex) => renderLeaf({ record, index, path, leafKey: `${path}-${index}-clause-${clauseIndex}`, shown: clause.text, raw: clause.text, label: 'Recommendation', saveValue: next => source.slice(0, clause.start) + String(next).trim() + source.slice(clause.end) })); })}</div>; });
  const fieldRows = (record, field) => { const value = record[field]; if (!hasValue(value)) return []; if (field === 'date') return [{ subtitle: '', value: formatDate(value) }]; if (FIXED_OBJECTS[field]) return FIXED_OBJECTS[field].flatMap(([subpath, label]) => { const child = getAtPath(record[field], subpath); return hasValue(child) ? [{ subtitle: label, value: displayValue(`${field}.${subpath}`, child) }] : []; }); if (field === 'results') return flattenLeaves(value).map(leaf => ({ subtitle: leaf.label, value: /date/i.test(leaf.path.split('.').pop()) ? formatDate(leaf.value) : displayValue(`results.${leaf.path}`, leaf.value) })); if (field === 'recommendations') return groupRecommendations(value).flatMap(group => [...(group.dateValue ? [{ subtitle: 'Date', value: formatDate(group.dateValue) }] : []), ...group.items.flatMap(({ item }) => { const source = String(item?.recommendation ?? item?.text ?? item?.value ?? ''); return splitClauses('recommendations', source, true).map(clause => ({ subtitle: '', value: clause.text })); })]); if (NARRATIVE_FIELDS.has(field)) return splitClauses(field, value).map(clause => { const parsed = parseLabel(clause.text); return { subtitle: parsed.label, value: parsed.value }; }); return [{ subtitle: '', value: displayValue(field, value) }]; };
  const sectionLines = (record, section) => { const lines = [section.title.toUpperCase(), '-'.repeat(40)]; section.fields.forEach(field => { const rows = fieldRows(record, field); if (!rows.length) return; if (FIELD_LABELS[field] !== section.title) lines.push(FIELD_LABELS[field]); let prior = null; rows.forEach((row, index) => { if (row.subtitle && row.subtitle !== prior) lines.push(row.subtitle); lines.push(`${index + 1}. ${row.value}`); prior = row.subtitle; }); }); return lines; };
  const renderSection = (record, index, section) => { const merged = mergedRecord(record, index, true); if (!section.fields.some(field => hasValue(merged[field]))) return null; const body = section.fields.flatMap(field => { if (!hasValue(merged[field])) return []; if (FIXED_OBJECTS[field]) return renderFixedObject(record, index, field); if (field === 'results') return renderResults(record, index); if (field === 'recommendations') return renderRecommendations(record, index); if (NARRATIVE_FIELDS.has(field)) return renderNarrative(record, index, field, section.title); return [renderScalar(record, index, field, FIELD_LABELS[field], section.title)]; }).filter(Boolean); const copyId = `${section.id}-${index}`, pending = sectionPending(section, index), approved = approvedSections[copyId]; return <section className="section" key={section.id}><div className="mini-cards-container"><div className="section-header"><h3 className="section-title">{section.title}</h3><div className="header-right-actions"><button className={`copy-btn ${copied === copyId ? 'copied' : ''}`} onClick={() => copyText(sectionLines(merged, section).join('\n'), copyId)}>{copied === copyId ? 'Copied!' : 'Copy Section'}</button>{pending && <button className="approve-btn pending" disabled={approving} onClick={() => approveSection(record, index, section)}>Pending Approve</button>}{approved && !pending && <span className="approve-btn approved">Approved</span>}</div></div>{body}</div></section>; };
  const allText = (record, index) => { const merged = mergedRecord(record, index, true), lines = [`AUTOANTIBODY PROFILE ${index + 1}`, '='.repeat(40)]; SECTIONS.forEach(section => { const output = sectionLines(merged, section); if (output.length > 2) lines.push('', ...output); }); return lines.join('\n'); };
  const filtered = useMemo(() => { const query = searchTerm.trim().toLowerCase(), values = records.map((record, index) => ({ record, index })); return query ? values.filter(({ record, index }) => JSON.stringify(mergedRecord(record, index, true)).toLowerCase().includes(query) || 'autoantibody profile'.includes(query)) : values; }, [records, searchTerm, mergedRecord]);
  if (!records.length) return <article className="autoantibody-profile-document"><div className="empty-state">No autoantibody profile data available.</div></article>;
  return <article className="autoantibody-profile-document"><header className="document-header"><h1 className="document-title">Autoantibody Profile</h1><div className="header-actions"><button className={`copy-btn ${copied === 'all' ? 'copied' : ''}`} onClick={() => copyText(records.map(allText).join('\n\n'), 'all')}>{copied === 'all' ? 'Copied!' : 'Copy All'}</button><PDFDownloadLink document={<AutoantibodyProfileDocumentPDFTemplate document={pdfData} />} fileName="Autoantibody_Profile.pdf" className="copy-btn pdf-btn">{({ loading }) => loading ? 'Preparing...' : 'Export PDF'}</PDFDownloadLink></div></header><div className="search-container"><input className="search-input" value={searchTerm} onChange={event => setSearchTerm(event.target.value)} placeholder="Search autoantibody profiles..." />{searchTerm && <button className="clear-search" onClick={() => setSearchTerm('')}>×</button>}</div><div className="records-container">{!filtered.length ? <div className="empty-state">No records match your search.</div> : filtered.map(({ record, index }) => <div className="record-card" key={recordIdOf(record) || index}><div className="record-header"><h2 className="record-name">Autoantibody Profile {index + 1}</h2></div>{SECTIONS.map(section => renderSection(record, index, section))}</div>)}</div></article>;
};

export { COMMA_ARRAY_FIELDS, COMMA_SPLIT_FIELDS, splitClauses };
export default AutoantibodyProfileDocument;
