import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';
import WellnessVisitDocumentationDocumentPDFTemplate from '../pdf-templates/WellnessVisitDocumentationDocumentPDFTemplate';
import BlueDatePicker from '../components/BlueDatePicker';
import BlueSelect from '../components/BlueSelect';
import secureApiClient from '../../../services/secureApiClient';
import './WellnessVisitDocumentationDocument.css';

const DRAFT_KEY = 'wellness_visit_documentationPendingEdits';
const readDrafts = () => { try { return JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}') || {}; } catch { return {}; } };
const writeDrafts = store => { try { if (store && Object.keys(store).length) localStorage.setItem(DRAFT_KEY, JSON.stringify(store)); else localStorage.removeItem(DRAFT_KEY); } catch { /* best effort */ } };

const SECTION_TITLES = {
  'visit-vitals': 'Visit & Vitals',
  'immunizations-screenings': 'Immunizations & Screenings',
  'health-maintenance': 'Health Maintenance',
  'history-directives': 'History & Directives',
  'screening-scores-plan': 'Screening Scores & Plan',
};
const FIELD_LABELS = {
  date: 'Visit Date', visitType: 'Visit Type', ageAtVisit: 'Age at Visit', heightInCm: 'Height (cm)', weightInKg: 'Weight (kg)', bodyMassIndex: 'BMI', bloodPressureSystolic: 'BP Systolic', bloodPressureDiastolic: 'BP Diastolic', vitalSignsDateTime: 'Vital Signs Date/Time',
  immunizationsAdministered: 'Immunizations Administered', immunizationsDeclined: 'Immunizations Declined', screeningsPerformed: 'Screenings Performed', developmentalMilestones: 'Developmental Milestones',
  healthMaintenanceItemsDue: 'Health Maintenance Items Due', healthMaintenanceItemsCompleted: 'Health Maintenance Items Completed', chronicConditionsReviewed: 'Chronic Conditions Reviewed', currentMedicationsList: 'Current Medications List', medicationReconciliationCompleted: 'Medication Reconciliation Completed',
  familyHistoryUpdated: 'Family History Updated', socialHistoryUpdated: 'Social History Updated', advanceDirectivesDiscussed: 'Advance Directives Discussed', functionalStatusAssessment: 'Functional Status Assessment',
  fallRiskScore: 'Fall Risk Score', depressionScreeningScore: 'Depression Screening Score', laboratoriesOrdered: 'Laboratories Ordered', counselingProvided: 'Counseling Provided',
};
const SECTION_FIELDS = {
  'visit-vitals': ['date', 'visitType', 'ageAtVisit', 'heightInCm', 'weightInKg', 'bodyMassIndex', 'bloodPressureSystolic', 'bloodPressureDiastolic', 'vitalSignsDateTime'],
  'immunizations-screenings': ['immunizationsAdministered', 'immunizationsDeclined', 'screeningsPerformed', 'developmentalMilestones'],
  'health-maintenance': ['healthMaintenanceItemsDue', 'healthMaintenanceItemsCompleted', 'chronicConditionsReviewed', 'currentMedicationsList', 'medicationReconciliationCompleted'],
  'history-directives': ['familyHistoryUpdated', 'socialHistoryUpdated', 'advanceDirectivesDiscussed', 'functionalStatusAssessment'],
  'screening-scores-plan': ['fallRiskScore', 'depressionScreeningScore', 'laboratoriesOrdered', 'counselingProvided'],
};
const DATE_FIELDS = new Set(['date', 'vitalSignsDateTime']);
const NUMBER_FIELDS = new Set(['ageAtVisit', 'heightInCm', 'weightInKg', 'bodyMassIndex', 'bloodPressureSystolic', 'bloodPressureDiastolic', 'fallRiskScore', 'depressionScreeningScore']);
const MEANINGFUL_ZERO_FIELDS = new Set(['fallRiskScore', 'depressionScreeningScore']);
const BOOLEAN_FIELDS = new Set(['medicationReconciliationCompleted', 'familyHistoryUpdated', 'socialHistoryUpdated', 'advanceDirectivesDiscussed']);
const ARRAY_FIELDS = new Set(['immunizationsAdministered', 'immunizationsDeclined', 'screeningsPerformed', 'developmentalMilestones', 'healthMaintenanceItemsDue', 'healthMaintenanceItemsCompleted', 'chronicConditionsReviewed', 'currentMedicationsList', 'laboratoriesOrdered', 'counselingProvided']);
const COMMA_ARRAY_FIELDS = new Set(['counselingProvided']);
const COMMA_STRING_FIELDS = new Set(['functionalStatusAssessment']);

const hasVal = value => value !== null && value !== undefined && value !== '' && (!Array.isArray(value) || value.some(hasVal));
const safeId = record => !record?._id ? null : typeof record._id === 'string' ? record._id : record._id.$oid || String(record._id);
const coerceBool = value => { if (typeof value === 'boolean') return value; if (value === null || value === undefined || value === '') return null; if (typeof value === 'string') return !['false', 'no', '0'].includes(value.trim().toLowerCase()); return Boolean(value); };
const formatDate = value => { if (!value) return ''; try { return new Date(value.$date || value).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }); } catch { return String(value); } };
const toInputDate = value => { if (!value) return ''; try { return new Date(value.$date || value).toISOString().slice(0, 10); } catch { return ''; } };
const parseLabel = value => { const text = String(value || ''); const match = text.match(/^([^:]{1,60}):\s+(.+)$/); return match ? { label: match[1].trim(), content: match[2].trim() } : { label: '', content: text }; };
const splitByComma = value => { const rows = []; let current = '', depth = 0; for (const char of String(value || '')) { if (char === '(') depth += 1; if (char === ')') depth = Math.max(0, depth - 1); if (char === ',' && depth === 0) { if (current.trim()) rows.push(current.trim()); current = ''; } else current += char; } if (current.trim()) rows.push(current.trim()); return rows; };
const splitBySentence = value => String(value || '').split(/;\s+|(?<!\d)\.(?:\s+|$)/).map(row => row.trim()).filter(row => row && !/^[;.,!?]+$/.test(row));
const splitString = (field, value) => COMMA_STRING_FIELDS.has(field) ? splitBySentence(value).flatMap(sentence => { const parsed = parseLabel(sentence); const clauses = splitByComma(parsed.content); return clauses.map(clause => ({ subtitle: parsed.label, value: clause })); }) : [{ subtitle: '', value: String(value || '').trim() }];
const fieldShows = (field, value) => hasVal(value) && !(NUMBER_FIELDS.has(field) && Number(value) === 0 && !MEANINGFUL_ZERO_FIELDS.has(field));

const WellnessVisitDocumentationDocument = ({ document: documentProp, data: dataProp, templateData }) => {
  const [searchTerm, setSearchTerm] = useState(''); const [copiedSection, setCopiedSection] = useState(null); const [copiedItems, setCopiedItems] = useState({}); const [showCopied, setShowCopied] = useState(false);
  const [localEdits, setLocalEdits] = useState({}); const [pendingEdits, setPendingEdits] = useState({}); const [editedFields, setEditedFields] = useState({}); const [editingField, setEditingField] = useState(null); const [editValue, setEditValue] = useState(''); const [approvedSections, setApprovedSections] = useState({}); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState(null); const containerRef = useRef(null);

  const records = useMemo(() => { const source = documentProp ?? dataProp ?? templateData; if (!source) return []; let rows = Array.isArray(source) ? source : [source]; rows = rows.flatMap(row => { if (Array.isArray(row?.records)) return row.records; if (Array.isArray(row?._records)) return row._records; if (row?.wellness_visit_documentation) return Array.isArray(row.wellness_visit_documentation) ? row.wellness_visit_documentation : [row.wellness_visit_documentation]; if (row?.documentData) { const nested = row.documentData; if (Array.isArray(nested)) return nested; if (nested?.wellness_visit_documentation) return Array.isArray(nested.wellness_visit_documentation) ? nested.wellness_visit_documentation : [nested.wellness_visit_documentation]; return [nested]; } return [row]; }); return rows.filter(row => row && typeof row === 'object'); }, [documentProp, dataProp, templateData]);
  const getValue = useCallback((record, field, index) => localEdits[`${field}-${index}`] !== undefined ? localEdits[`${field}-${index}`] : record[field], [localEdits]);

  useEffect(() => { const store = readDrafts(), nextLocal = {}, nextPending = {}, nextEdited = {}; records.forEach((record, recordIndex) => { Object.entries(store[safeId(record)] || {}).forEach(([part, value]) => { const match = part.match(/^(.+)\.(\d+)$/); if (match && ARRAY_FIELDS.has(match[1])) { const field = match[1], arrayIndex = Number(match[2]), key = `${field}-${recordIndex}`, current = nextLocal[key] || [...(record[field] || [])]; current[arrayIndex] = value; nextLocal[key] = current; nextPending[key] = true; nextEdited[`${part}-${recordIndex}`] = true; } else { nextLocal[`${part}-${recordIndex}`] = value; nextPending[`${part}-${recordIndex}`] = true; nextEdited[`${part}-${recordIndex}`] = true; } }); }); if (!Object.keys(nextPending).length) return; /* eslint-disable react-hooks/set-state-in-effect */ setLocalEdits(previous => ({ ...nextLocal, ...previous })); setPendingEdits(previous => ({ ...nextPending, ...previous })); setEditedFields(previous => ({ ...nextEdited, ...previous })); /* eslint-enable react-hooks/set-state-in-effect */ }, [records]);

  const resetApproval = useCallback((section, index) => setApprovedSections(previous => { const key = `${section}-${index}`; if (!previous[key]) return previous; const next = { ...previous }; delete next[key]; return next; }), []);
  const stageField = useCallback((record, field, recordIndex, section, value) => { const id = safeId(record); if (!id) return; const key = `${field}-${recordIndex}`; setLocalEdits(previous => ({ ...previous, [key]: value })); setPendingEdits(previous => ({ ...previous, [key]: true })); setEditedFields(previous => ({ ...previous, [key]: true })); resetApproval(section, recordIndex); const store = readDrafts(); store[id] = { ...(store[id] || {}), [field]: value }; writeDrafts(store); setEditingField(null); setEditValue(''); }, [resetApproval]);
  const stageArray = useCallback((record, field, recordIndex, section, arrayIndex, value) => { const id = safeId(record); if (!id) return; const current = [...(getValue(record, field, recordIndex) || [])]; current[arrayIndex] = value; const key = `${field}-${recordIndex}`, part = `${field}.${arrayIndex}`; setLocalEdits(previous => ({ ...previous, [key]: current })); setPendingEdits(previous => ({ ...previous, [key]: true })); setEditedFields(previous => ({ ...previous, [`${part}-${recordIndex}`]: true })); resetApproval(section, recordIndex); const store = readDrafts(); store[id] = { ...(store[id] || {}), [part]: value }; writeDrafts(store); setEditingField(null); setEditValue(''); }, [getValue, resetApproval]);
  const sectionHasEdits = useCallback((section, index) => SECTION_FIELDS[section].some(field => pendingEdits[`${field}-${index}`]), [pendingEdits]);
  const approve = useCallback(async (record, section, index) => { const id = safeId(record); if (!id) return; setSaving(true); setSaveError(null); try { const store = readDrafts(), drafts = store[id] || {}, committed = []; for (const [part, value] of Object.entries(drafts)) { const match = part.match(/^(.+)\.(\d+)$/), field = match && ARRAY_FIELDS.has(match[1]) ? match[1] : part; if (!SECTION_FIELDS[section].includes(field)) continue; const response = await secureApiClient.put(`/api/edit/wellness_visit_documentation/${id}/edit`, { field: part, value }); if (response?.success === false) throw new Error(response.error || 'Save failed'); committed.push(part); } await secureApiClient.put(`/api/edit/wellness_visit_documentation/${id}/approve`, { sectionId: section, approved: true }); setPendingEdits(previous => { const next = { ...previous }; SECTION_FIELDS[section].forEach(field => delete next[`${field}-${index}`]); return next; }); committed.forEach(part => delete drafts[part]); if (Object.keys(drafts).length) store[id] = drafts; else delete store[id]; writeDrafts(store); setApprovedSections(previous => ({ ...previous, [`${section}-${index}`]: true })); } catch (error) { console.error(error); setSaveError('Approve failed. Please try again.'); } finally { setSaving(false); } }, []);

  const copyText = useCallback(async text => { try { await navigator.clipboard.writeText(text); return true; } catch { const area = window.document.createElement('textarea'); area.value = text; area.style.position = 'absolute'; area.style.left = '-9999px'; (containerRef.current || window.document.body).appendChild(area); area.select(); window.document.execCommand('copy'); area.remove(); return true; } }, []);
  const rowsFor = useCallback((field, value) => { if (DATE_FIELDS.has(field)) return [{ subtitle: '', value: formatDate(value) }]; if (BOOLEAN_FIELDS.has(field)) return [{ subtitle: '', value: coerceBool(value) ? 'Yes' : 'No' }]; if (NUMBER_FIELDS.has(field)) return [{ subtitle: '', value: String(value) }]; if (ARRAY_FIELDS.has(field)) return (Array.isArray(value) ? value : []).flatMap(item => { const parsed = parseLabel(item), clauses = COMMA_ARRAY_FIELDS.has(field) ? splitByComma(parsed.content) : [parsed.content]; return clauses.map(clause => ({ subtitle: parsed.label, value: clause })); }); return splitString(field, value); }, []);
  const sectionCopy = useCallback((record, index, section) => { let text = `${SECTION_TITLES[section]}\n${'='.repeat(40)}\n\n`; SECTION_FIELDS[section].forEach(field => { const value = getValue(record, field, index); if (!fieldShows(field, value)) return; text += `${FIELD_LABELS[field]}\n${'-'.repeat(40)}\n`; let previousSubtitle = ''; rowsFor(field, value).forEach((row, rowIndex) => { if (row.subtitle && row.subtitle !== previousSubtitle) text += `${row.subtitle}\n`; text += `${rowIndex + 1}. ${row.value}\n`; previousSubtitle = row.subtitle || ''; }); text += '\n'; }); return text; }, [getValue, rowsFor]);
  const copyAll = useCallback(async () => { let text = `WELLNESS VISIT DOCUMENTATION\n${'='.repeat(40)}\n\n`; records.forEach((record, index) => { text += `Wellness Visit Documentation ${index + 1}\n${'='.repeat(40)}\n\n`; Object.keys(SECTION_FIELDS).forEach(section => { text += sectionCopy(record, index, section); }); }); if (await copyText(text)) { setShowCopied(true); setTimeout(() => setShowCopied(false), 2000); } }, [copyText, records, sectionCopy]);
  const highlight = useCallback(value => { if (!searchTerm.trim()) return value; const escaped = searchTerm.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), matcher = new RegExp(`(${escaped})`, 'gi'); return String(value).split(matcher).map((part, index) => matcher.test(part) ? <mark key={index}>{part}</mark> : part); }, [searchTerm]);

  const row = ({ field, recordIndex, key, dataField = field, value, save, type = 'text' }) => { const editing = editingField === key, modified = editedFields[`${dataField}-${recordIndex}`], display = type === 'date' ? formatDate(value) : type === 'boolean' ? (coerceBool(value) ? 'Yes' : 'No') : String(value); return <div key={key} className="editable-leaf" data-edit-field={dataField}><div className={`numbered-row editable-row ${modified ? 'modified' : ''}`} onClick={() => { if (editing) return; setEditingField(key); setEditValue(type === 'date' ? toInputDate(value) : type === 'boolean' ? display : String(value)); setSaveError(null); }}>{editing ? <div className="edit-field-container">{type === 'date' ? <BlueDatePicker value={editValue} onSelect={next => setEditValue(next || '')} /> : type === 'boolean' ? <BlueSelect value={editValue} options={['Yes', 'No']} onChange={next => setEditValue(next)} /> : type === 'number' ? <div className="number-edit-row"><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String((Number(editValue) || 0) - 1)); }}>−</button><input type="text" className="edit-input" value={editValue} onChange={event => setEditValue(event.target.value)} /><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String((Number(editValue) || 0) + 1)); }}>+</button></div> : <textarea className="edit-textarea" value={editValue} onChange={event => setEditValue(event.target.value)} autoFocus />}{saveError && <div className="save-error">{saveError}</div>}<div className="edit-actions"><button className="save-btn" disabled={saving} onClick={event => { event.stopPropagation(); save(type === 'number' ? Number(editValue) : type === 'boolean' ? editValue === 'Yes' : editValue); }}>Save</button><button className="cancel-btn" onClick={event => { event.stopPropagation(); setEditingField(null); setEditValue(''); setSaveError(null); }}>Cancel</button></div></div> : <><div className="row-content"><span className="content-value">{highlight(display)}</span><span className="edit-indicator">&#9998;</span></div><button className={`copy-btn ${copiedItems[key] ? 'copied' : ''}`} onClick={async event => { event.stopPropagation(); if (await copyText(display)) { setCopiedItems(previous => ({ ...previous, [key]: true })); setTimeout(() => setCopiedItems(previous => ({ ...previous, [key]: false })), 2000); } }}>{copiedItems[key] ? 'Copied!' : 'Copy'}</button></>}</div>{modified && <span className="modified-badge">edited - click Pending Approve to save</span>}</div>; };
  const scalar = (record, field, recordIndex, section) => { const value = getValue(record, field, recordIndex); if (!fieldShows(field, value)) return null; const rows = rowsFor(field, value); return <div key={field} className="rec-mini-card nested-mini-card"><div className="nested-subtitle">{FIELD_LABELS[field]}</div>{rows.map((entry, rowIndex) => row({ field, recordIndex, key: `${field}-${recordIndex}-${rowIndex}`, value: entry.value, type: DATE_FIELDS.has(field) ? 'date' : BOOLEAN_FIELDS.has(field) ? 'boolean' : NUMBER_FIELDS.has(field) ? 'number' : 'text', save: next => { if (DATE_FIELDS.has(field) || BOOLEAN_FIELDS.has(field) || NUMBER_FIELDS.has(field) || rows.length === 1) stageField(record, field, recordIndex, section, next); else { const updated = [...rows]; updated[rowIndex] = { ...updated[rowIndex], value: String(next).trim() }; const rebuilt = updated.map(item => `${item.subtitle ? `${item.subtitle}: ` : ''}${item.value}`).filter(Boolean).join('. '); stageField(record, field, recordIndex, section, rebuilt); } } }))}</div>; };
  const arrayField = (record, field, recordIndex, section) => { const items = (getValue(record, field, recordIndex) || []).filter(hasVal); if (!items.length) return null; const groups = []; items.forEach((item, itemIndex) => { const parsed = parseLabel(item), entry = { itemIndex, parsed, clauses: COMMA_ARRAY_FIELDS.has(field) ? splitByComma(parsed.content) : [parsed.content] }; if (parsed.label) groups.push({ label: parsed.label, entries: [entry] }); else { const last = groups[groups.length - 1]; if (last && !last.label) last.entries.push(entry); else groups.push({ label: '', entries: [entry] }); } }); return groups.map((group, groupIndex) => <div key={`${field}-${groupIndex}`} className="rec-mini-card nested-mini-card"><div className="nested-subtitle">{FIELD_LABELS[field]}{group.label ? ` — ${group.label}` : ''}</div>{group.entries.flatMap(entry => entry.clauses.map((clause, clauseIndex) => row({ field, recordIndex, key: `${field}-${recordIndex}-${entry.itemIndex}-${clauseIndex}`, dataField: `${field}.${entry.itemIndex}`, value: clause, save: next => { const updated = [...entry.clauses]; updated[clauseIndex] = String(next).trim(); stageArray(record, field, recordIndex, section, entry.itemIndex, `${entry.parsed.label ? `${entry.parsed.label}: ` : ''}${updated.filter(Boolean).join(', ')}`); } })))}</div>); };

  const matches = useCallback(record => !searchTerm.trim() || JSON.stringify(record).toLowerCase().includes(searchTerm.trim().toLowerCase()), [searchTerm]);
  const pdfData = useMemo(() => records.filter(matches).map((record, index) => { const merged = { ...record }; Object.entries(localEdits).forEach(([key, value]) => { const match = key.match(/^(.+)-(\d+)$/); if (match && Number(match[2]) === index && !pendingEdits[key]) merged[match[1]] = value; }); return merged; }), [localEdits, matches, pendingEdits, records]);

  return <div ref={containerRef} className="wellness-visit-documentation-document"><div className="document-header"><h2 className="document-title">Wellness Visit Documentation</h2><div className="header-actions"><button className={`copy-btn ${showCopied ? 'copied' : ''}`} onClick={copyAll}>{showCopied ? 'Copied!' : 'Copy All'}</button><PDFDownloadLink document={<WellnessVisitDocumentationDocumentPDFTemplate document={pdfData} />} fileName="Wellness_Visit_Documentation.pdf" className="copy-btn">Export PDF</PDFDownloadLink></div></div><div className="search-container"><input className="search-input" type="text" value={searchTerm} onChange={event => setSearchTerm(event.target.value)} placeholder="Search wellness visit documentation..." /></div><div className="records-container">{records.filter(matches).map((record, recordIndex) => <div className="record-card" key={safeId(record) || recordIndex}><div className="record-header"><h3 className="record-name">Wellness Visit Documentation {recordIndex + 1}</h3></div>{Object.keys(SECTION_FIELDS).map(section => { const fields = SECTION_FIELDS[section]; if (!fields.some(field => fieldShows(field, getValue(record, field, recordIndex)))) return null; const copyId = `${section}-${recordIndex}`, hasEdits = sectionHasEdits(section, recordIndex); return <section className="section" key={section}><div className="mini-cards-container"><div className="section-header"><h4 className="section-title">{SECTION_TITLES[section]}</h4><div className="header-right-actions"><button className={`copy-btn ${copiedSection === copyId ? 'copied' : ''}`} onClick={async () => { if (await copyText(sectionCopy(record, recordIndex, section))) { setCopiedSection(copyId); setTimeout(() => setCopiedSection(null), 2000); } }}>{copiedSection === copyId ? 'Copied!' : 'Copy Section'}</button>{hasEdits && <button className="approve-btn pending" disabled={saving} onClick={() => approve(record, section, recordIndex)}>Pending Approve</button>}{approvedSections[copyId] && !hasEdits && <span className="approve-btn approved">Approved</span>}</div></div>{fields.map(field => ARRAY_FIELDS.has(field) ? arrayField(record, field, recordIndex, section) : scalar(record, field, recordIndex, section))}</div></section>; })}</div>)}</div>{!records.length && <div className="empty-state">No wellness visit documentation available</div>}</div>;
};

export default WellnessVisitDocumentationDocument;
