import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';
import WellChildSummaryDocumentPDFTemplate from '../pdf-templates/WellChildSummaryDocumentPDFTemplate';
import BlueDatePicker from '../components/BlueDatePicker';
import secureApiClient from '../../../services/secureApiClient';
import './WellChildSummaryDocument.css';

const DRAFT_KEY = 'well_child_summaryPendingEdits';
const readDrafts = () => { try { return JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}') || {}; } catch { return {}; } };
const writeDrafts = store => { try { if (store && Object.keys(store).length) localStorage.setItem(DRAFT_KEY, JSON.stringify(store)); else localStorage.removeItem(DRAFT_KEY); } catch { /* best effort */ } };

const SECTION_TITLES = {
  'visit-info': 'Visit Information', growth: 'Growth Percentile Overview',
  'vaccines-administered': 'Vaccines Administered', 'vaccines-due': 'Vaccines Due',
  'developmental-milestones': 'Developmental Milestones', screenings: 'Screenings',
  nutrition: 'Nutrition Counseling', 'safety-guidance': 'Safety Guidance',
  'parental-concerns': 'Parental Concerns', 'next-visit': 'Next Visit',
};
const FIELD_LABELS = {
  date: 'Visit Date', provider: 'Provider', facility: 'Facility', childAge: 'Child Age', dateOfBirth: 'Date of Birth', gestationalAgeAtBirth: 'Gestational Age at Birth',
  weightMeasurement: 'Weight (kg)', weightPercentile: 'Weight Percentile', heightMeasurement: 'Height (cm)', heightPercentile: 'Height Percentile', headCircumference: 'Head Circumference (cm)', headCircumferencePercentile: 'Head Circumference Percentile', bodyMassIndex: 'BMI', bmiPercentile: 'BMI Percentile',
  vaccinesAdministered: 'Vaccines Administered', vaccinesDue: 'Vaccines Due', developmentalMilestones: 'Developmental Milestones', visionScreeningResult: 'Vision Screening', hearingScreeningResult: 'Hearing Screening', hemoglobinLevel: 'Hemoglobin Level', leadScreeningResult: 'Lead Screening', nutritionCounseling: 'Nutrition Counseling', safetyGuidanceProvided: 'Safety Guidance', parentalConcerns: 'Parental Concerns', nextVisitScheduled: 'Next Visit Scheduled',
};
const SECTION_FIELDS = {
  'visit-info': ['date', 'provider', 'facility', 'childAge', 'dateOfBirth', 'gestationalAgeAtBirth'],
  growth: ['weightMeasurement', 'weightPercentile', 'heightMeasurement', 'heightPercentile', 'headCircumference', 'headCircumferencePercentile', 'bodyMassIndex', 'bmiPercentile'],
  'vaccines-administered': ['vaccinesAdministered'], 'vaccines-due': ['vaccinesDue'], 'developmental-milestones': ['developmentalMilestones'],
  screenings: ['visionScreeningResult', 'hearingScreeningResult', 'hemoglobinLevel', 'leadScreeningResult'], nutrition: ['nutritionCounseling'],
  'safety-guidance': ['safetyGuidanceProvided'], 'parental-concerns': ['parentalConcerns'], 'next-visit': ['nextVisitScheduled'],
};
const DATE_FIELDS = new Set(['date', 'dateOfBirth']);
const NUMBER_FIELDS = new Set(['weightMeasurement', 'weightPercentile', 'heightMeasurement', 'heightPercentile', 'headCircumference', 'headCircumferencePercentile', 'bodyMassIndex', 'bmiPercentile', 'hemoglobinLevel']);
const ZERO_SENTINEL_FIELDS = new Set(['weightMeasurement', 'heightMeasurement', 'headCircumference', 'headCircumferencePercentile', 'bodyMassIndex', 'hemoglobinLevel']);
const ARRAY_FIELDS = new Set(['vaccinesAdministered', 'vaccinesDue', 'developmentalMilestones', 'safetyGuidanceProvided', 'parentalConcerns']);
const COMMA_STRING_FIELDS = new Set(['nutritionCounseling']);
const COMMA_ARRAY_FIELDS = new Set(['safetyGuidanceProvided']);

const hasVal = value => value !== null && value !== undefined && value !== '' && (!Array.isArray(value) || value.some(hasVal));
const safeId = record => !record?._id ? null : typeof record._id === 'string' ? record._id : record._id.$oid || String(record._id);
const formatDate = value => { if (!value) return ''; try { return new Date(value.$date || value).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }); } catch { return String(value); } };
const toInputDate = value => { if (!value) return ''; try { return new Date(value.$date || value).toISOString().slice(0, 10); } catch { return ''; } };
const parseLabel = value => { const text = String(value || ''); const match = text.match(/^([^:]{1,60}):\s+(.+)$/); return match ? { label: match[1].trim(), content: match[2].trim() } : { label: '', content: text }; };
const splitByComma = value => { const rows = []; let current = ''; let depth = 0; for (const char of String(value || '')) { if (char === '(') depth += 1; if (char === ')') depth = Math.max(0, depth - 1); if (char === ',' && depth === 0) { if (current.trim()) rows.push(current.trim()); current = ''; } else current += char; } if (current.trim()) rows.push(current.trim()); return rows; };
const splitBySentence = value => String(value || '').split(/;\s+|(?<!\d)\.(?:\s+|$)/).map(row => row.trim()).filter(row => row && !/^[;.,!?]+$/.test(row));
const splitString = (field, value) => COMMA_STRING_FIELDS.has(field) ? splitBySentence(value).flatMap(splitByComma).filter(Boolean) : [String(value || '').trim()].filter(Boolean);
const fieldShows = (field, value) => hasVal(value) && !(NUMBER_FIELDS.has(field) && ZERO_SENTINEL_FIELDS.has(field) && Number(value) === 0);

const WellChildSummaryDocument = ({ document: documentProp, data: dataProp, templateData }) => {
  const [searchTerm, setSearchTerm] = useState(''); const [copiedSection, setCopiedSection] = useState(null); const [copiedItems, setCopiedItems] = useState({}); const [showCopied, setShowCopied] = useState(false);
  const [localEdits, setLocalEdits] = useState({}); const [pendingEdits, setPendingEdits] = useState({}); const [editedFields, setEditedFields] = useState({}); const [editingField, setEditingField] = useState(null); const [editValue, setEditValue] = useState(''); const [approvedSections, setApprovedSections] = useState({}); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState(null); const containerRef = useRef(null);

  const records = useMemo(() => { const source = documentProp ?? dataProp ?? templateData; if (!source) return []; let rows = Array.isArray(source) ? source : [source]; rows = rows.flatMap(row => { if (Array.isArray(row?.records)) return row.records; if (Array.isArray(row?._records)) return row._records; if (row?.well_child_summary) return Array.isArray(row.well_child_summary) ? row.well_child_summary : [row.well_child_summary]; if (row?.documentData) { const nested = row.documentData; if (Array.isArray(nested)) return nested; if (nested?.well_child_summary) return Array.isArray(nested.well_child_summary) ? nested.well_child_summary : [nested.well_child_summary]; return [nested]; } return [row]; }); return rows.filter(row => row && typeof row === 'object'); }, [documentProp, dataProp, templateData]);
  const getValue = useCallback((record, field, index) => localEdits[`${field}-${index}`] !== undefined ? localEdits[`${field}-${index}`] : record[field], [localEdits]);

  useEffect(() => { const store = readDrafts(); const nextLocal = {}, nextPending = {}, nextEdited = {}; records.forEach((record, recordIndex) => { Object.entries(store[safeId(record)] || {}).forEach(([part, value]) => { const match = part.match(/^(.+)\.(\d+)$/); if (match && ARRAY_FIELDS.has(match[1])) { const base = match[1], arrayIndex = Number(match[2]), key = `${base}-${recordIndex}`, current = nextLocal[key] || [...(record[base] || [])]; current[arrayIndex] = value; nextLocal[key] = current; nextPending[key] = true; nextEdited[`${part}-${recordIndex}`] = true; } else { nextLocal[`${part}-${recordIndex}`] = value; nextPending[`${part}-${recordIndex}`] = true; nextEdited[`${part}-${recordIndex}`] = true; } }); }); if (!Object.keys(nextPending).length) return; /* eslint-disable react-hooks/set-state-in-effect */ setLocalEdits(previous => ({ ...nextLocal, ...previous })); setPendingEdits(previous => ({ ...nextPending, ...previous })); setEditedFields(previous => ({ ...nextEdited, ...previous })); /* eslint-enable react-hooks/set-state-in-effect */ }, [records]);

  const stageField = useCallback((record, field, recordIndex, value) => { const id = safeId(record); if (!id) return; const key = `${field}-${recordIndex}`; setLocalEdits(previous => ({ ...previous, [key]: value })); setPendingEdits(previous => ({ ...previous, [key]: true })); setEditedFields(previous => ({ ...previous, [key]: true })); const store = readDrafts(); store[id] = { ...(store[id] || {}), [field]: value }; writeDrafts(store); setEditingField(null); setEditValue(''); }, []);
  const stageArray = useCallback((record, field, recordIndex, arrayIndex, value) => { const id = safeId(record); if (!id) return; const current = [...(getValue(record, field, recordIndex) || [])]; current[arrayIndex] = value; const baseKey = `${field}-${recordIndex}`, part = `${field}.${arrayIndex}`; setLocalEdits(previous => ({ ...previous, [baseKey]: current })); setPendingEdits(previous => ({ ...previous, [baseKey]: true })); setEditedFields(previous => ({ ...previous, [`${part}-${recordIndex}`]: true })); const store = readDrafts(); store[id] = { ...(store[id] || {}), [part]: value }; writeDrafts(store); setEditingField(null); setEditValue(''); }, [getValue]);
  const sectionHasEdits = useCallback((section, index) => SECTION_FIELDS[section].some(field => pendingEdits[`${field}-${index}`]), [pendingEdits]);
  const approve = useCallback(async (record, section, index) => { const id = safeId(record); if (!id) return; setSaving(true); setSaveError(null); try { const store = readDrafts(), drafts = store[id] || {}, committed = []; for (const [part, value] of Object.entries(drafts)) { const match = part.match(/^(.+)\.(\d+)$/), base = match && ARRAY_FIELDS.has(match[1]) ? match[1] : part; if (!SECTION_FIELDS[section].includes(base)) continue; const response = await secureApiClient.put(`/api/edit/well_child_summary/${id}/edit`, { field: part, value }); if (response?.success === false) throw new Error(response.error || 'Save failed'); committed.push(part); } await secureApiClient.put(`/api/edit/well_child_summary/${id}/approve`, { sectionId: section, approved: true }); setPendingEdits(previous => { const next = { ...previous }; SECTION_FIELDS[section].forEach(field => delete next[`${field}-${index}`]); return next; }); committed.forEach(part => delete drafts[part]); if (Object.keys(drafts).length) store[id] = drafts; else delete store[id]; writeDrafts(store); setApprovedSections(previous => ({ ...previous, [`${section}-${index}`]: true })); } catch (error) { console.error(error); setSaveError('Save failed. Please try again.'); } finally { setSaving(false); } }, []);

  const copyText = useCallback(async text => { try { await navigator.clipboard.writeText(text); return true; } catch { const area = window.document.createElement('textarea'); area.value = text; area.style.position = 'absolute'; area.style.left = '-9999px'; (containerRef.current || window.document.body).appendChild(area); area.select(); window.document.execCommand('copy'); area.remove(); return true; } }, []);
  const rowsFor = useCallback((field, value) => { if (DATE_FIELDS.has(field)) return [{ value: formatDate(value) }]; if (ARRAY_FIELDS.has(field)) return (Array.isArray(value) ? value : []).flatMap(item => { const parsed = parseLabel(item), clauses = COMMA_ARRAY_FIELDS.has(field) ? splitByComma(parsed.content) : [parsed.content]; return clauses.map(clause => ({ subtitle: parsed.label, value: clause })); }); if (NUMBER_FIELDS.has(field)) return [{ value: String(value) }]; return splitString(field, value).map(row => ({ value: row })); }, []);
  const sectionCopy = useCallback((record, index, section) => { let text = `${SECTION_TITLES[section]}\n${'='.repeat(40)}\n\n`; SECTION_FIELDS[section].forEach(field => { const value = getValue(record, field, index); if (!fieldShows(field, value)) return; text += `${FIELD_LABELS[field]}\n${'-'.repeat(40)}\n`; let previousSubtitle = ''; rowsFor(field, value).forEach((row, rowIndex) => { if (row.subtitle && row.subtitle !== previousSubtitle) text += `${row.subtitle}\n`; text += `${rowIndex + 1}. ${row.value}\n`; previousSubtitle = row.subtitle || ''; }); text += '\n'; }); return text; }, [getValue, rowsFor]);
  const copyAll = useCallback(async () => { let text = `WELL CHILD SUMMARY\n${'='.repeat(40)}\n\n`; records.forEach((record, index) => { text += `Well Child Summary ${index + 1}\n${'='.repeat(40)}\n\n`; Object.keys(SECTION_FIELDS).forEach(section => { text += sectionCopy(record, index, section); }); }); if (await copyText(text)) { setShowCopied(true); setTimeout(() => setShowCopied(false), 2000); } }, [copyText, records, sectionCopy]);
  const highlight = useCallback(value => { if (!searchTerm.trim()) return value; const escaped = searchTerm.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), matcher = new RegExp(`(${escaped})`, 'gi'); return String(value).split(matcher).map((part, index) => matcher.test(part) ? <mark key={index}>{part}</mark> : part); }, [searchTerm]);

  const row = ({ field, recordIndex, key, dataField = field, value, save, type = 'text' }) => { const editing = editingField === key, modified = editedFields[`${dataField}-${recordIndex}`]; return <div key={key} className="editable-leaf" data-edit-field={dataField}><div className={`numbered-row editable-row ${modified ? 'modified' : ''}`} onClick={() => { if (editing) return; setEditingField(key); setEditValue(type === 'date' ? toInputDate(value) : String(value)); setSaveError(null); }}>{editing ? <div className="edit-field-container">{type === 'date' ? <BlueDatePicker value={editValue} onSelect={next => setEditValue(next || '')} /> : type === 'number' ? <div className="number-edit-row"><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String((Number(editValue) || 0) - 1)); }}>−</button><input type="text" className="edit-input" value={editValue} onChange={event => setEditValue(event.target.value)} /><button type="button" className="num-step" onClick={event => { event.stopPropagation(); setEditValue(String((Number(editValue) || 0) + 1)); }}>+</button></div> : <textarea className="edit-textarea" value={editValue} onChange={event => setEditValue(event.target.value)} autoFocus />}{saveError && <div className="save-error">{saveError}</div>}<div className="edit-actions"><button className="save-btn" disabled={saving} onClick={event => { event.stopPropagation(); save(type === 'number' ? Number(editValue) : editValue); }}>Save</button><button className="cancel-btn" onClick={event => { event.stopPropagation(); setEditingField(null); setEditValue(''); setSaveError(null); }}>Cancel</button></div></div> : <><div className="row-content"><span className="content-value">{highlight(type === 'date' ? formatDate(value) : value)}</span><span className="edit-indicator">&#9998;</span></div><button className={`copy-btn ${copiedItems[key] ? 'copied' : ''}`} onClick={async event => { event.stopPropagation(); if (await copyText(type === 'date' ? formatDate(value) : String(value))) { setCopiedItems(previous => ({ ...previous, [key]: true })); setTimeout(() => setCopiedItems(previous => ({ ...previous, [key]: false })), 2000); } }}>{copiedItems[key] ? 'Copied!' : 'Copy'}</button></>}</div>{modified && <span className="modified-badge">edited - click Pending Approve to save</span>}</div>; };
  const scalar = (record, field, recordIndex, section) => { const value = getValue(record, field, recordIndex); if (!fieldShows(field, value)) return null; const clauses = DATE_FIELDS.has(field) || NUMBER_FIELDS.has(field) ? [value] : splitString(field, String(value)); const showLabel = FIELD_LABELS[field].toLowerCase() !== SECTION_TITLES[section].toLowerCase(); return <div key={field} className="rec-mini-card nested-mini-card">{showLabel && <div className="nested-subtitle">{FIELD_LABELS[field]}</div>}{clauses.map((clause, clauseIndex) => row({ record, field, recordIndex, key: `${field}-${recordIndex}-${clauseIndex}`, value: clause, type: DATE_FIELDS.has(field) ? 'date' : NUMBER_FIELDS.has(field) ? 'number' : 'text', save: next => { if (DATE_FIELDS.has(field) || NUMBER_FIELDS.has(field)) stageField(record, field, recordIndex, next); else { const updated = [...clauses]; updated[clauseIndex] = String(next).trim(); stageField(record, field, recordIndex, updated.filter(Boolean).join(COMMA_STRING_FIELDS.has(field) ? '; ' : '. ')); } } }))}</div>; };
  const arrayField = (record, field, recordIndex) => { const items = (getValue(record, field, recordIndex) || []).filter(hasVal); if (!items.length) return null; const groups = []; items.forEach((item, itemIndex) => { const parsed = parseLabel(item), entry = { itemIndex, parsed, clauses: COMMA_ARRAY_FIELDS.has(field) ? splitByComma(parsed.content) : [parsed.content] }; if (parsed.label) groups.push({ label: parsed.label, entries: [entry] }); else { const last = groups[groups.length - 1]; if (last && !last.label) last.entries.push(entry); else groups.push({ label: '', entries: [entry] }); } }); return groups.map((group, groupIndex) => <div key={`${field}-${groupIndex}`} className="rec-mini-card nested-mini-card">{group.label && <div className="nested-subtitle">{group.label}</div>}{group.entries.flatMap(entry => entry.clauses.map((clause, clauseIndex) => row({ record, field, recordIndex, key: `${field}-${recordIndex}-${entry.itemIndex}-${clauseIndex}`, dataField: `${field}.${entry.itemIndex}`, value: clause, save: next => { const updated = [...entry.clauses]; updated[clauseIndex] = String(next).trim(); stageArray(record, field, recordIndex, entry.itemIndex, `${entry.parsed.label ? `${entry.parsed.label}: ` : ''}${updated.filter(Boolean).join(', ')}`); } })))}</div>); };

  const matches = useCallback(record => !searchTerm.trim() || JSON.stringify(record).toLowerCase().includes(searchTerm.trim().toLowerCase()), [searchTerm]);
  const pdfData = useMemo(() => records.filter(matches).map((record, index) => { const merged = { ...record }; Object.entries(localEdits).forEach(([key, value]) => { const match = key.match(/^(.+)-(\d+)$/); if (match && Number(match[2]) === index && !pendingEdits[key]) merged[match[1]] = value; }); return merged; }), [localEdits, matches, pendingEdits, records]);

  return <div ref={containerRef} className="well-child-summary-document"><div className="document-header"><h2 className="document-title">Well Child Summary</h2><div className="header-actions"><button className={`copy-btn ${showCopied ? 'copied' : ''}`} onClick={copyAll}>{showCopied ? 'Copied!' : 'Copy All'}</button><PDFDownloadLink document={<WellChildSummaryDocumentPDFTemplate document={pdfData} />} fileName="Well_Child_Summary.pdf" className="copy-btn">Export PDF</PDFDownloadLink></div></div><div className="search-container"><input className="search-input" type="text" value={searchTerm} onChange={event => setSearchTerm(event.target.value)} placeholder="Search well child summary..." /></div><div className="records-container">{records.filter(matches).map((record, recordIndex) => <div className="record-card" key={safeId(record) || recordIndex}><div className="record-header"><h3 className="record-name">Well Child Summary {recordIndex + 1}</h3></div>{Object.keys(SECTION_FIELDS).map(section => { const fields = SECTION_FIELDS[section]; if (!fields.some(field => fieldShows(field, getValue(record, field, recordIndex)))) return null; const copyId = `${section}-${recordIndex}`, hasEdits = sectionHasEdits(section, recordIndex); return <section className="section" key={section}><div className="mini-cards-container"><div className="section-header"><h4 className="section-title">{SECTION_TITLES[section]}</h4><div className="header-right-actions"><button className={`copy-btn ${copiedSection === copyId ? 'copied' : ''}`} onClick={async () => { if (await copyText(sectionCopy(record, recordIndex, section))) { setCopiedSection(copyId); setTimeout(() => setCopiedSection(null), 2000); } }}>{copiedSection === copyId ? 'Copied!' : 'Copy Section'}</button>{hasEdits && <button className="approve-btn pending" disabled={saving} onClick={() => approve(record, section, recordIndex)}>Pending Approve</button>}{!hasEdits && approvedSections[copyId] && <span className="approve-btn approved">Approved</span>}</div></div>{fields.map(field => ARRAY_FIELDS.has(field) ? arrayField(record, field, recordIndex) : scalar(record, field, recordIndex, section))}</div></section>; })}</div>)}{!records.filter(matches).length && <div className="no-data">No summary data available</div>}</div></div>;
};

export default WellChildSummaryDocument;
