/**
 * Collection Descriptions
 *
 * Provides human-readable descriptions for all 850+ medical data collections
 * Used in artifact panel to help differentiate similar-sounding collections
 */

const COLLECTION_DESCRIPTIONS = {
  // Core Medical Records
  "abnormal_results": "Lab or test results flagged as outside normal ranges",
  "admission_assessments": "Initial patient evaluations upon hospital admission",
  "goals_of_care_discussions": "Patient wishes for end-of-life care and medical decisions",
  "allergies": "List of patient allergies and adverse reactions",
  "appointments": "Scheduled medical visits and consultations",
  "consultation_notes": "Specialist evaluations and recommendations",
  "diagnoses": "Medical conditions and disease classifications",
  "discharge_summaries": "Comprehensive reports at end of hospital stay",
  "follow_ups": "Scheduled post-treatment monitoring appointments",
  "imaging_reports": "Radiology and diagnostic imaging results",
  "lab_results": "Laboratory test results and values",
  "medical_alerts": "Critical safety warnings and patient alerts",
  "medical_certificates": "Official documentation for work, school, or legal purposes",
  "medical_procedures": "Invasive and non-invasive medical interventions",
  "medications": "Current and historical medication records",
  "medication_recommendations": "Suggested medication changes or additions",
  "medication_safety": "Drug interaction and safety assessments",
  "medication_safety_alerts": "Critical warnings about medication risks",
  "prescriptions": "Written orders for medications",
  "recommendations": "General medical advice and care suggestions",
  "referrals": "Transfers to specialist care",
  "vaccination_records": "Immunization history and schedules",
  "vital_signs": "Blood pressure, heart rate, temperature, respiratory rate",

  // Hospital & Emergency
  "emergency_discharge_summaries": "Emergency department visit summaries",
  "emergency_reports": "Acute care documentation from ED visits",
  "hospital_admission_notes": "Documentation at time of hospital entry",
  "hospital_discharge_summaries": "Comprehensive inpatient stay summaries",
  "hospital_transfer_notes": "Documentation when moving between facilities",
  "icu_flow_sheets": "Intensive care unit monitoring records",
  "icu_flow_sheet": "Individual ICU monitoring documentation",
  "hourly_vital_signs": "Frequent vital sign measurements in critical care",
  "arterial_blood_gases": "Blood oxygen and acid-base status measurements",
  "continuous_infusions": "IV drip medications and rates",
  "neurological_assessment": "Brain and nervous system evaluations",
  "glasgow_coma_scale": "Consciousness level scoring",
  "cam_icu": "Delirium screening in intensive care",
  "procedures_interventions": "Medical procedures performed during care",
  "nursing_notes": "Nurse observations and care documentation",
  "transfer_summaries": "Patient status when transferring care",
  "treatment_courses": "Therapeutic plans and progress over time",
  "admission_recommendations": "Suggested care plans at hospital entry",

  // Care Coordination
  "case_management": "Coordination of complex care needs",
  "proposed_art_switch": "HIV antiretroviral therapy change proposals",
  "hiv_history": "HIV diagnosis and treatment history",
  "current_opportunistic_infections": "Active infections in immunocompromised patients",
  "food_insecurity": "Nutrition access and support needs",
  "smoking_cessation_program": "Tobacco use cessation interventions",
  "harm_reduction_counseling": "Risk mitigation for substance use",
  "cognitive_behavioral_therapy": "Psychological therapy sessions",
  "support_groups": "Peer support program participation",
  "food_assistance_programs": "Nutritional support resources",
  "appetite_stimulants": "Medications to increase food intake",
  "social_services_programs": "Community resource referrals",
  "immune_reconstitution_planning": "HIV treatment recovery planning",
  "primary_prophylaxis": "Prevention of first infection occurrence",
  "secondary_prophylaxis": "Prevention of infection recurrence",
  "cmv_monitoring_plan": "Cytomegalovirus surveillance strategy",

  // Surgical & Operative
  "anesthesia_records": "Anesthesia administration documentation",
  "operative_reports": "Detailed surgical procedure documentation",
  "operative_report_details": "Supplementary surgical procedure information",
  "patient_positioning": "Surgical positioning and safety measures",
  "prep_and_drape": "Sterile field preparation documentation",
  "pneumoperitoneum": "Abdominal insufflation during laparoscopy",
  "port_placement": "Surgical access port positioning",
  "critical_view_of_safety": "Gallbladder surgery safety verification",
  "intraoperative_cholangiography": "Bile duct imaging during surgery",
  "surgical_steps": "Detailed surgical technique documentation",
  "pathology_gross_description": "Specimen appearance documentation",
  "closure_technique": "Surgical wound closing methods",
  "sponge_instrument_counts": "Surgical safety count verification",
  "operative_time": "Duration of surgical procedures",
  "post_operative_reports": "Immediate post-surgery documentation",
  "pre_operative_assessments": "Surgical readiness evaluations",
  "surgical_consent_forms": "Informed consent for procedures",

  // Cardiology
  "cardiac_catheterization_reports": "Heart catheter procedure results",
  "cardiac_rehabilitation_reports": "Heart recovery program progress",
  "cardiology_admission_notes": "Heart-related hospital admissions",
  "cardiology_consultations": "Cardiologist evaluations",
  "cardiology_followup_reports": "Ongoing cardiac care monitoring",
  "ecg_reports": "Electrocardiogram results",
  "echo_reports": "Echocardiogram (heart ultrasound) results",
  "stress_test_reports": "Cardiac stress testing results",

  // Neurology
  "diagnostic_studies": "Neurological testing and imaging",
  "eeg_reports": "Brainwave activity recordings",
  "emg_reports": "Muscle and nerve electrical activity tests",
  "interval_history": "Changes since last neurology visit",
  "neurology_consultations": "Neurologist evaluations",
  "neurology_progress_notes": "Ongoing neurological care documentation",
  "neuropsychological_assessments": "Cognitive and behavioral evaluations",

  // Psychiatry & Mental Health
  "mental_health_assessments": "Psychological and psychiatric evaluations",
  "psychiatric_discharge_summaries": "Mental health hospitalization summaries",
  "psychiatric_evaluations": "Comprehensive mental health assessments",
  "psychiatric_progress_notes": "Ongoing psychiatric treatment notes",
  "therapy_session_notes": "Psychotherapy session documentation",

  // Pediatrics
  "apgar_scores": "Newborn health assessment at birth",
  "developmental_assessments": "Child development milestone evaluations",
  "newborn_screening_results": "Newborn genetic and metabolic testing",
  "pediatric_growth_charts": "Child height, weight, and head circumference tracking",
  "pediatric_vaccination_records": "Childhood immunization history",
  "pediatric_visits": "Well-child and sick-child visit notes",
  "well_child_examinations": "Routine pediatric health checks",

  // Obstetrics & Gynecology
  "amniocentesis_reports": "Amniotic fluid testing results",
  "gynecology_consultations": "Women's health specialist evaluations",
  "labor_delivery_records": "Childbirth documentation",
  "maternal_fetal_reports": "Pregnancy monitoring results",
  "obstetric_ultrasound_reports": "Pregnancy ultrasound findings",
  "postpartum_notes": "Post-delivery care documentation",
  "prenatal_testing_reports": "Pregnancy screening test results",
  "prenatal_visits": "Pregnancy care appointment notes",
  "ultrasound_ob_reports": "Obstetric ultrasound imaging results",

  // Oncology
  "chemotherapy_records": "Cancer drug treatment documentation",
  "oncology_consultations": "Cancer specialist evaluations",
  "oncology_followup_reports": "Ongoing cancer care monitoring",
  "oncology_treatment_plans": "Comprehensive cancer therapy strategies",
  "radiation_therapy_records": "Radiation treatment documentation",
  "tumor_board_notes": "Multidisciplinary cancer care discussions",
  "tumor_marker_panels": "Blood tests for cancer monitoring",

  // Endocrinology
  "diabetes_management_notes": "Diabetes care and monitoring",
  "endocrinology_consultations": "Hormone specialist evaluations",
  "hormone_panels": "Endocrine laboratory testing",
  "hormone_therapy_records": "Hormone replacement treatment documentation",
  "thyroid_evaluations": "Thyroid function assessments",

  // Gastroenterology
  "colonoscopy_reports": "Colon examination results",
  "endoscopy_reports": "Upper GI examination results",
  "gastroenterology_consultations": "Digestive system specialist evaluations",
  "ibd_consultation_details": "Inflammatory bowel disease specialist notes",
  "mayo_score": "IBD disease activity scoring",
  "symptom_progression_timeline": "IBD symptom tracking over time",
  "infliximab_drug_monitoring": "Biologic medication level tracking",
  "fecal_calprotectin": "Intestinal inflammation marker",
  "rescue_therapy_options": "IBD flare treatment alternatives",
  "ibd_care_team": "Multidisciplinary IBD care providers",
  "barriers_psychosocial_issues": "Social and psychological challenges in IBD care",
  "inflammatory_bowel_reports": "IBD assessment and monitoring",
  "liver_function_assessments": "Liver health evaluations",

  // Pulmonology
  "asthma_management_notes": "Asthma care and control documentation",
  "copd_assessments": "Chronic lung disease evaluations",
  "pulmonary_function_tests": "Lung capacity and function measurements",
  "pulmonary_rehabilitation_notes": "Lung disease recovery program notes",
  "pulmonology_consultations": "Lung specialist evaluations",
  "sleep_study_reports": "Sleep apnea and sleep disorder testing",

  // Nephrology
  "dialysis_records": "Kidney replacement therapy documentation",
  "dialysis_run_sheets": "Individual dialysis session records",
  "dialysis_run_sheet": "Single dialysis treatment documentation",
  "pre_dialysis_assessment": "Patient evaluation before dialysis",
  "dialysis_prescription": "Dialysis treatment orders",
  "dialyzer": "Dialysis machine and filter specifications",
  "dialysate_composition": "Dialysis fluid composition",
  "intradialytic_monitoring": "Vital signs during dialysis",
  "medications_administered": "Drugs given during dialysis",
  "post_dialysis_assessment": "Patient evaluation after dialysis",
  "kidney_function_reports": "Renal function assessments",
  "nephrology_consultations": "Kidney specialist evaluations",
  "nephrology_consultation_details": "Detailed kidney care plans",
  "kidney_disease_progression_timeline": "Chronic kidney disease tracking",
  "estimated_time_to_dialysis": "Projected dialysis start timeline",
  "education_initiated": "Patient education about kidney disease",
  "access_planning": "Dialysis access preparation",
  "depression_screening": "Mental health assessment in kidney disease",
  "advance_directive_discussion": "End-of-life planning in kidney disease",
  "prognosis_discussion": "Kidney disease outcome discussions",
  "transplant_evaluations": "Kidney transplant candidacy assessments",

  // Rheumatology
  "arthritis_assessments": "Joint disease evaluations",
  "autoimmune_evaluations": "Immune system disorder assessments",
  "autoimmune_panels": "Autoantibody laboratory testing",
  "rheumatology_consultations": "Rheumatologist evaluations",

  // Hematology
  "blood_disorder_reports": "Blood disease assessments",
  "bone_marrow_reports": "Bone marrow biopsy and aspiration results",
  "coagulation_studies": "Blood clotting function tests",
  "hematology_consultations": "Blood disorder specialist evaluations",

  // Orthopedics
  "orthopedic_consultations": "Bone and joint specialist evaluations",
  "orthopedic_followup_notes": "Ongoing orthopedic care monitoring",
  "orthopedic_operative_reports": "Bone and joint surgery documentation",

  // Ophthalmology
  "glaucoma_assessments": "Eye pressure and optic nerve evaluations",
  "ophthalmology_examinations": "Comprehensive eye exams",
  "retinal_examinations": "Back-of-eye evaluations",
  "visual_acuity_reports": "Vision testing results",

  // ENT (Ear, Nose, Throat)
  "audiometry_reports": "Hearing testing results",
  "ent_consultations": "Ear, nose, and throat specialist evaluations",
  "laryngoscopy_reports": "Throat and voice box examination results",

  // Dermatology
  "dermatology_consultations": "Skin specialist evaluations",
  "dermatology_procedure_notes": "Skin procedure documentation",
  "skin_biopsy_reports": "Skin tissue sample results",

  // Urology
  "cystoscopy_reports": "Bladder examination results",
  "urodynamic_studies": "Bladder function testing",
  "urology_consultations": "Urologist evaluations",

  // Geriatrics
  "cognitive_evaluations": "Memory and thinking assessments",
  "fall_risk_assessments": "Fall prevention evaluations",
  "geriatric_assessments": "Comprehensive elderly care evaluations",
  "polypharmacy_reviews": "Multiple medication safety reviews",

  // Pathology
  "autopsy_reports": "Post-mortem examination findings",
  "biopsy_reports": "Tissue sample microscopic analysis",
  "cytology_reports": "Cell sample analysis",
  "pathology_reports": "Tissue diagnosis and analysis",

  // Radiology & Imaging
  "bone_scan_reports": "Nuclear medicine bone imaging results",
  "dexa_scan_reports": "Bone density measurements",
  "interventional_radiology_notes": "Image-guided procedure documentation",
  "mammography_reports": "Breast imaging results",
  "mri_reports": "Magnetic resonance imaging results",
  "pet_scan_reports": "Positron emission tomography results",
  "radiology_reports": "General imaging study results",

  // Laboratory & Specialized Tests
  "antibiogram_reports": "Antibiotic resistance testing",
  "blood_glucose_logs": "Blood sugar monitoring records",
  "flow_cytometry_reports": "Cell population analysis",
  "genetic_testing_reports": "DNA and genetic analysis results",
  "microbiology_culture_reports": "Bacterial culture and sensitivity results",
  "toxicology_reports": "Drug and poison screening results",

  // Dental
  "dental_examination_reports": "Oral health evaluations",
  "oral_surgery_reports": "Dental surgical procedure documentation",
  "orthodontic_treatment_plans": "Teeth straightening care plans",
  "periodontal_charts": "Gum disease assessments",

  // Physical Therapy & Rehabilitation
  "cognitive_rehabilitation_reports": "Brain injury recovery therapy",
  "occupational_therapy_reports": "Daily living skills therapy",
  "physical_therapy_evaluations": "Movement and function assessments",
  "physical_therapy_notes": "Physical rehabilitation session notes",
  "rehabilitation_progress_notes": "Recovery therapy monitoring",
  "speech_therapy_assessments": "Communication and swallowing evaluations",

  // Nursing & Clinical Notes
  "intake_output_records": "Fluid intake and output tracking",
  "medication_administration_records": "Medication delivery documentation",
  "medication_administration_record": "Individual medication administration log",
  "scheduled_medications": "Regularly timed medication doses",
  "prn_medications": "As-needed medication doses",
  "iv_infusions": "Intravenous fluid and medication delivery",
  "blood_glucose_monitoring": "Blood sugar measurement tracking",
  "omissions_refusals": "Missed or declined medications",
  "nurse_signatures": "Nursing staff verification",
  "pharmacy_review": "Pharmacist medication assessment",
  "monitoring_reports": "Patient status observation records",
  "nicu_progress_notes": "Neonatal intensive care documentation",
  "nursing_assessments": "Nurse patient evaluations",
  "pain_assessment_forms": "Pain level and character documentation",
  "progress_notes": "Ongoing care documentation",
  "shift_handoff_notes": "Nursing shift change communication",
  "soap_notes": "Subjective, objective, assessment, plan notes",
  "therapy_progress_notes": "Treatment response monitoring",
  "vital_signs_logs": "Vital sign measurement records",
  "wound_care_documentation": "Wound treatment and healing tracking",
  "wound_care_notes": "Wound assessment and management",

  // Emergency & Critical Care
  "code_blue_summaries": "Cardiac arrest response documentation",
  "ems_run_reports": "Ambulance and paramedic records",
  "poison_control_reports": "Toxicology consultation records",
  "rapid_response_summaries": "Emergency response team activations",
  "trauma_flow_sheets": "Major injury care documentation",

  // Administrative & Legal
  "administrative_data": "Non-clinical patient information",
  "disability_evaluations": "Work disability assessments",
  "dnr_orders": "Do not resuscitate orders",
  "fitness_for_duty_evaluations": "Work readiness assessments",
  "insurance_forms": "Insurance authorization documentation",
  "medical_power_of_attorney": "Healthcare proxy documentation",
  "medical_reconciliation_forms": "Medication list verification",
  "prior_authorization_forms": "Insurance pre-approval requests",
  "school_health_forms": "Student health documentation",
  "travel_health_certificates": "International travel health clearance",
  "workers_comp_evaluations": "Work injury assessments",
  "document_metadata": "Document classification information",
  "workplace_accommodations": "Work modification recommendations",
  "employment_counseling": "Job-related support services",
  "insurance_authorizations": "Insurance approval documentation",

  // Patient Education & Social
  "care_coordination_notes": "Multi-provider care collaboration",
  "home_health_notes": "In-home nursing care documentation",
  "hospice_notes": "End-of-life care documentation",
  "pain_management_notes": "Pain control strategies",
  "malnutrition_risk_assessment": "Malnutrition screening and risk evaluation",
  "patient_education_records": "Patient teaching documentation",
  "social_work_notes": "Social services documentation",
  "mental_health_resources": "Psychological support referrals",
  "stress_management_referrals": "Stress reduction program referrals",
  "exercise_recommendations": "Physical activity prescriptions",
  "communication_preferences": "Patient contact preferences",
  "data_management_instructions": "Health information management guidance",

  // Telemedicine & Second Opinions
  "case_summaries": "Comprehensive case reviews",
  "second_opinion_reports": "Alternative expert evaluations",
  "telemedicine_encounters": "Virtual visit documentation",

  // Research & Clinical Trials
  "clinical_trial_documents": "Research study participation records",
  "research_consent_forms": "Research participation agreements",

  // Additional Medical Documentation
  "hospital_course": "Hospitalization timeline and events",
  "specialty_fields": "Specialized medical data",
  "flexible_data": "Unstructured medical information",
  "surgical_history": "Past surgical procedures",
  "family_history": "Family medical conditions and genetics",
  "social_history": "Lifestyle, occupation, and social factors",
  "chief_complaints": "Primary reasons for medical visit",
  "history_present_illness": "Current illness timeline and details",
  "review_of_systems": "Symptom review by body system",
  "physical_examinations": "Physical exam findings",
  "assessment_plans": "Medical impressions and treatment plans",
  "additional_notes": "Supplementary medical information",
  "risk_factors": "Disease risk identification",
  "follow_up_appointments": "Scheduled future visits",
  "follow_up_enhanced": "Detailed follow-up planning",
  "disease_severity": "Condition intensity assessment",
  "urgent_call_criteria": "When to seek immediate care",
  "data_upload_instructions": "Remote monitoring data submission",
  "twenty_four_seven_support": "24/7 care access information",

  // Emergency Medicine Fields
  "emergency_information": "Emergency contact and medical alerts",
  "triage_data": "Emergency department prioritization",
  "ed_course": "Emergency department care timeline",
  "consultation_timeline": "Specialist consultation sequence",
  "preoperative_preparation": "Pre-surgery preparation steps",
  "pre_operative_preparation": "Surgical readiness procedures",
  "blood_products_ordered": "Transfusion requests",
  "ed_disposition": "Emergency department discharge plan",
  "injury_details": "Trauma mechanism and severity",
  "procedural_sedation": "Sedation for emergency procedures",
  "work_restrictions": "Return-to-work limitations",

  // Diabetes/Endocrinology Fields
  "diabetes_management": "Diabetes care plans and monitoring",
  "insulin_pump_settings": "Insulin pump configuration",
  "cgm_data": "Continuous glucose monitor readings",
  "insulin_regimen": "Insulin dosing schedules",
  "diabetes_education": "Diabetes self-management training",
  "diabetes_educator": "Diabetes educator consultations",
  "hypoglycemia_management": "Low blood sugar treatment plans",
  "endocrine_lab_results": "Hormone laboratory testing",
  "preconception_counseling": "Pregnancy planning with diabetes",
  "diabetes_quality_metrics": "Diabetes care quality measures",
  "pump_download_analysis": "Insulin pump data review",
  "foot_exam": "Diabetic foot examination",
  "diabetes_supplies": "Diabetes equipment and supplies",
  "fertility_tracking": "Reproductive health monitoring",
  "pump_advanced_settings": "Advanced insulin pump features",
  "insulin_timing_instructions": "Insulin administration timing",
  "hypoglycemia_protocol": "Low blood sugar response plan",
  "basal_rate_adjustments": "Background insulin dose changes",
  "bolus_adjustments": "Mealtime insulin dose changes",

  // IBD/Gastroenterology Fields
  "ibd_assessment": "Inflammatory bowel disease evaluation",
  "disease_activity_scores": "IBD severity measurements",
  "endoscopy_findings": "GI scope examination results",
  "ibd_biomarkers": "IBD inflammation markers",
  "biologic_therapy": "Advanced IBD medication treatment",
  "extraintestinal_manifestations": "IBD effects outside intestines",
  "ibd_surgical_planning": "Surgery planning for IBD",
  "flare_management": "IBD symptom exacerbation treatment",

  // Geriatrics Fields
  "cancer_surveillance": "Cancer screening in elderly",
  "functional_status": "Ability to perform daily activities",
  "geriatric_cognitive_assessment": "Elderly memory evaluations",
  "falls_prevention_program_assessment": "Elderly fall prevention evaluation",
  "polypharmacy_review": "Multiple medication management in elderly",
  "quality_assurance": "Care quality monitoring",
  "lymph_node_cytomorphology": "Lymph node cell analysis",
  "cytogenetics": "Chromosome analysis",
  "staging_summary": "Cancer extent classification",
  "geriatric_nutritional_assessment": "Elderly nutrition evaluation",
  "mood_psychological_assessment": "Elderly mental health evaluation",
  "social_functional_assessment": "Elderly social support evaluation",
  "frailty_assessment": "Elderly weakness and vulnerability evaluation",
  "geriatric_care_planning": "Future care preferences documentation",
  "caregiver_assessment": "Caregiver burden and support evaluation",

  // Oncology Fields
  "cancer_diagnosis": "Cancer identification and confirmation",
  "cancer_staging": "Cancer extent and spread classification",
  "myeloma_specific_data": "Multiple myeloma details",
  "chemotherapy_regimen": "Cancer drug treatment protocols",
  "radiation_therapy": "Radiation treatment plans",
  "transplant_assessment": "Stem cell transplant evaluation",
  "performance_status": "Cancer patient functional capacity",
  "tumor_markers": "Cancer biomarker measurements",
  "clinical_trials": "Cancer research study participation",
  "response_assessment": "Cancer treatment effectiveness evaluation",
  "toxicity_assessment": "Cancer treatment side effect monitoring",
  "palliative_care_needs": "Symptom management and comfort care",
  "treatment_summary": "Comprehensive cancer treatment overview",
  "surgical_oncology": "Cancer surgery documentation",
  "radiation_oncology": "Radiation therapy details",
  "endocrine_therapy": "Hormone therapy for cancer",
  "bone_health": "Bone density and fracture risk in cancer",
  "survivorship_care_plan": "Post-cancer treatment follow-up",
  "cancer_related_side_effects": "Cancer treatment complications",
  "oncologic_emergencies": "Life-threatening cancer complications",
  "psychosocial_oncology": "Emotional and social cancer support",
  "genetic_oncology": "Hereditary cancer risk assessment",
  "prognostic_factors": "Cancer outcome predictors",
  "integrative_oncology": "Complementary cancer therapies",
  "prophylactic_medications": "Preventive medications in cancer care",
  "pre_chemotherapy_workup": "Pre-treatment cancer assessments",
  "renal_protection_plan": "Kidney protection during cancer treatment",
  "pain_management_plan": "Cancer pain control strategy",
  "supportive_care": "Cancer symptom management",
  "insurance_authorization": "Treatment approval documentation",
  "oncology_team": "Cancer care team members",

  // Obstetrics Fields
  "obstetric_history": "Pregnancy and delivery history",
  "current_pregnancy": "Active pregnancy monitoring",
  "reproductive_history": "Fertility and pregnancy history",
  "prenatal_screening": "Pregnancy genetic and health screening",
  "nt_scan_result": "Nuchal translucency ultrasound",
  "cell_free_dna_result": "Non-invasive prenatal testing",
  "first_trimester_screen_result": "Early pregnancy screening",
  "anatomy_scan_result": "Mid-pregnancy detailed ultrasound",
  "cervical_length_measurement": "Preterm labor risk assessment",
  "fetal_echo_result": "Fetal heart ultrasound",
  "perinatal_mental_health_referral": "Pregnancy mental health support",
  "fetal_ultrasound": "Pregnancy ultrasound imaging",
  "gestational_diabetes": "Pregnancy-related diabetes",
  "fetal_surveillance": "Fetal well-being monitoring",
  "pregnancy_complications": "Pregnancy medical issues",
  "delivery_planning": "Birth preparation and preferences",
  "maternal_labs": "Pregnancy laboratory testing",
  "prenatal_visit": "Pregnancy care appointments",
  "maternal_weight_monitoring": "Pregnancy weight tracking",
  "fetal_assessment": "Fetal health evaluation",
  "contraction_monitoring": "Labor pattern tracking",
  "pregnancy_symptoms": "Pregnancy-related complaints",
  "prenatal_education": "Pregnancy health education",
  "birth_plan": "Delivery preferences documentation",
  "postpartum_planning": "Post-delivery care planning",
  "pregnancy_risk_assessment": "High-risk pregnancy evaluation",
  "pregnancy_course": "Pregnancy timeline and events",
  "risk_counseling": "Pregnancy risk discussion",
  "ketone_monitoring_instructions": "Pregnancy diabetic ketone testing",
  "glucometer_download_schedule": "Blood sugar data review schedule",
  "carbohydrate_counting_education": "Diabetes meal planning education",
  "amniotic_fluid_index_current": "Current amniotic fluid volume",
  "breastfeeding_recommendation": "Infant feeding guidance",
  "partner_involvement": "Partner participation in pregnancy care",
  "diabetes_management_plan": "Pregnancy diabetes treatment plan",
  "single_embryo_transfer_details": "IVF embryo transfer information",
  "single_embryo_transfer": "Single embryo IVF procedure",
  "preeclampsia_monitoring": "Pregnancy high blood pressure surveillance",
  "infection_risk_monitoring": "Pregnancy infection prevention",
  "partner_involvement_diabetes_management": "Partner support in diabetes care",
  "excessive_glucose_monitoring": "Frequent blood sugar testing",
  "macrosomia_threshold": "Large baby risk monitoring",
  "postpartum_diabetes_risk": "Diabetes risk after delivery",
  "gdm_recurrence_risk": "Gestational diabetes recurrence",
  "cervical_assessment": "Cervix evaluation during pregnancy",

  // Nephrology Fields
  "ckd_assessment": "Chronic kidney disease evaluation",
  "proteinuria_assessment": "Protein in urine evaluation",
  "dialysis_planning": "Kidney replacement therapy preparation",
  "current_dialysis": "Active dialysis treatment",
  "transplant_evaluation": "Kidney transplant candidacy assessment",
  "mineral_bone_disease": "Bone disease from kidney failure",
  "renal_anemia": "Anemia from kidney disease",
  "fluid_electrolyte_management": "Fluid and salt balance management",
  "renal_nutrition": "Kidney disease diet planning",
  "medication_renal_dosing": "Medication adjustment for kidney function",
  "glomerular_disease": "Kidney filtering unit disease",
  "acute_kidney_injury": "Sudden kidney function loss",
  "polycystic_kidney_disease": "Inherited kidney cyst disease",
  "diabetic_nephropathy": "Diabetes-related kidney disease",
  "hypertensive_nephropathy": "High blood pressure kidney damage",

  // Neurology Fields
  "movement_disorder_assessment": "Abnormal movement evaluation",
  "parkinsonian_features": "Parkinson's disease symptoms",
  "gait_analysis": "Walking pattern evaluation",
  "motor_complications": "Movement disorder treatment side effects",
  "non_motor_symptoms": "Non-movement Parkinson's symptoms",
  "neurological_exam": "Nervous system physical examination",
  "parkinson_medications": "Parkinson's disease drug treatment",
  "deep_brain_stimulation": "Brain electrical stimulation therapy",
  "epilepsy_assessment": "Seizure disorder evaluation",
  "headache_assessment": "Headache type and severity evaluation",
  "multiple_sclerosis_assessment": "MS disease evaluation",
  "stroke_assessment": "Brain attack evaluation",
  "dementia_assessment": "Memory disorder evaluation",
  "peripheral_neuropathy": "Nerve damage evaluation",
  "neuromuscular_disorder": "Muscle and nerve disease",

  // Surgery Fields
  "surgical_team": "Surgical staff and roles",
  "operative_details": "Surgical procedure specifics",
  "anesthesia_record": "Anesthesia administration details",
  "surgical_approach": "Surgical technique and access",
  "intraoperative_findings": "Discoveries during surgery",
  "operative_technique": "Surgical methods used",
  "intraoperative_imaging": "Imaging during surgery",
  "specimens": "Tissue samples removed",
  "estimated_blood_loss": "Blood loss during surgery",
  "complications": "Surgical problems and adverse events",
  "postoperative_orders": "Post-surgery care instructions",
  "postoperative_condition": "Patient status after surgery",
  "discharge_planning": "Hospital discharge preparation",

  // Orthopedics Fields
  "mechanism_of_injury": "How injury occurred",
  "orthopedic_imaging": "Bone and joint imaging",
  "orthopedic_assessment": "Musculoskeletal evaluation",
  "orthopedic_procedures": "Bone and joint procedures",
  "ligament_reconstruction": "Ligament repair surgery",
  "meniscus_repair": "Knee cartilage repair",
  "articular_cartilage": "Joint surface cartilage",
  "tourniquet_data": "Surgical blood flow restriction",
  "postop_testing": "Post-surgery orthopedic testing",
  "rehabilitation_protocol": "Physical therapy plan",
  "return_to_sport": "Athletic activity clearance",
  "dvt_prophylaxis": "Blood clot prevention",
  "venous_thromboembolism_risk": "VTE risk scoring and prophylaxis planning",
  "performance_assessment": "Sports performance testing and return-to-play evaluation",
  "treatment_goals": "Structured treatment goals with timeframes and measures",
  "document_type": "Document classification and ICD-10/CPT coding metadata",
  "neurovascular_exam": "Nerve and blood vessel examination",
  "athlete_specific_data": "Sports-related medical information",

  // Pediatrics Fields
  "birth_history": "Birth and newborn period details",
  "growth_parameters": "Height, weight, head circumference",
  "developmental_milestones": "Child development achievements",
  "pediatric_screening": "Childhood health screenings",
  "school_performance": "Academic progress",
  "anticipatory_guidance": "Preventive parenting education",
  "behavioral_assessment": "Child behavior evaluation",
  "adhd_assessment": "Attention deficit hyperactivity evaluation",
  "parental_concerns": "Parent-reported worries",
  "well_child_summary": "Routine child health visit summary",
  "early_childhood_development": "Young child development",

  // Clinical Scores and Functional Assessments
  "clinical_scores": "Standardized medical scoring systems",
  "functional_assessment": "Daily activity capability evaluation",
  "consultation_details": "Specialist consultation specifics",
  "medication_reconciliation": "Medication list verification and updates",
  "supplementation_plans": "Vitamin and supplement recommendations",
  "trend_analysis": "Pattern tracking over time",
  "home_monitoring": "Remote patient monitoring",
  "care_coordination": "Multi-provider care collaboration",
  "prognosis": "Expected disease outcome",

  // Additional Missing Fields
  "age": "Patient age",
  "allergy_assessment": "Comprehensive allergy testing and evaluation",
  "allergy_immunology_assessment": "Detailed immunological allergy workup with IgE testing",
  "anesthesiology_assessment": "Anesthesia risk evaluation",
  "asthma_action_plan": "Asthma self-management instructions",
  "asthma_assessment": "Asthma severity and control evaluation",
  "autoantibody_profile": "Autoimmune disease antibody testing",
  "biopsychosocial_formulation": "Integrated medical-psychological-social assessment",
  "cardiology_assessment": "Cardiac evaluation",
  "colorectal_surgery_assessment": "Colon and rectal surgery evaluation",
  "connective_tissue_disease_assessment": "Systemic rheumatic disease evaluation",
  "copd_assessment": "Chronic obstructive pulmonary disease evaluation",
  "date": "Document date",
  "department": "Clinical department",
  "dermatology_assessment": "Skin condition evaluation",
  "diagnostic_impression": "Clinical diagnosis summary",
  "document_type": "Type of medical document",
  "emergency_assessment": "Emergency department evaluation",
  "endocrinology_assessment": "Hormone disorder evaluation",
  "ent_assessment": "Ear, nose, throat evaluation",
  "environmental_exposures": "Toxic or allergenic exposure history",
  "facility": "Healthcare facility name",
  "family_meeting_notes": "Family conference documentation",
  "gender": "Patient gender",
  "gout_assessment": "Gout evaluation and management",
  "headers": "Document section headers",
  "homicide_risk_assessment": "Violence risk evaluation",
  "imaging": "Imaging studies ordered or performed",
  "immunization_record": "Vaccination documentation",
  "immunization_status": "Current immunization status",
  "infectious_disease_assessment": "Infection specialist evaluation",
  "inflammatory_markers": "Inflammation laboratory tests",
  "lupus_assessment": "Systemic lupus erythematosus evaluation",
  "fetal_echo": "Fetal heart ultrasound",
  "umbilical_artery_doppler": "Fetal blood flow ultrasound",
  "insulin_adjustment_protocol": "Insulin dose adjustment instructions",
  "postpartum_glucose_monitoring": "Blood sugar monitoring after delivery",
  "amniotic_fluid_assessment": "Amniotic fluid volume evaluation",
  "continuous_glucose_monitor": "Real-time blood sugar monitoring device",
  "weekly_virtual_check_ins": "Scheduled telehealth appointments",
  "south_asian_nutritionist": "Cultural nutrition counseling",
  "indian_diet_exchange_lists": "Cultural food portion guides",
  "cultural_considerations": "Culturally sensitive care planning",
  "thyroid_management": "Thyroid hormone treatment",
  "total_weight_gain": "Total pregnancy weight gain",
  "pre_pregnancy_weight": "Weight before pregnancy",
  "fetal_echo_results": "Fetal heart ultrasound findings",
  "diabetes_educator_training": "Diabetes education sessions",
  "exercise_program": "Physical activity prescription",
  "early_maternity_leave": "Work leave before delivery",
  "download_glucometer": "Blood sugar meter data download",
  "estimated_delivery_date": "Expected birth date",
  "first_trimester_bleeding": "Early pregnancy bleeding",
  "support_group_referral": "Peer support program referral",
  "continuous_glucose_monitor_discussion": "CGM education and planning",
  "glucose_monitoring_goals": "Target blood sugar ranges",
  "insulin_storage_instructions": "Insulin handling guidelines",
  "cesarean_threshold": "C-section decision criteria",
  "glucose_testing_weeks": "Blood sugar testing schedule",
  "point_of_care_ultrasound_heart_rate": "Bedside fetal heart rate check",
  "lab_schedule": "Laboratory testing timeline",
  "growth_ultrasound_schedule": "Fetal growth scan schedule",
  "inter_pregnancy_weight_management": "Weight control between pregnancies",
  "glucose_monitoring_frequency": "Blood sugar testing frequency",
  "sleep_disturbances": "Sleep problem documentation",
  "work_accommodations": "Workplace modifications",
  "patient_emotional_response": "Patient emotional state",
  "comprehensive_cardiomyopathy_panel": "Heart muscle disease genetic testing",
  "detailed_family_pedigree": "Family tree genetic mapping",
  "acmg_guidelines_reference": "Genetic testing interpretation standards",
  "inheritance_pattern_details": "Genetic disease transmission pattern",
  "children_specific_risk": "Offspring genetic risk",
  "cascade_testing_protocol": "Family genetic testing plan",
  "potential_testing_outcomes": "Possible genetic test results",
  "psychosocial_support_services": "Emotional support resources",
  "reason_for_referral": "Why patient was referred",
  "medical_geneticist": "Genetics specialist",
  "extended_family_history": "Multi-generational health history",
  "genetics_psychosocial_assessment": "Genetic counseling support evaluation",
  "immediate_recommendations": "Urgent action items",
  "variant_interpretation_guidelines": "Genetic variant classification",
  "prior_authorization_status": "Insurance approval status",
  "blood_sample_collection_status": "Lab specimen status",
  "fmla_documentation_note": "Family medical leave paperwork",
  "mental_status_exam": "Psychiatric mental state evaluation",
  "myositis_assessment": "Muscle inflammation evaluation",
  "neurosurgery_assessment": "Brain and spine surgery evaluation",
  "nuclear_medicine_assessment": "Radiotracer imaging evaluation",
  "nutritional_assessment": "Dietary and nutrition evaluation",
  "past_ocular_history": "Previous eye conditions",
  "ophthalmology_exam": "Eye examination",
  "glaucoma_management": "Eye pressure treatment",
  "post_op_testing": "Post-surgery testing",
  "pain_management": "Pain control strategies",
  "pathology_report": "Tissue diagnosis report",
  "patient_id": "Patient identifier",
  "patient_name": "Patient full name",
  "physical_examination": "Physical exam findings",
  "plastic_surgery_assessment": "Reconstructive surgery evaluation",
  "pmr_assessment": "Physical medicine and rehabilitation evaluation",
  "preventive_medicine_assessment": "Preventive care evaluation",
  "procedures": "Medical procedures performed",
  "psychiatry_assessment": "Mental health evaluation",
  "pulmonology_assessment": "Lung disease evaluation",
  "radiation_oncology_assessment": "Radiation therapy evaluation",
  "radiology_assessment": "Imaging study evaluation",
  "rheumatology_assessment": "Rheumatic disease evaluation",
  "scleroderma_assessment": "Systemic sclerosis evaluation",
  "sports_medicine_assessment": "Athletic injury evaluation",
  "suicide_risk_assessment": "Self-harm risk evaluation",
  "surgical_pathology": "Surgical specimen analysis",
  "transplant_surgery_assessment": "Organ transplant evaluation",
  "urology_assessment": "Urological evaluation",
  "vascular_surgery_assessment": "Blood vessel surgery evaluation",
  "job_hazard_analysis": "Workplace hazard identification and risk controls",
  "vascular_bypass_surgery": "Bypass graft surgery details and hemodynamics",
  "venous_insufficiency_assessment": "Venous reflux and insufficiency evaluation",
  "aortic_aneurysm_surveillance": "Aortic aneurysm monitoring and measurements",
  "trauma_assessment": "Trauma triage and primary survey evaluation",
  "trauma_scoring": "Trauma severity scores (GCS, ISS, RTS, TRISS)",
  "emergency_procedures": "Emergency procedures performed and outcomes",
  "immunization_schedule": "Vaccine administration schedule and documentation",
  "travel_vaccination_records": "Travel vaccinations and destination risk details",
  "facial_trauma_assessment": "Facial fracture and trauma evaluation",
  "vital_signs_table": "Tabulated vital sign measurements",
  "patient_provider": "Healthcare provider list",

  // AI-Generated Clinical Insights (Document Mode)
  "clinical_decision_support": "AI-powered risk assessment with drug interactions and contraindications",
  "intelligent_recommendations": "AI-generated immediate, short-term, and long-term care recommendations",
  "trending_analysis": "AI analysis of vital signs trends and disease progression over time",
  "patient_specific_care_plan": "Personalized AI care plan considering occupation, lifestyle, and barriers",
  "medication_optimization": "AI medication cost analysis, adherence risk, and simplification opportunities",
  "follow_up_intelligence": "AI-prioritized follow-up tasks with auto-scheduling and coordination needs",
  "patient_education_context": "AI-generated patient-friendly explanations and medication instructions",
  "quality_metrics": "AI assessment of guideline compliance, care gaps, and outcome predictions",
  "guideline_compliance": "Adherence to clinical practice guidelines"
};

/**
 * Get description for a collection
 * @param {string} collectionName - Name of the collection
 * @returns {string} Human-readable description
 */
function getCollectionDescription(collectionName) {
  return COLLECTION_DESCRIPTIONS[collectionName] || "Medical data collection";
}

/**
 * Check if a description exists for a collection
 * @param {string} collectionName - Name of the collection
 * @returns {boolean}
 */
function hasDescription(collectionName) {
  return collectionName in COLLECTION_DESCRIPTIONS;
}

module.exports = {
  COLLECTION_DESCRIPTIONS,
  getCollectionDescription,
  hasDescription
};
